### PR TITLE
Update CLI reference nav titles

### PR DESCRIPTION
**Pull request by dannykng**
## Preview URL

https://docs-5jaho91jk-supabase.vercel.app/docs/reference/cli/introduction

## What kind of change does this PR introduce?

- Update nav menu titles
- Remove unused metadata in Supabase CLI overview guide (to kick off preview build)
Screenshot 2023-01-10 at 6 32 22 PM
Screenshot 2023-01-10 at 6 33 37 PM
Screenshot 2023-01-10 at 6 33 51 PM

### CODE REVIEW

**Comment by sweatybridge** [comment]
Also I looked into docker and kubernetes cli reference docs
- https://docs.docker.com/engine/reference/commandline/cli/
- https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

Both of them use command string as title in the nav bar. It's quite different from the way stripe does it. Personally I find it clearer to have the list of commands shown up front, with detailed descriptions available after navigating. Wdyt?

**Comment by MildTomato** [comment]
@sweatybridge we support accordion menus.
See https://supabase.com/docs/reference/javascript/using-filters
(scroll up and down)

**Comment by MildTomato** [comment]
We don't need to have subsection titles. It's just the other ref docs make use of them, as it's easy to then visually split up the content based on 'product'.

@sweatybridge we do support accordion menus.
See https://supabase.com/docs/reference/javascript/using-filters
(scroll up and down)

**Comment by dannykng** [comment]
> Also I looked into docker and kubernetes cli reference docs
> 
> * https://docs.docker.com/engine/reference/commandline/cli/
> * https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
> 
> Both of them use command string as title in the nav bar. It's quite different from the way stripe does it. Personally I find it clearer to have the list of commands shown up front, with detailed descriptions available after navigating. Wdyt?

@sweatybridge I don't think one is necessarily better than the other. It's more what do we expect users to do more often. Look up what a command does or which command they need to use to accomplish a particular task?

My assumption is on the latter and natural language titles are more approachable to new users and experienced users can still search by the exact command string if they want to. Don't have a strong opinion on this though so we can change it back if you think that would be better for users.

**Comment by dannykng** [comment]
@MildTomato getting this error when I try to add an "accordion":

error

I'm probably doing something wrong though. Example:
```
{
  "id": "supabase-gen",
  "title": "Run code generation tools",
  "slug": "supabase-gen",
  "type": "cli-command",
  "items": [
    {
      "id": "supabase-gen-types",
      "title": "Generate types (Postgres schema)",
      "slug": "supabase-gen-types",
      "type": "cli-command"
    },
    {
      "id": "supabase-gen-types-typescript",
      "title": "Generate types (TypeScript)",
      "slug": "supabase-gen-types-typescript",
      "type": "cli-command"
    }
  ]
}
```

**Comment by dannykng** [comment]
@MildTomato can we have the docs build for changes in the `/spec` directory?

**Comment by sweatybridge** [comment]
> Look up what a command does or which command they need to use to accomplish a particular task?

I agree these are different UX goals that our design need to cater for. Imo, our guides section is more suited to focus on the latter while the reference section should focus on the former. People unfamiliar with the CLI would start with a particular task in mind, which more often than not requires multiple commands. For eg.

- To generate types: user needs to run `login`, `link`, then `gen`.
- To start local development: user needs to `init`, then `start`.

Once users are familiar with the basic commands but couldn't accomplish what they want to do, they would want to go straight to a command to read about advanced use cases and related commands. I think having nav titles as command strings would cater for this group of experienced users.

So in a way, new users would want to read our guides if they have a particular task in mind. Power users would want to read our reference section which easily maps to the commands they remembered.

**Comment by MildTomato** [comment]
@dannykng example of accordion 
https://github.com/supabase/supabase/blob/j0/add_python_v2_spec/spec/common-client-libs-sections.json/#L627-L642

**Comment by MildTomato** [comment]
ah sorry there is an issue with accordions active state - think we need to fix this so accordions can be added anywhere

cc @saltcod

**Review by sweatybridge — APPROVED** [review]
Anyway this is not blocking for me. Feel free to merge when ready

**Pull request merged**
