### PR TITLE
Fixes mobile width/ratio issue on all blog post YouTube video iframe embeds

### PR DESCRIPTION
**Pull request by onkarhanchate14**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?
image

Please link any relevant issues here.
https://github.com/supabase/supabase/issues/12234

## What is the new behavior?
image

Feel free to include screenshots if it includes visual changes.

## Additional context
- Adds <div className="video-container"> above <iframe> in all apps/www/_blog/*mdx files.
- Adds in proper format
- More details provided in issue - https://github.com/supabase/supabase/issues/12234

Add any other context or screenshots.

### CODE REVIEW

**Comment by ruggi99** [comment]
Duplicate of #12245 ?

**Comment by onkarhanchate14** [comment]
> Duplicate of #12245 ?

In #12245, he missed couple of files to add and also the formatting of code is not correct.
So created new PR

**Review by kiwicopple — APPROVED** [review]
this is a MONSTER pr @onkarhanchate14 - thank you!

Feel free to reach out on twitter and I can send you a swag code for a free tshirt

**Comment by onkarhanchate14** [comment]
> this is a MONSTER pr @onkarhanchate14 - thank you!
> 
> Feel free to reach out on twitter and I can send you a swag code for a free tshirt

Thanks a lot @kiwicopple 
This was my first contribution to Supabase, I'll surely keep making contributions to Supabase daily.

**Comment by kiwicopple** [comment]
I see this is branch off #12245  - I'll merge that first then revisit this

**Comment by onkarhanchate14** [comment]
> I see this is branch off #12245 - I'll merge that first then revisit this

Okay, sure

**Pull request merged**
