### PR TITLE
Added a readme file of urdu language and gave it's link in the main readme file

### PR DESCRIPTION
**Pull request by ibilalkayy**
## What kind of change does this PR introduce?

In this PR, I created a new readme file in Urdu translation and gave the link to that translated readme file in the main readme file also.

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by MildTomato** [comment]
I don't speak Urdu but OpenAI likes the translation.
as of commit https://github.com/supabase/supabase/pull/19010/commits/2112c156874c18477d20edb4e4d7e4b40087d0d1

**Comment by ibilalkayy** [comment]
@MildTomato But those who speak Urdu can understand it because I am an Urdu and Pashto speaker and I am making Pashto translations also.

I wrote this translation in one day because it was manual, not with ChatGPT.

**Comment by MildTomato** [comment]
> > I don't speak Urdu but OpenAI likes the translation.
based on commit https://github.com/supabase/supabase/commit/2112c156874c18477d20edb4e4d7e4b40087d0d1

> @MildTomato But those who speak Urdu can understand it because I am an Urdu and Pashto speaker and I am currently working on the Pashto translations also.

> I wrote this translation in one day because it was manual, not with ChatGPT.

@ibilalkayy 

Just to be transparent, just so it's clear what I meant:

The reason I wrote that is so the repo maintainers are informed that the translation is trustworthy. We are vigilant on checking contributions that are written in languages we don't speak as they could contain content that is inappropriate that might had been submitted by a malicious contributor.

Hope that helps, I certainly didn't mean anything negative 😄 

Thanks for the translation contribution @ibilalkayy - this is what makes the Supabase project so awesome ⚡

**Comment by ibilalkayy** [comment]
@MildTomato No problem. This is your right to check it. If you missed something or want me to change the translation in it, I can edit this commit again.

**Comment by MildTomato** [comment]
@ibilalkayy you might need to run `npm run format --write` to fix the prettier check issues

**Pull request closed without merging**
