### PR TITLE
Center notifications dismiss button

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Center notifications dismiss button

## What is the current behavior?

Notifications dismiss button is position to the top.

## What is the new behavior?

Notifications dismiss button is position in the center.

## Additional context

CleanShot 2023-08-11 at 12 50 53@2x

### CODE REVIEW

**Review by vikashviraj — APPROVED** [review]
LGTM 👍

**Comment by Isaiah-Hamilton** [comment]
> Is there a task associated with this? Personally I kinda like the top right position 😅

Their is no task associated with this, just noticed it and can't unsee it.

**Comment by alaister** [comment]
Let's let @MildTomato be the tiebreaker 👍🏻

**Comment by saltcod** [comment]
My vote is top right too I'm afraid 🥲

**Pull request closed without merging**
