### PR TITLE
add `target="_blank" rel="noreferrer"` to external links

### PR DESCRIPTION
**Pull request by brunocrosier**
Bug fix, feature, docs update, ...

## What is the current behavior?

Clicking an external link opens it in the same tab, meaning you lose any chagnes which are in progress

## What is the new behavior?

External links open in a new tab

### CODE REVIEW

**Comment by Chensokheng** [comment]
@brunocrosier You can take a look at this feedback. https://github.com/supabase/supabase/pull/9398/files/f47eadf261936bc2359823bc5a48444536307730#diff-eece05ef427c700391d4b3887548b0de9c52378c69c30244e2b67f22227b7c05

**Review by Isaiah-Hamilton — APPROVED** [review]

**Review by alaister — APPROVED** [review]
@brunocrosier Thank you for this!

**Comment by brunocrosier** [comment]
> @brunocrosier Thank you for this!

cheers!

**Comment by MildTomato** [comment]
Screenshot 2022-10-14 at 3 56 44 PM

ahh, we're going to need to update Button component to use the type of the preferred `as` prop selection.
ie, if its `as="a"` then we need to use the types for an anchor element

**Comment by MildTomato** [comment]
checking preview tests on a duplicate PR
https://github.com/supabase/supabase/pull/9553

**Pull request merged**
