### PR TITLE
Chore: Update README images

### PR DESCRIPTION
**Pull request by tomoyukiy**
## What kind of change does this PR introduce?

- Update README images #16294 
- Fixed some README files that "Architecture" images were not showing up.
[i18n/README.es.md](https://github.com/supabase/supabase/blob/master/i18n/README.es.md)
[i18n/README.ko.md](https://github.com/supabase/supabase/blob/master/i18n/README.ko.md)
[i18n/README.nb.md](https://github.com/supabase/supabase/blob/master/i18n/README.nb.md)
[i18n/README.nl.md](https://github.com/supabase/supabase/blob/master/i18n/README.nl.md)

### Top
https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--light.svg
https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--dark.svg

### Architecture
https://user-images.githubusercontent.com/70828596/187547862-ffa9d058-0c3a-4851-a3e7-92ccfca4b596.png

### Top
https://user-images.githubusercontent.com/8291514/213727234-cda046d6-28c6-491a-b284-b86c5cede25d.png
https://user-images.githubusercontent.com/8291514/213727225-56186826-bee8-43b5-9b15-86e839d89393.png

### Architecture
https://github.com/supabase/supabase/blob/master/apps/docs/public/img/supabase-architecture.png

### CODE REVIEW

**Review by Isaiah-Hamilton — CHANGES_REQUESTED** [review]
The top images need to stay as [https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--light.svg#gh-light-mode-only](https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--light.svg) and [https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--light.svg#gh-light-mode-only](https://raw.githubusercontent.com/supabase/supabase/master/packages/common/assets/images/supabase-logo-wordmark--light.svg). The architecture image can be [https://github.com/supabase/supabase/blob/master/apps/docs/public/img/supabase-architecture.png](https://github.com/supabase/supabase/blob/master/apps/docs/public/img/supabase-architecture.png)

**Review by gregnr — APPROVED** [review]
Good one, thanks @tomoyukiy!

**Comment by gregnr** [comment]
@Isaiah-Hamilton looks like we're inconsistent on logo images between readmes. Is there a reason we use a different logo image here vs. the main readme?

**Comment by Isaiah-Hamilton** [comment]
> @Isaiah-Hamilton looks like we're inconsistent on logo images between readmes. Is there a reason we use a different logo image here vs. the main readme?

Sorry I meant to put the main readme image as the top image for the i18n readme's. All the i18n readme images are supposed to have the same image as the main readme image. Same goes for the Architecture image.

**Comment by tomoyukiy** [comment]
@gregnr @Isaiah-Hamilton 
Should I change only the architecture image?

**Comment by Isaiah-Hamilton** [comment]
Sorry for the confusion, You should change the i18n readme top images to the main readme top image, [example](https://github.com/supabase/supabase/blob/master/README.md?plain=1#L1-L4). and change the i18n architecture image to the main readme architecture image, [example](https://github.com/supabase/supabase/blob/master/README.md?plain=1#L62). Hope this clarifies things.

**Comment by tomoyukiy** [comment]
@Isaiah-Hamilton 
I changed the i18n Readme top image to the main Readme top image.
https://user-images.githubusercontent.com/8291514/213727234-cda046d6-28c6-491a-b284-b86c5cede25d.png
https://user-images.githubusercontent.com/8291514/213727225-56186826-bee8-43b5-9b15-86e839d89393.png


I changed the i18n Readme architecture image to the main Readme architecture image.
https://github.com/supabase/supabase/blob/master/apps/docs/public/img/supabase-architecture.png

Would you please check again?
https://github.com/tomoyukiy/supabase/tree/issues-16294/i18n

**Comment by Isaiah-Hamilton** [comment]
@tomoyukiy Just checked, everything looks good. Push the changes to the pull request and I'll approve it.

**Comment by tomoyukiy** [comment]
@Isaiah-Hamilton 
Thank you for confirming.

I have already pushed that change.
Please check the changes.
https://github.com/supabase/supabase/pull/16296/files

**Review by Isaiah-Hamilton — APPROVED** [review]

**Comment by tomoyukiy** [comment]
@Isaiah-Hamilton 
I merged the latest source code into this branch.
Do I need to be approved in order to proceed with the workflow?

**Comment by tomoyukiy** [comment]
@gregnr 
Do I need to be approved in order to proceed with the workflow?

**Pull request merged**
