### PR TITLE
fixed a typo in the docs

### PR DESCRIPTION
**Pull request by siddhantmadhur**
change a mistype of "thier" to "their"

## What kind of change does this PR introduce?

Update on the docs, to fix the typo

## What is the current behavior?

Spelt "thier"

## What is the new behavior?

Spelt "their"

## Additional context

image

### CODE REVIEW

**Comment by sizzleman** [comment]
WOW! THIS IS A GOOD ONE(important too...).
Best typo found in the 21st century

**Comment by sizzleman** [comment]
also buddy,
verfiFIED should be veriFIES

**Comment by kiwicopple** [comment]
>  Best typo found in the 21st century

hey @sizzleman - please don't discourage contributions, no matter small. Supabase's goal is to increase the number of open source contributors, and that's a lot easier if the community is encouraging to eachother. Thanks!

**Comment by J0** [comment]
Hey @SiddhantMadhur,

Thanks for the PR!  It _is_ an important PR on two fronts:

1. It contributes to the overall experience of the experience since a single typo can break the experience of reading a document

2. It's a place to get started. I personally feel that it can be intimidating looking at a large codebase and doc PRs are a simple way to get started. So, I think this PR is valid and @SiddhantMadhur please feel free to re-open the PR. If you'd be keen I'd be happy to guide you through the process of a slightly more intensive task(like documenting a provider).

Let us know!

P.S.:  I think the `verified` -> `verifies` change is valid too. If anyone would like to please feel free to open a PR and I'll review

**Comment by kiwicopple** [comment]
:) Siddhant already opened a new PR with the verified fix too: https://github.com/supabase/supabase/pull/5245

**Pull request closed without merging**
