### PR TITLE
fix(studio): use SUPABASE_REST_URL for autogenerated API

### LINKED ISSUE #5816: The API section of the local Studio is inaccessible (500)
# Bug report

## Describe the bug

When I use the Supabase CLI to start a local instance of Supabase, I cannot access the API section in the studio. This comment in the Discussions goes into detail about it: https://github.com/supabase/supabase/discussions/5489#discussioncomment-2280409

## To Reproduce

1. Install the Supabase CLI from AUR
2. Run `supabase init`
3. Run `supabase start`
4. Open the Studio at http://localhost:54323/
5. Navigate to the API section at http://localhost:54323/project/default/api

## Expected behavior

The API section opens correctly

## System information

- OS: Arch Linux on WSL2
- Browser (if applies): N/A
- Version of supabase-js: N/A
- Version of Node.js: N/A
- Version of Supabase CLI: `r199.48bc07a-1` (installed from AUR)

## Additional context

Similar issues have been filed previously: https://github.com/supabase/supabase/issues/4550, https://github.com/supabase/supabase/issues/5066. The difference of this issue is that it's using the Supabase CLI, so it's not obvious where one wouls provide the envs that fixed this problem for Docker users.

### PR DESCRIPTION
**Pull request by soedirgo**
Fixes #5816

### CODE REVIEW

**Review by burmecia — COMMENTED** [review]
Could you add this env var to `docker/.env.example` as well so it can work when self hosting with Docker?

**Comment by soedirgo** [comment]
Updated :+1:

**Review by burmecia — APPROVED** [review]

**Comment by bnjmnt4n** [comment]
Just a note: this causes the curl code snippets to begin with the `http://kong:8000/` URL, which is not accessible publicly.

**Comment by soedirgo** [comment]
Ah just noticed that - I guess we should instead be using one internal endpoint + one public endpoint, instead of one internal endpoint + one REST endpoint

**Pull request merged**
