### PR TITLE
bug fix: notification count not showing in light mode

### LINKED ISSUE #16536: Notification count not showing in light mode
If you have notifications, the count number doesn't show in light mode:

CleanShot 2023-08-15 at 09 05 38@2x

### PR DESCRIPTION
**Pull request by SuhelMakkad**
## What kind of change does this PR introduce?

fixes: #16536 

## What is the current behavior?

Screenshot 2023-08-15 at 7 14 08 PM

## What is the new behavior?

Screenshot 2023-08-15 at 7 13 44 PM

## Additional context

background color was set to white for both light and dark modes, so I have changed it to black for light mode

### CODE REVIEW

**Comment by Zaib001** [comment]
If you're using a state management solution like Vuex, ensure that the notification count is stored and accessed correctly in your state. Make sure updates to the count trigger proper reactivity.

**Comment by SuhelMakkad** [comment]
@Zaib001 - The issue is not related to the state or anything else. It is just that the background color for the counter was not correct in light mode.

**Review by rahul-adnabu — APPROVED** [review]

**Review by Isaiah-Hamilton — APPROVED** [review]

**Comment by Zaib001** [comment]
I see if the issue is related to the background color of the counter not displaying correctly in light mode, it sounds like a styling issue. To resolve this, you can take the following steps:

Inspect Element Styles:
Use your browser's developer tools to inspect the element that represents the notification counter in light mode. Check the applied styles, especially the background color property, to see if it's set correctly.

Check CSS Classes:
Verify that the CSS classes or styles you're applying for the notification counter's background color in light mode are correctly defined and have the expected color value.

Check Theme Variables:
If you're using CSS variables for your theme, ensure that the correct variable is being used to set the background color of the notification counter in light mode.

Check Styles Cascade:
Sometimes, CSS styles can be overridden by more specific selectors or styles later in the stylesheet. Make sure there are no conflicting styles that might be affecting the background color.

Check Component Styles:
Review the styles applied directly to the component that hosts the notification counter. Sometimes, local component styles might unintentionally override global styles.

Check Conditional Styling:
If you have conditional styling based on themes, double-check the logic to make sure that the background color is set appropriately for both light and dark modes.

Use a Specific Class:
Instead of relying on theme variables directly, consider applying a specific CSS class to the notification counter element in light mode. This can help isolate the styling for this specific case.

Hardcoded Value for Testing:
As a troubleshooting step, you can temporarily set a hardcoded background color value to the notification counter to confirm if the issue is indeed related to the styling.

Try Inline Styles:
Apply inline styles directly to the notification counter component to see if the background color changes as expected. This can help verify if the issue is related to the styling definitions.

Browser Compatibility:
Ensure that the issue is consistent across different browsers. Sometimes, browser-specific rendering behavior can lead to unexpected styling discrepancies.

Theme CSS Overrides:
If you're using a prebuilt theme or CSS framework, check if any predefined styles might be affecting the background color of the notification counter. Sometimes, these frameworks come with default styles that you might need to override.

Ask for Design Feedback:
If you're still unable to resolve the issue, consider seeking feedback from designers or colleagues to ensure that the background color you're using is in line with the design specifications.

**Comment by dubeyx** [comment]
good

**Comment by SuhelMakkad** [comment]
@saltcod, please review review the PR

**Pull request merged**
