### PR TITLE
Confirmation modal to triggers

### PR DESCRIPTION
**Pull request by 3ru**
## What kind of change does this PR introduce?

- Check if a form has been edited and launch a confirmation modal if necessary.
- some CSS refactor
## What is the current behavior?

The user loses the change directly.

## What is the new behavior?

If the form is changed, a confirmation modal opens

## Additional context

Add any other context or screenshots.

behavior

### CODE REVIEW

**Review by saltcod — APPROVED** [review]

**Comment by saltcod** [comment]
Nice one @3ru, thanks!

**Comment by saltcod** [comment]
@brandongregoryscott any chance you've got ideas on this one? Running into the same heap size issue. I increased your 10k to 20k, but still same issue.

**Comment by brandongregoryscott** [comment]
Hmmm - let me pull this branch down. I didn't spend a lot of time trying to reproduce the issue locally, but maybe that's the next step. I assume Jest has a config option for configuring the max heap size, which may help for local reproduction & tuning the config.

**Comment by brandongregoryscott** [comment]
@saltcod I'm still investigating, not entirely sure where the issue lies. Using the `--expose-gc` flag for `node` and the `--logHeapUsage` flag for jest, it seems like these tests are allocating a really good chunk of memory:

in `studio/package.json`:
```diff
-    "test": "jest",
+    "test": "node --max-old-space-size=2048 --expose-gc ../node_modules/.bin/jest --logHeapUsage",
```

I'm seeing 1GB+ for a lot of these test suites:
```
studio:test: PASS tests/pages/projects/LogEventChart.test.js (1119 MB heap size)
studio:test: PASS tests/pages/projects/PreviewFilterPanel.test.js (1067 MB heap size)
studio:test: PASS tests/components/CopyButton.test.tsx (1358 MB heap size)
studio:test: PASS tests/pages/projects/Logs.Datepickers.test.js (1107 MB heap size)
studio:test: PASS tests/pages/projects/Logs.utils.test.js (1153 MB heap size)
studio:test: PASS tests/components/Editor/SpreadsheetImport.utils.test.js (1092 MB heap size)
studio:test: PASS tests/pages/projects/logs-explorer/saved.test.js (1110 MB heap size)
studio:test: PASS tests/components/Billing/TaxID.utils.test.js (1057 MB heap size)
studio:test: PASS tests/components/ui/Charts/Charts.utils.test.ts (1070 MB heap size)
studio:test: PASS tests/components/Reports/ReportWidget.test.js (1396 MB heap size)
studio:test: PASS tests/components/Grid/Grid.utils.test.js (1147 MB heap size)
studio:test: PASS tests/components/Auth/Auth.constants.test.js (1020 MB heap size)
studio:test: PASS tests/components/Storage/StorageSettings.utils.test.js (1043 MB heap size)
```

Reducing the `testTimeout` from 20000 to 10000 as it was previously seems to reduce average heap size, but still pretty large:

````
studio:test: PASS tests/pages/projects/PreviewFilterPanel.test.js (684 MB heap size)
studio:test: PASS tests/pages/projects/LogEventChart.test.js (686 MB heap size)
studio:test: PASS tests/pages/projects/LogsQueryPanel.test.js (750 MB heap size)
studio:test: PASS tests/pages/projects/Logs.Datepickers.test.js (1007 MB heap size)
studio:test: PASS tests/components/CopyButton.test.tsx (717 MB heap size)
studio:test: PASS tests/components/Reports/ReportWidget.test.js (717 MB heap size)
studio:test: PASS tests/pages/projects/logs-explorer/saved.test.js (794 MB heap size)
studio:test: PASS tests/pages/projects/Logs.utils.test.js (1041 MB heap size)
studio:test: PASS tests/components/ui/Charts/Charts.utils.test.ts (739 MB heap size)
studio:test: PASS tests/components/Grid/Grid.utils.test.js (720 MB heap size)
studio:test: PASS tests/components/Auth/Auth.constants.test.js (1004 MB heap size)
studio:test: PASS tests/components/Storage/StorageSettings.utils.test.js (687 MB heap size)
studio:test: PASS tests/components/Billing/TaxID.utils.test.js (691 MB heap size)
studio:test: PASS tests/components/Editor/SpreadsheetImport.utils.test.js (716 MB heap size)
```

I started taking a look at the `render` wrapper that is used in a lot of these tests to setup common providers/etc, but commenting out different pieces of it didn't seem to make a meaningful difference.

**Comment by brandongregoryscott** [comment]
Still haven't really found a root cause, but one thing that might be worth trying is running jest with the `--runInBand` flag. [Based on this StackOverflow answer](https://stackoverflow.com/a/44506948), it might be a better option for CI since the memory/CPU resources are more limited.

**Comment by 3ru** [comment]
Hi, Has this CI issue been resolved?

**Pull request merged**
