### PR TITLE
chore: use www.youtube-nocookie.com to remove youtube cookie tracking

### PR DESCRIPTION
**Pull request by MildTomato**
## What kind of change does this PR introduce?

Changed embedded videos from youtube to use privacy focussed `youtube-nocookies` domain.

## What is the new behavior?

Removes all youtube/google tracking cookies 🔥

### CODE REVIEW

**Comment by kiwicopple** [comment]
Wow, didn't know this was a thing.

There does still seem to be a cookie though right? Is this some sort of "essential" cookie?

https://main-git-chore-remove-youtube-cookies.supabase.vercel.app/blog/2021/02/02/supabase-beta-january-2021

image

**Comment by MildTomato** [comment]
> There does still seem to be a cookie though right? Is this some sort of "essential" cookie?

That's weird, why is the iframe using youtube.com rather than youtube-nocookies.com

**Comment by MildTomato** [comment]
@kiwicopple Is there a problem with vercel preview?

from https://main-git-chore-remove-youtube-cookies.supabase.vercel.app/blog/2021/02/02/supabase-beta-january-2021
Screenshot 2021-02-10 at 16 15 21

github:
Screenshot 2021-02-10 at 16 15 16

**Comment by MildTomato** [comment]
> There does still seem to be a cookie though right? Is this some sort of "essential" cookie?

When I tested locally, iframes using youtube-cookies.com had no cookies at all 😄

**Comment by kiwicopple** [comment]
You could be right @MildTomato - I think this is once again a quirk of our monorepo+vercel. If you're happy that it's working locally, let's do it 👍 

Also TIL about `youtube-nocookies.com` - very useful

**Comment by MildTomato** [comment]
@kiwicopple let's deploy it and see what happens 🤙

**Pull request merged**
