### PR TITLE
fix: new connection pool config video added to the page

### LINKED ISSUE #7172: docs: update text and vidoe on `Finding the connection pool config`
# Improve documentation

## Link 

[Finding the connection pool config](https://supabase.com/docs/guides/database/connecting-to-postgres#finding-the-connection-pool-config)

## Describe the problem

The description and video on 'Finding the connection pool config' is outdated with latest dashboard UI.

## Describe the improvement

The connection pool config is now at `https://app.supabase.com/project/_/settings/database`, the text and video needs to be updated.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?
Fixes #7172 
Docs update: Video update that demonstrates where to find the connection pool config settings

## What is the current behavior?

The current video is outdated and doesn't show the correct place to find information about connection pool config

## What is the new behavior?

Video demonstrating the new way to perform the conifg connection pool

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by kiwicopple** [comment]
hey @gitstart - this is awesome, but the file is huge! would you mind compressing it ? I generally use ffmpeg to compress & convert to mp4:


```
ffmpeg -i "./input.mov" -vcodec h264 -acodec mp2 "./output.mp4"
```

**Comment by gitstart** [comment]
> hey @gitstart - this is awesome, but the file is big! would you mind compressing it ? I generally use ffmpeg to compress & convert to mp4:
> 
> ```
> ffmpeg -i "./input.mov" -vcodec h264 -acodec mp2 "./output.mp4"
> ```

@kiwicopple Thanks for the recommendation. I've resized the video to about half it's prior size

**Comment by gitstart** [comment]
@kiwicopple Does this mean this ticket is complete?

**Comment by pucho** [comment]
@gitstart We're recently aiming for videos to be 500/600kb every 10 seconds at roughly 1080p, so we can keep the repo size down. I already prepared a video for this PR, and here's the link so you don't have to work more on this. Please update and I'll approve.

https://we.tl/t-ne7OQq9Hub

Thanks!

**Comment by gitstart** [comment]
Hey @dannykng ,
Thanks for the video. I've updated the video but made another PR with the same changes [here](https://github.com/supabase/supabase/pull/8806). We updated out fork because of permission issues, so please bear with me

**Pull request closed without merging**
