### PR TITLE
feat: command to query a table

### PR DESCRIPTION
**Pull request by charislam**
Creates this subpage:

image

Selecting a table brings you to the SQL editor with this prefilled:

image

### CODE REVIEW

**Comment by joshenlim** [comment]
hahaha caught this in my previous stress testing scenarios 😂 
im guessing the highlighting logic is ignoring cases on the table name?
image

**Comment by charislam** [comment]
@joshenlim 

> my table names give this vibe 😂

I love it 😂 

good catch with the highlighting, nice stress testing there

I quoted all identifiers that need to be quoted in SQL, in the interest of "educating users about SQL" (didn't feel right to write it as `schema.tableName` when it's not valid), but I guess we don't do that anywhere else in the dashboard, so I'll take it out

**Comment by charislam** [comment]
@joshenlim should be fixed now!

**Comment by jordienr** [comment]
lgtm! tested in preview environment

**Review by jordienr — APPROVED** [review]

**Pull request merged**
