### PR TITLE
Feat: add support policy

### PR DESCRIPTION
**Pull request by mansueli**
## What kind of change does this PR introduce?

This PR includes the scope of the support on a page, so it creates clear expectations for the users about what is included in the support service.

## What is the current behavior?

We don't have it yet.

### CODE REVIEW

**Review by Isaiah-Hamilton — COMMENTED** [review]
Wouldn't it be better to put this with rest of our policies in `www`. for example our [Privacy Policy](https://supabase.com/privacy) and [Acceptable Use Policy](https://supabase.com/aup)

**Comment by mansueli** [comment]
> Wouldn't it be better to put this with rest of our policies in `www`. for example our [Privacy Policy](https://supabase.com/privacy) and [Acceptable Use Policy](https://supabase.com/aup)

Maybe, I have no strong opinions either way. But usually, folks are looking for support content in the docs/guides pages. 
This would also include this in the Command + K /Clippy by being in the docs.

**Comment by KevinBrolly** [comment]
@mansueli I am +1 on @Isaiah-Hamilton's idea of putting it under www. under something like `/support-policy` - what do you think?

**Comment by mansueli** [comment]
No strong opinions. Made an alternate PR:

https://github.com/supabase/supabase/pull/14311

Whichever gets merged, I am happy with it.

**Comment by mansueli** [comment]
Closed as the other one was merged.

**Pull request closed without merging**
