### PR TITLE
Fix errors being swallowed in account_page.dart and login_page.dart fixes #27104

### LINKED ISSUE #27104: Flutter User Management Tutorial fails to catch and display many errors
# Improve documentation

## Link 

[Add a link to the page which needs improvement (if relevant)](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter?platform=android#get-the-api-keys)

## Describe the problem

SnackBars are not being displayed properly, so errors are swallowed from the user perspective. onError is not implemented for supabase sdk calls, so errors are being swallowed there too from a developer and user persepective. Makes it hard and confusing to follow along as a new flutter user.

## Describe the improvement

Change all calls in the documentation of 

`SnackBar(...);
`
to

`ScaffoldMessenger.of(context).showSnackBar(SnackBar(....));
`

I don't know if this is a recent change to flutter or something but you can't just construct a SnackBar widget and expect it to be displayed, you must show it.

Add an onError handler to this block in login_page.dart. 

```
  @override
  void initState() {
    _authStateSubscription = supabase.auth.onAuthStateChange.listen((data) {
      if (_redirecting) return;
      final session = data.session;
      if (session != null) {
        _redirecting = true;
        Navigator.of(context).pushReplacementNamed('/account');
      }
    });
    super.initState();
  }
```

### PR DESCRIPTION
**Pull request by tpfaff**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix, fixes #27104 

## What is the current behavior?

[Please link any relevant issues here.](https://github.com/supabase/supabase/issues/27104)

Errors get swallowed from a user and developer perspective

## What is the new behavior?

Errors are reliably propagated to user, SnackBars that were instantiated but not shown are now shown.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by dshukertjr** [comment]
@tpfaff 
Good call about the snackbars not showing up. Do you want to update the guide too to match the new code that you have?
https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/getting-started/tutorials/with-flutter.mdx

**Comment by tpfaff** [comment]
> @tpfaff Good call about the snackbars not showing up. Do you want to update the guide too to match the new code that you have? https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/getting-started/tutorials/with-flutter.mdx

Can do, working on it!

**Comment by dshukertjr** [comment]
Awesome! Thank you so much! Feel free to let me know when it's ready for a review!

**Comment by tpfaff** [comment]
@dshukertjr Should be good to review now

**Comment by dshukertjr** [comment]
Thanks for the amazing work, and sorry, I have been sick for the past few days. Will take a look tomorrow!

**Review by dshukertjr — APPROVED** [review]
Thank you so much for this PR!

**Pull request merged**
