### PR TITLE
Showcase section added for web 🥳

### LINKED ISSUE #169: Built with Supabase Site
This is a Hacktoberfest task! 
You can read more about Hacktoberfest [on our blog](https://supabase.io/blog/2020/09/11/supabase-hacktoberfest-2020) and see all tasks on our [Hacktoberfest Project Board](https://github.com/orgs/supabase/projects/5).

# Summary

We need a "Built with Supabase" showcase site

A showcase of sites and services that are built on Supabase with 

## Details

Some ideas:

- create a new website (Next.js)
- add a section to our current Docusaurus site
- an indicator of whether they are open source and a link to source code if available
- Create an easy way for people to add their site (PR or via a form?)

### PR DESCRIPTION
**Pull request by ephelsa**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Closes #169

## What is the new behavior?

Added a Showcase section for supabase.io

out

### CODE REVIEW

**Comment by awalias** [comment]
ohhh this is sweet! @ephelsa 

@kiwicopple any feedback?

**Comment by awalias** [comment]
perhaps we can add it in, but hide the link until we populate the projects

**Comment by kiwicopple** [comment]
A couple of possible improvements with the buttons at the bottom of each card:

- If there is only one button ("Visit site"), it could stretch the full width
- If there are 2, then should be half the width, with a small gap

At the moment they feel like they are floating a bit. Otherwise it looks great!

**Comment by ephelsa** [comment]
@kiwicopple modifying. I like the suggestion.

Also, any feedback for the mobile version? 

supabase mobile

**Comment by kiwicopple** [comment]
That looks OK - I assume that's more at tablet width? My (subjective) suggestions are to do simplify, declutter:

- Remove the hashtag
- remove the light-grey background behind the card title
- remove the line under the card title

anything you can do to simplify is worthwhile. You don't need to do all of these if you don't want to, but at the moment the card doesn't feel cohesive, simply because too much is happening.

**Comment by ephelsa** [comment]
@kiwicopple the hashtags is an indicative for the "I like but..." scenario. Based on these:
* All: is open source + repo link + web site
* I like but...: is open source + web site
* Got money: web site
* I'm starting: nothing

Before I read the comment, this is the result:
out

**Comment by kiwicopple** [comment]
OK cool, thanks for adjusting the buttons - they look great. 

I have one final question: what happens when people upload images of different sizes? Does the card image handle that gracefully?

**Comment by ephelsa** [comment]
I like the result. Also, let me answer.

out

**Comment by kiwicopple** [comment]
Hey @ephelsa I marked this one as accepted (for Hacktoberfest) - I'm about to roll out some changes to the website so I won't merge it just yet. I'll aim for next week!

**Comment by ephelsa** [comment]
@kiwicopple if I can help, tell me! 😁

**Comment by kiwicopple** [comment]
Hey @ephelsa - looping back on this now that we updated the website. There are a couple of conflicts but if you can resolve them then I'd be happy to merge this in 👍

**Comment by ephelsa** [comment]
> Hey @ephelsa - looping back on this now that we updated the website. There are a couple of conflicts but if you can resolve them then I'd be happy to merge this in 👍 
> 

Yeah, give me a few hours to be free 😁

**Comment by kiwicopple** [comment]
No hurry!

**Comment by kiwicopple** [comment]
Nice! thanks @ephelsa . Amazing contribution

**Pull request merged**
