### PR TITLE
fix: typo in auth-sql-rules-examples.js

### PR DESCRIPTION
**Pull request by georgemoon**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Typo in SQL code

## What is the new behavior?

Fixed typo

## Additional context

Current bug visible on: https://supabase.com/auth

### CODE REVIEW

**Comment by georgemoon** [comment]
In fact this code block doesn't seem to execute in general, but "referenced" is not a Postgres command in any case :)

**Comment by georgemoon** [comment]
Maybe it should be aligned to the code found here:
https://supabase.com/docs/guides/auth/row-level-security#using-joins

```
-- 1. Create a table of teams
create table teams (
  id serial primary key,
  name text
);

-- 2. Create many to many join
create table members (
  team_id bigint references teams,
  user_id uuid references auth.users
);

-- 3. Enable RLS
alter table teams enable row level security;

-- 4. Create Policy
create policy "Team members can update team details if they belong to the team"
  on teams
  for update using (
    (select auth.uid()) in (
      select user_id from members
      where team_id = id
    )
  );
```

**Review by charislam — APPROVED** [review]

**Comment by charislam** [comment]
@georgemoon thanks! you're absolutely right, updated the code sample so it runs

**Review by Dustin4444 — COMMENTED** [review]
#41695

**Pull request merged**
