### PR TITLE
Contact page, which links to beta@, GitHub discussions, and GitHub Issues

### PR DESCRIPTION
**Pull request by hobbleabbas**
## What kind of change does this PR introduce?

Adds a contact page

## What is the current behavior?

Theres currently a support page in the docs, this is a separate contact page on the main site which links directly. The descriptions on the cards are from the support page (might affect SEO)

## What is the new behavior?

Previous page: 
Screen Shot 2021-06-12 at 9 44 32 PM

New Page:
Screen Shot 2021-06-12 at 9 45 23 PM

## Additional context

Could be redundant, feel free to ignore

### CODE REVIEW

**Comment by hobbleabbas** [comment]
Oh maybe I could add a FAQ section too?

**Comment by inian** [comment]
Can you check this build error @hobbleabbas? 
image

**Comment by hobbleabbas** [comment]
Found the error @inian, should be fixed in the change.

**Comment by hobbleabbas** [comment]
All checks passed 👍

**Comment by inian** [comment]
Yeah I think the contact and support pages are redundant. 

We can 
- rename new contact page to support
- remove the old /docs/support
- update all links to point to the new page

WDYT @kiwicopple @roryw10?

**Comment by kiwicopple** [comment]
Agreed on the actions that @inian has laid out 👍 

Also the page probably just needs 2 breakpoints - at the moment it looks like this on tablets:

image

And could probably just break immediately to this view:

image

**Comment by hobbleabbas** [comment]
Changed the footer link on site and removed the docs' Support page. Kept the file itself (in case anyone has it saved in their path for example). Should I keep a the support link on docs but map it to the new page perhaps? Docusaurus does [support](https://github.com/facebook/docusaurus/issues/827) this.

**Pull request merged**
