### PR TITLE
chore: add Supabase Beta update January 2022

### PR DESCRIPTION
**Pull request by MildTomato**
## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

Blog post added

Screenshot 2022-02-22 at 9 53 28 PM

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by MildTomato** [comment]
just fixing the youtube embeds

**Comment by MildTomato** [comment]
done

**Review by joshenlim — APPROVED** [review]
🚢

**Comment by kiwicopple** [comment]
legend, thanks @MildTomato - you probably could have put your name on this one :)

**Pull request merged**
