### PR TITLE
feat: add kubernetes support with Helm

### PR DESCRIPTION
**Pull request by icrotz**
## What kind of change does this PR introduce?

Feature, Docs

## What is the current behavior?

For the moment the only option to deploy Supabase is using Docker Compose or Kompose.

## What is the new behavior?

Adding a Helm chart to deploy a complete supabase architecture.

By following the README.me located in the `charts` directory you can start supabase in a `minikube` cluster easily.

It's also technically possible to deploy a production environment with replication and backup, but no documentation has been written on that.

_The Supabase Studio app is not protected, don't forget to disable it before going to production. You can also choose to use a Basic HTTP authentication if you use the nginx ingress controller_

## Additional context

- You need to have a kubernetes cluster to deploy the Helm chart. You can create have locally using [Minikube](https://minikube.sigs.k8s.io/docs/start/)
- We are using the bitnami chart to deploy the postgres database. 
- We are using a custom version of the bitnami postgres image to add the extension. You might want to publish this image on your account instead.
- I created another PR to allow the modification of the url used for the API documentation because at the moment it's hard coded. [ref](https://github.com/supabase/supabase/pull/4880)

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @icrotz - we just started a community library over here:
https://github.com/supabase-community/supabase-kubernetes

Perhaps we can open the PR there?

**Comment by milanvanschaik** [comment]
@icrotz Awesome work! I started over [here](https://github.com/supabase-community/supabase-kubernetes) but you're fast! I'll drop a review asap.

@kiwicopple I think it's easier to maintain if we put them in the main repo (like the docker-compose file), because of migrations and such. Thoughts?

**Comment by kiwicopple** [comment]
> if we put them in the main repo (like the docker-compose file), because of migrations and such. Thoughts?

The main problem of adding it to the main repo is that we don't (yet) have capacity to support it internally. If its in here, developers assume it's officially supported and we get a flood of questions on how to use/run it.

Perhaps we can add some sort of versioning, so that there is parity between the Docker + K8s on each version?

**Comment by icrotz** [comment]
@milanvanschaik Thanks, I had a lot of questions during the implemention regarding the scaling, the performance, the usage. I tried to create something in-between. So everyone can use it on a local cluster without k8s knowledge but its also possible to use it in production. The only missing part is the healthcheck / live prob.

I hesitated to create another repository before making the PR, my thoughts was: because Supabase focus is to provide a backend in less than 2 minutes and considering that K8s is becoming a standard for this kind of software, it would be normal for the community to expect a K8s support on the project. The fact that a lot of k8s operators now support easy install of software with Helm charts make me think this would be great. But maybe I'm wrong :/

Me and my team use Supabase for our mobile applications and we only use K8s for deployment. We can totally help you to support this feature.

If you want I can also move my code and make a PR to the other repository.

**Comment by milanvanschaik** [comment]
@icrotz I see, you did an awesome job already. I've to find some time to dive deeper into it to do a full review.

I think it might be worth it to put it as PR in the community repo for now, as I think @kiwicopple has a valid point with "officially" supporting it. I think it would still be easy to setup for people if we publish a Helm chart to the registry. And we could of course setup a PR with documentation on the Supabase docs site.

Though, indeed, we have to work with some sort of versioning to avoid things getting out of sync, and I'm not sure about that yet.

**Comment by kiwicopple** [comment]
> We can totally help you to support this feature.

Let's put it in the community repo for now, and once things seem settled/stable we can definitely move it back (with your support please!)

**Comment by icrotz** [comment]
Great ! I will create the PR in the community and close this one

**Comment by icrotz** [comment]
PR is available: https://github.com/supabase-community/supabase-kubernetes/pull/2
I'm closing this one for now

**Comment by kiwicopple** [comment]
thanks @icrotz !

**Comment by ryanpeach** [comment]
Do we have a PR for documentation? Any advice on how to start this documentation? I see this page:

https://supabase.com/docs/guides/self-hosting

Should it be

https://supabase.com/docs/guides/self-hosting/k8s

**Pull request closed without merging**
