### PR TITLE
feat/studio/logs: Adds storing of input values in query params when browsing logs

### PR DESCRIPTION
**Pull request by Ziinc**
This PR adds query params caching of input values to the omnibox, and input population on page mount, which allows us to link directly to specific queries/searches.

This is to allow for:
- clicking on usage chart bars links to specific point in time
- accidental refreshes will not cause query data to get lost (great for complex queries)
- users can craft queries and bookmark/share them

### CODE REVIEW

**Comment by chasers** [comment]
Was just thinking about this the other day, had not noticed!! Nice one!

**Comment by Ziinc** [comment]
Gotta perfect that UX 🙂 
Todos:
- [x] added query param loading
- [ ] set query params on execution

**Comment by Ziinc** [comment]
Ready for review 😬

**Comment by joshenlim** [comment]
@Ziinc ahh sorry, i just saw this PR - got some conflicts 🙏

**Comment by Ziinc** [comment]
@joshenlim will be adding in an extra input for allowing custom timestamp setting, will re-request review when done

**Comment by Ziinc** [comment]
https://user-images.githubusercontent.com/22714384/148529303-adc51dbb-2168-48e3-bd30-1bc40923c3a0.mov

Will add timestamp input in a separate PR, ready to review & merge.

**Comment by Ziinc** [comment]
Although not shown in demo, any refresh made to the page will automatically load values into editor/input, with editor taking priority.

**Review by kiwicopple — APPROVED** [review]
Looks great - the only change would be a UX one:

image


Not a huge fan of the "GO" and the button seems a bit squashed for some reason. Possible improvements:

- Remove the 🔍 icon from the left, and then make the button 🔍 instead of "GO"
- Make the button "RUN" like the one below it, or just "Search" (probably without the icon)
- Change "GO" for an ↩️ icon or whatever key command triggers the search

**Comment by Ziinc** [comment]
Went with option one, made it less squished by changing the input size to normal instead of tiny. Seems like setting both input and button to `tiny` makes it look squished.

image

**Pull request merged**
