### PR TITLE
fix: Table View no longer returns values when filter is applied on renamed column

### LINKED ISSUE #10306: Table View no longer returns values when filter is applied on renamed column
# Bug report

## Describe the bug

When setting a filter on the Table-view and renaming or removing the related column in the database, the view no longer loads and the filter cannot be removed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with column "a" and "b" of any type
2. Add a few records with test-data
3. Use the Table-view to filter on a value of column "a"
4. Rename column "a" to "c"
5. Open the Table-view
6. No values are returned, a SQL-error is displayed and the related filter cannot be removed

## Expected behavior

The applied filters should still be displayed so they can be removed in order to see results again.

## Screenshots
Scherm­afbeelding 2022-11-14 om 11 42 53

## System information

- OS: macOS
- Browser: Firefox 106.0.5

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

Fixes: https://github.com/supabase/supabase/issues/10306

## What is the current behavior?

If a column has an existing filter or sort rule, and the column is renamed, the rules are not renamed or deleted.
https://github.com/supabase/supabase/issues/10306

## What is the new behavior?

- When a column has a filter rule and this column is renamed, the filtering rule is also renamed as well
- When a column has a sort rule and this column is renamed, the sort rule is renamed as well

## Steps to test
Steps to reproduce the behavior, please provide code snippets or a repository:

- Create a table with column "a" and "b" of any type
- Add a few records with test-data
- Use the Table-view to filter on a value of column "a"
- Rename column "a" to "c"
- Verify that the filtering rule has also been renamed
- Follow same approach to test the sorting rule

## Demo

https://user-images.githubusercontent.com/45232708/202669259-7c8e199f-1119-4612-98e8-7010c2d882ff.mov

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Review by saltcod — APPROVED** [review]

**Comment by saltcod** [comment]
Great PR @gitstart ! Thank you!

**Comment by saltcod** [comment]
I've marked that as approved — can merge it in if you're ready to mark it Ready for Review. Thanks!

**Comment by saltcod** [comment]
Also, since you're pretty familiar with sorts and filters now, wanted to draw your attention to this one in case you haven't seen it:    

:^)

https://github.com/supabase/supabase/issues/9301

**Comment by joshenlim** [comment]
> A potential way to handle this could be to Catch the non existing column error, and show a modal instead of toast, which would prompt a user to update the filter rule, when user clicks “OK” the we update query string, WDYT?

@gitstart hmm i think let's just keep things simple - if the url path has sorts/filters for a non-existing column, lets just remove it from the url. The user can add back the filter/sort again if still needed - cause this edge case can also happen easily if users were to just open the table in the table editor with erroneous column names

perhaps lets ^ get this fixed first before getting this PR in :) thanks so much for all the contribution by the way! its amazing and incredibly helpful

**Comment by gitstart** [comment]
> I've marked that as approved — can merge it in if you're ready to mark it Ready for Review. Thanks!

@saltcod We marked this PR Ready for review

> Also, since you're pretty familiar with sorts and filters now, wanted to draw your attention to this one in case you haven't seen it...

@saltcod Thank you. We would love to take that issue. Could you please assign us that issue?

**Comment by saltcod** [comment]
Thanks @gitstart — Just reading Joshen's comment now and think that's probably wise to do before we merge this. 

Re https://github.com/supabase/supabase/issues/9301, looks like I can't assign to anyone outside of the Supabase org.  Feel free to grab it though & just leave a comment that you're starting in on it. Appreciated!

**Review by joshenlim — CHANGES_REQUESTED** [review]
Requested changes as per https://github.com/supabase/supabase/pull/10532#issuecomment-1358985332

and also to prevent PR from being accidentally merged in

**Comment by joshenlim** [comment]
hey there @gitstart! thanks so much for the update - i just tested on the staging preview but it seems like now, renaming a column that has an active sort/filter on the table editor doesnt update the active sort/filter but removes it instead

ideally we keep the original behaviour from this PR, but just remove sort/filters on columns which are no longer present

https://user-images.githubusercontent.com/19742402/215547253-c20b509f-b022-430d-95cd-5aa9d411e134.mov

**Comment by gitstart** [comment]
Hi @joshenlim.
PR has been updated now to support the desired behavior, kindly take a look.

**Comment by joshenlim** [comment]
@gitstart hey there! so sorry for the huge delay on this - would you mind pulling in the latest changes from master again and resolve the conflicts? i'll take a look again thereafter!

**Comment by saltcod** [comment]
Looks good! Thanks @gitstart

**Review by saltcod — APPROVED** [review]

**Review by saltcod — APPROVED** [review]

**Review by joshenlim — APPROVED** [review]

**Pull request merged**
