### PR TITLE
Fix: docs sidebar

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Fix docs sidebar

## What is the current behavior?

https://user-images.githubusercontent.com/70828596/220245941-afb20427-98a2-4731-a35a-a6bf450705e8.mp4

## What is the new behavior?

https://user-images.githubusercontent.com/70828596/220246107-af24a9ab-e937-4001-95ab-fd78326c1b15.mp4

### CODE REVIEW

**Comment by MildTomato** [comment]
@Isaiah-Hamilton updated this PR with the overflow-hidden method

**Comment by MildTomato** [comment]
Might also fix #12567 12396

**Review by kiwicopple — APPROVED** [review]

**Comment by Isaiah-Hamilton** [comment]
> this one good to go?

not yet

@MildTomato The return animation back home is still flashing. 

https://user-images.githubusercontent.com/70828596/220415996-670c4386-afaa-4c69-8ba3-c0f725567eb4.mp4

**Comment by MildTomato** [comment]
good enough, think it always did that

**Pull request merged**
