### PR TITLE
docs: fix sign up docs

### LINKED ISSUE #1872: docs: fix sign up docs
**Description**

In [Sign Up with Redirect](https://supabase.io/docs/reference/javascript/auth-signup#sign-up-with-redirect) documentation `supabase.auth.signUp` is used instead of `supabase.auth.signIn`.

```js
const { user, session, error } = await supabase.auth.signUp({
  provider: 'github'
}, {
  redirectTo: 'https://example.com/welcome'
})
```

**Improvement**

Change the the function to `supabase.auth.signIn`. Also change the order of sub-headings in example.

```js
const { user, session, error } = await supabase.auth.signIn({
  provider: 'github'
}, {
  redirectTo: 'https://example.com/welcome'
})
```

### PR DESCRIPTION
**Pull request by ghost**
**Description**

Closes #1872

**Changelog**

- [x] change the the function to `supabase.auth.signIn`
- [x] change the order of sub-headings in example

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @harshcut - this is a great PR, but now that I look at the docs it's very confusing that there are `signIn` examples in the `signUp` page (our fault). Perhaps we should:

- move all the `signIn()` code blocks to the `signIn()` page
- leave the headings + links in `signUp()` page to redirect the users to the relevant section

wdyt?

**Comment by harshcut** [comment]
> - move all the `signIn()` code blocks to the `signIn()` page
> - leave the headings + links in `signUp()` page to redirect the users to the relevant section

I think the below example would be best, with the `signIn()` link anchored to [using third-party providers](https://supabase.io/docs/reference/javascript/auth-signin#sign-in-using-third-party-providers).

image

**Comment by kiwicopple** [comment]
> with the signIn() link anchored to using third-party providers.

I agree! Are you happy to make these changes @harshcut ? I'll merge after that 🚢

**Comment by harshcut** [comment]
**Changelog**

- [x] remove third-party providers from sign up.

**Comment by kiwicopple** [comment]
Strange, it creates a code block below the text which says `Not yet implemented`:
https://docs-git-fork-harshcut-docs-signup-supabase.vercel.app/docs/reference/javascript/auth-signup#sign-up-with-third-party-providers

image


I think I need to make an adjustment to the documentation generator to fix this

**Comment by i-pip** [comment]
imho, I think this is more an api issue than a docs issue: 

federated signIn / signUp should really be the same api call behind the scenes and it should be left up to the thrid-party provider to decide whether what the user should get is an authorize page (sign up) or immediate redirect (sign in). 

imho I think [signUp](https://github.com/supabase/gotrue-js/blob/b887af5567409a189b0e700880a032c65d0d21e8/src/GoTrueClient.ts#L96) should accept `provider` as param and call [`_handleProviderSignIn`](https://github.com/supabase/gotrue-js/blob/b887af5567409a189b0e700880a032c65d0d21e8/src/GoTrueClient.ts#L431) just like [signIn](https://github.com/supabase/gotrue-js/blob/b887af5567409a189b0e700880a032c65d0d21e8/src/GoTrueClient.ts#L152) if a `provider` argument is present

**Comment by kiwicopple** [comment]
Hey i-pip, it's definitely an option, but I'd prefer to keep the codebase small (even if it's just a small addition right now, it could grow over time). Let's leave it so that users have 1 way to do it - if it becomes too confusing we can revisit 👍

**Pull request merged**
