### PR TITLE
fix: On the database view databases/table one cannot distinguish tables via UI with big screens

### LINKED ISSUE #4829: On the database view `databases/table` one cannot distinguish tables via UI with big screens
# Chore

## Underlying problem description with proposal

On my screen (it's not even that wide) the table view e.g. looks like this with a lot of tables above and below
image

From a viewpoint of Accessibility and Usability not only the icon buttons to edit are small but they are also visually not grouped to the name. On top of that there is no visual marker telling me that I am currently hovering the correct table.

My proposal:

Provide a clear contrastful hover on the table rows
+ Move the action buttons to the left such that they are grouped with the name.

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

This change fixes a bug on the table view on displays with huge resolutions.

Fixes #4829 

Bug fix, feature, docs update, ...

## What is the current behavior?

On large screens, the table view looks like this
image

From a viewpoint of Accessibility and Usability not only are the icon buttons to edit small but they are also visually not grouped to the name. On top of that there is no visual marker telling me that I am currently hovering the correct table.

#### Table rows are now hoverable

https://user-images.githubusercontent.com/39791369/172179561-fa1e2b8a-5d84-4417-8705-33a393c2a9cf.mov

#### Action items are moved to the left(Screenshot taken on a 4k display)
Screenshot 2022-06-06 at 16 49 56

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by gitstart** [comment]
Sorry about the PR title, perhaps someone with edit access can help me edit it to `fix: On the database view databases/table one cannot distinguish tables via UI with big screens`

**Comment by gitstart** [comment]
> thanks @gitstart
> 
> firstly, it's probably worth pointing out that these screens need to be overhauled really - so any small improvements will only have small gains really. Parts of the dashboard like this, we are actively looking at how to improve/move so they are much more useful.
> 
> secondly, i don't agree with moving action items to the left/middle, we have a pattern across other screens of keeping actions to the right when possible, so moving them feels like regression.
> 
> But keep in mind the first point, i don't think we are doing a great job here with UI that utilizes tables. We are probably better trying to figure out a more repeatable common table system that we can use across the entire dashboard rather than trying to make little adjustments like this.

😢

**Comment by activenode** [comment]
@MildTomato  is that personal preference or would you mind to share research e.g. from Norman Nielsen or any other good resource that backs this? Cause "regression" as you framed it isn't necessarily something that has to be considered "bad" looking at the fact that the whole point of UI/UX is testing and gathering feedback and going back _if necessary and useful_ .


I do like the proposal. From a personal experience perspective. But again: Maybe just try it and go back if users complained or it didn't work well? Cause only because it's a pattern now doesn't make it any better/worse other than staying consistent with the worse/better solution which shouldn't be the only reason.

**Comment by gitstart** [comment]
Hey @MildTomato I'm open to suggestions here. The idea of max-width doesn't sound bad at all.

**Comment by kiwicopple** [comment]
Hey team! Just getting through all the notifications from the past 2 weeks.

@gitstart thanks for the PR (and all the others that I've seen you create) 🙏 

a few pieces of feedback:

### One change per PR

it's usually better to split each change into smaller PRs, which makes them easier to merge/close. For example, I like the hoverable row highlighting! In this case if I wanted to merge it, it would be blocked by the other changes. This is particularly true in a "speculative" PR, which isn't solving an open github issue. If you're solving a few bugs, feel free to roll them up into a single PR.

### Issues/discussions are the right place for discussion

Generally once a PR is created we feel a lot of pressure to merge it, because we love having contributors. But we _do_ have to say no sometimes, because we need to keep a consistent look/feel/UX across our applications. I'm sure that if we had a discussion first, Jonny might have pushed to make this change in the [UI library](https://ui.supabase.com)

----

Personally, I don't think "Actions on the right" is that controversial - it's pretty common on admin dashboards. Everything from Linear to React Admin implements this pattern, and overall just seems like the most normal thing for a user to expect.

I don't know how to move forward on this one, except to say that we should just implement tables in the UI library and then we solve the problem everywhere

**Comment by gitstart** [comment]
@kiwicopple Thanks for the feedback, it's clarified some stuff. Let me create a PR for the hover

**Comment by gitstart** [comment]
@MildTomato I've reverted the changes that moved the icons

**Review by kiwicopple — APPROVED** [review]

**Comment by kiwicopple** [comment]
thanks @gitstart !

**Pull request merged**
