### PR TITLE
docs: row-level-security.mdx, syntax error in create table user_id field

### PR DESCRIPTION
**Pull request by mio256**
syntax error in create table user_id field

## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

docs update

## What is the current behavior?

```sql
create table tasks (
  id uuid primary key,
  user_id references auth.users,
  title text,
  done boolean
);
```

```shell
ERROR:  42601: syntax error at or near "references"
LINE 3:   user_id references auth.users,
                  ^
```

## What is the new behavior?

```shell
Success. No rows returned
```

## Additional context

I am impressed by the amazing features of Supabase. I encountered some difficulties during the RLS tutorial, so I'd like to contribute.

### CODE REVIEW

**Review by charislam — APPROVED** [review]
Thanks @mio256!

**Review by Hallidayo — APPROVED** [review]
LGTM @mio256 thank you 👍

EDIT: Sorry @charislam didn't see you had reviewed 😂

**Comment by charislam** [comment]
@Hallidayo no problem at all! I'm sure I've double-reviewed tons of your stuff, moving through notifications too fast 😄 appreciate the ping anyway because it surfaced the stalled check on this, let me try to give that a kick so this actually merges...

**Comment by mio256** [comment]
Thank you🥳

**Pull request merged**
