### PR TITLE
fix: updated font size for better a11y

### PR DESCRIPTION
**Pull request by Arindam200**
## What kind of change does this PR introduce?

This PR introduces a bug fix related to font size to enhance accessibility. It aims to address the issue #15356.

## What is the current behavior?

Currently, the font size used in the project is set to "Text-xs".

## What is the new behavior?

The font size has been updated to a custom value of "text-[13px]" based on discussions and considerations regarding accessibility. This change ensures better readability and usability for users.

### CODE REVIEW

**Comment by fsansalvadore** [comment]
Thanks @Arindam200 for contributing!

It seems Prettier is failing. Can you please try to run `npm run format` so prettier does its thing? Thanks

**Comment by Arindam200** [comment]
> Thanks @Arindam200 for contributing!
> 
> It seems Prettier is failing. Can you please try to run `npm run format` so prettier does its thing? Thanks

Ok, Sure! 

Thanks. I'm doing that.

**Comment by Arindam200** [comment]
Hey @fsansalvadore , 

I ran that command, But it's not working. 

Here's the error I got: 
image

Can you help me?

**Comment by fsansalvadore** [comment]
> Hey @fsansalvadore ,
> 
> I ran that command, But it's not working.
> 
> Here's the error I got: image
> 
> Can you help me?

Hey @Arindam200, you need to run `npm run format` in the root of the repo, so outside of the `apps` folder.

**Comment by Arindam200** [comment]
Hey @fsansalvadore ! 

Sorry to disturb you again! 

But I have tried that outside the apps directory, But it's still not working! 

Here's the ss:
image

Can you help/guide me?

**Comment by fsansalvadore** [comment]
@Arindam200 did you run `npm install` first?

**Comment by Arindam200** [comment]
> @Arindam200 did you run `npm install` first?

Yes! @fsansalvadore 

I have done that! But I got this error
image

To solve this, I have tried to downgrade the node.js version, but it's not working

image

Can you guide me?

**Comment by fsansalvadore** [comment]
@Arindam200 did you try with a node version manager?

**Comment by Arindam200** [comment]
> @Arindam200 did you try with a node version manager?

Hey! @fsansalvadore  ! 

I was not able to work on that because of my bad health! 

I'm Sorry for that! 

I'll start working on it today!

**Review by fsansalvadore — COMMENTED** [review]
@Arindam200 the `text-xs` also came with "line-height: 1rem" that we now lost. So we should integrate every text-[13px] with a `leading-4`. I'll commit as suggestions.

**Review by fsansalvadore — APPROVED** [review]
Merging this after fixing the linting issue. Thanks @Arindam200

**Comment by Arindam200** [comment]
Thanks a lot for helping me @fsansalvadore !

**Pull request merged**
