### PR TITLE
fix/docs compilation check installation failing

### PR DESCRIPTION
**Pull request by Ziinc**
Updates the following:
- dependency installation, errors out when using ssh to clone dependencies. Switch to using https.
- remove `jq` dependency installation, which is already installed in nodejs base action image.

### CODE REVIEW

**Comment by joshenlim** [comment]
ahh sorry i missed this PR - but the docs compilation check is still failing 😕 
image

**Review by joshenlim — APPROVED** [review]

**Comment by Ziinc** [comment]
@joshenlim when updating github actions, the previous action's logic will still be triggered (since it is still in repo), hence why it failed 😄

**Comment by joshenlim** [comment]
ahh okay gotcha gotcha haha thanks so much man :) 🙏

**Comment by Ziinc** [comment]
oh actually i'm wrong on that, reruns are on commit basis, not branch basis. Didn't see that @phamhieu updated the git config, thanks!

**Pull request merged**
