### PR TITLE
Allow user to apply his own PostgreSQL Conf

### PR DESCRIPTION
**Pull request by WilliamFalci**
## What kind of change does this PR introduce?

Allowing user to apply his own PostgreSQL conf

By default the logging_collector will be off, to avoid any possible disk usage for a wrong configuration of logs (like reported in previous issues the realtime write to many logs, in only 3 weeks I collected more then 100GB of logs for that) 

## What is the current behavior?

#5505

## What is the new behavior?

PostgreSQL conf now is available under `volumes/db/postgresql.conf` and copied inside the docker container to `/etc/postgresql/` allowing in this way the user to apply his configuration 

## Additional context

### CODE REVIEW

**Comment by w3b6x9** [comment]
@WilliamFalci as an alternative, what if we just overwrite specific configs like: https://github.com/supabase/supabase/pull/5481/files#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03R150

**Comment by WilliamFalci** [comment]
> @WilliamFalci as an alternative, what if we just overwrite specific configs like: https://github.com/supabase/supabase/pull/5481/files#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03R150

I was to adopt the same solution, but.. into case the user want realize a re-use log system he have to to write/replace more parameters, or if he need set in any way some configs he would do that... so I think the most simple and "elegant" way is to allow the user to set his config file into an expose folder and then grab it

**Comment by kiwicopple** [comment]
I'm worried about the maintainability of this approach. Each time Postgres add/change a config param we will also need to update the file. Perhaps we can just document this approach here?
https://supabase.com/docs/guides/hosting/docker#configuration

I think it's a great way to do it, just want to make sure we aren't causing a maintenance burden

**Comment by WilliamFalci** [comment]
> I'm worried about the maintainability of this approach. Each time Postgres add/change a config param we will also need to update the file. Perhaps we can just document this approach here? https://supabase.com/docs/guides/hosting/docker#configuration
> 
> I think it's a great way to do it, just want to make sure we aren't causing a maintenance burden

I understand your point-of-view, but, with the copy of the file or just by command into yml every release by postgress will cause a check anyway.

So in anyway the most simple way is:

at the release of a new Postgres -> just copy and paste the file conf under `volumes/db/` 

then will be the end-user to check is own configuration. Example:

- I clone the repository (with the default Postgres conf under `volumes/db`)
- Postgres release a new versione with few changes on variables into Postgres conf file, so you copy and paste the last version and then apply the change on the repository
- The end-user will fetch and pull from this repository
- The end-user will be noticed on file conflict between his old file conf then the new one
- The end-user decide to accept the incomig applying what he needed in perispective of his old config


Is most user-friendly then go to touch the docker yml

**Comment by alaister** [comment]
Hey @WilliamFalci,

I'm sorry about the massive delays here.

It looks like this isn't getting merged, so I'm going to go ahead and close this.
For now, you can use @w3b6x9's workaround, and if you think this is still an issue that others would find helpful to be fixed, please open a [new discussion](https://github.com/orgs/supabase/discussions/new/choose)!

Thanks for your work 🙏🏻

**Pull request closed without merging**
