### PR TITLE
fix: studio users listbox

### LINKED ISSUE #12507: Permissions dropdown css bug
image

on org permissions

using Firefox 109.0.1 on Mac 13.2.1

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase Studio > Settings > Users

## What is the current behavior?

The users list box items crop

## What is the new behavior?

Fixed width added:

Screenshot 2023-02-19 at 21 28 07

## Additional context

Closes #12507

### CODE REVIEW

**Review by Isaiah-Hamilton — APPROVED** [review]

**Comment by MildTomato** [comment]
can we not use the `size` prop?

**Comment by Hallidayo** [comment]
@MildTomato - I tried using the `size` prop but this just changed the font size of the ToolTip. I also tried `optionsWidth' but no effect.

**Comment by MildTomato** [comment]
@Hallidayo i think this is meant to be a Dropdown. pinged out frontend team about it.
Probably not worth fixing just for this though

**Review by MildTomato — APPROVED** [review]

**Comment by Timon-star-max** [comment]
I tried using the size prop but this just changed the font size of the ToolTip. I also tried `optionsWidth' but had no effect.

**Pull request merged**
