### PR TITLE
chore: export IconBaseProps interface, update populate-icons script to write props in component def

### PR DESCRIPTION
**Pull request by brandongregoryscott**
## What kind of change does this PR introduce?

This PR updates the `populate-icons.js` script to remove extra whitespace at the beginning of each line (from the indented template string) as well as specifying the `IconBaseProps` interface as props - this should improve the developer experience when working with the generated icon components!

## What is the current behavior?

Each icon is generated with the props typed as `any`, which can lead to erroneous behavior. 

## What is the new behavior?

The props object for each generated icon is now properly typed to a composition of what the `IconBase` component expects, minus the `icon` prop, which is being set internally.

## Additional context

Aside from the generated icon changes, the `Loading` component (https://github.com/supabase/supabase/blob/master/packages/ui/src/components/Loading/Loading.tsx#L20-L25) was updated to join `spinnerClasses` to a `string`. It wasn't _harming_ anything by being a string array as it is now, but I don't think that's the intention based on `IconBase`.

There are a few additional, optional props that were added to `IconBaseProps` based on existing usages. I can't say for sure whether these are actually being passed correctly to the underlying element(s) being rendered internally, but this is why we should be defining types! 😛

### CODE REVIEW

**Comment by MildTomato** [comment]
@brandongregoryscott ok to fix the errors?
Probably get the same thing running `npm run build` locally

Screenshot 2023-02-20 at 5 16 33 PM

**Comment by brandongregoryscott** [comment]
@MildTomato I think that's from an old build before I added some of the missing props I found to `IconBaseProps`:

https://github.com/supabase/supabase/pull/12454/files#diff-8a37fa2a6b0bf41b7c960b98b82d924416d5469c02562c10db016c794981abb5R18-R22

`npm run build` is running successfully locally - is there a way to re-trigger the deployments?

```
 Tasks:    3 successful, 3 total
Cached:    2 cached, 3 total
  Time:    1m25.394s 
```

I just merged in upstream changes so maybe that will trigger new builds.

**Comment by MildTomato** [comment]
retriggering 😄

**Comment by MildTomato** [comment]
just waiting on site checks again. i'll merge if they all pass

**Review by MildTomato — APPROVED** [review]

**Pull request merged**
