### PR TITLE
Chore/upgrade sb

### PR DESCRIPTION
**Pull request by MildTomato**
## What kind of change does this PR introduce?

- upgrade to storybook 8 RC

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by ivasilov** [comment]
there's few warnings
```WARN The following packages are incompatible with Storybook 8.0.0-rc.1 as they depend on different major versions of Storybook packages:
WARN - @storybook/addon-styling-webpack@0.0.6
WARN 
WARN 
WARN Please consider updating your packages or contacting the maintainers for compatibility details.
WARN For more on Storybook 8 compatibility, see the linked GitHub issue:
WARN https://github.com/storybookjs/storybook/issues/26031
WARN The "@storybook/addon-mdx-gfm" addon is meant as a migration assistant for Storybook 8.0; and will likely be removed in a future version.
WARN It's recommended you read this document:
WARN https://storybook.js.org/docs/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm
WARN 
WARN Once you've made the necessary changes, you can remove the addon from your package.json and storybook config.```

@MildTomato Is there a need (a specific feature) you need from v8 to bump while it's in `beta`? I would wait it out TBH.

**Comment by MildTomato** [comment]
> @MildTomato Is there a need (a specific feature) you need from v8 to bump while it's in beta? I would wait it out TBH.

we have a ton of subcomponents, and v8 has support for it

**Comment by MildTomato** [comment]
@ivasilov how much of an issue is this? Would quite like to work on storybook following v8 docs from the beginning, so I don't end up using < v7 stuff and end up going through upgrade pain later.

**Review by alaister — APPROVED** [review]
LGTM! Since storybook isn't mission critical, I think using v8 RC is fine :)

**Comment by MildTomato** [comment]
@ivasilov @alaister leave you two to debate about it 🤣

**Pull request merged**
