### PR TITLE
Enhanced useHash.ts hook ^^

### PR DESCRIPTION
**Pull request by TheEinshine**
Added dependencies,
Auto URL parsing rather than manually splitting it,
At last cleanup in useEffect!

### CODE REVIEW

**Comment by charislam** [comment]
Thanks @TheEinshine! Could you run `npm run format` so it'll pass our formatting check?

**Comment by TheEinshine** [comment]
> Thanks @TheEinshine! Could you run `npm run format` so it'll pass our formatting check?

Ran Prettier, hope that's what we are using on lint check, lemme know if it's something else

**Comment by TheEinshine** [comment]
@charislam let's check if it's passing tests? :)

**Comment by charislam** [comment]
@TheEinshine, thanks for the nudge! Just started tests again 🤞🏼

**Comment by TheEinshine** [comment]
@charislam All checks passed, well we back at it again :D let's goooo!

**Review by charislam — APPROVED** [review]

**Comment by charislam** [comment]
Awesome, thanks!

**Comment by TheEinshine** [comment]
> Awesome, thanks!

hahaha thanks, it took like a week
i will go on PR rampage soo, after work soften up a bit, see you around

**Pull request merged**
