### PR TITLE
fix/studio/logs: added metadata overflow, copy buttons

### PR DESCRIPTION
**Pull request by Ziinc**
image

cc @chasers 

copy buttons have been requested by users through feedback form.

### CODE REVIEW

**Comment by kiwicopple** [comment]
possible to make these scrollbars dark when in dark mode?

**Comment by kiwicopple** [comment]
Also, perhaps we can use a similar approach to github's code-copy button (which appears only when you hover over the code block)?

image

**Comment by joshenlim** [comment]
yeah we have a component that has the copy button within itself, e.g:
image

I can take a look into the styling of these

**Comment by Ziinc** [comment]
@joshenlim should be able to use the new InputTextArea component https://github.com/supabase/ui/pull/304

**Comment by Ziinc** [comment]
could use them for both the metadata + event message

**Comment by joshenlim** [comment]
Updated as such

**Comment by joshenlim** [comment]
Updated as such

image

**Review by joshenlim — APPROVED** [review]

**Comment by Ziinc** [comment]
@joshenlim the event message shouldn't be truncated, as the data grid already truncates it, so users wouldn't have a way to see the full event message at all

**Pull request merged**
