### PR TITLE
Find and replace `.io` to `.com` in docs.

### PR DESCRIPTION
**Pull request by leerob**
Was reading the docs and noticed a few instances of `.io` still, pre-redirect to `.com`, so this PR updates them all.

CleanShot 2021-12-12 at 19 14 01@2x

You might want to also update `.io` to `.com` in the repo description 😄 
CleanShot 2021-12-12 at 19 14 01@2x

### CODE REVIEW

**Comment by leerob** [comment]
You might consider turning off [Git Fork Protection](https://vercel.com/changelog/git-fork-protection-can-now-be-disabled) for the docs project so Preview URLs will generate for all contributors.

**Comment by MildTomato** [comment]
@leerob we might have caused some confusion here, the dashboard is still on app.supabase.io, we haven't migrated it to .com yet.

**Comment by leerob** [comment]
My bad! This can just sit for awhile 😄

**Comment by MildTomato** [comment]
@leerob finally, we updated all this. had to do it in [another PR though](https://github.com/supabase/supabase/pull/7048)

thanks for this though :fire:

**Pull request closed without merging**
