### PR TITLE
docs: correct server-side-auth template for change of email

### LINKED ISSUE #18305: Change Email Address Template in Email Auth with PKCE flow for SSR needs to be corrected
There is nice documentation on how to configure a Supabase project to handle email authentication in a server-side rendered (SSR) application. But, I think the example template for the `Change Email Address` case is incorrect [Link](https://github.com/supabase/supabase/blob/02dd1b643a94f549f1014bb18bd2db8b643268db/apps/docs/pages/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr.mdx#L235C12-L235C12)

Instead of 
```
<h2>Confirm Change of Email</h2>

<p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
<p><a href="{{ .ConfirmationURL }}">Change Email</a></p>
```

It should follow the pattern of the other templates and be 
```
<h2>Confirm Change of Email</h2>

<p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
<p><a href="{{ .SiteURL }}/api/store/auth/confirm?token_hash={{ .TokenHash }}&type=email_change">Change Email</a></p>
```

This should be an easy change. I am happy to make a PR if you want.

### PR DESCRIPTION
**Pull request by ciyer**
## What kind of change does this PR introduce?

Docs update to correct the "Confirm Change of Email" template for server-side auth.

## What is the current behavior?

The current template is incorrect for this use case.

## What is the new behavior?

Change the template to follow the same pattern used by the other server-side auth templates

## Additional context

Second try -- this time with `prettier` run on changed file.

Fix #18305
@J0

### CODE REVIEW

**Comment by ciyer** [comment]
@J0 Just wanted to follow-up -- would you be able to take a look at the PR? I have run the code formatter and, at least locally, the change passes. (I had to create a new PR because I pushed a change to the old one the triggered some automation to close the PR, sorry about that!) Thanks!

**Review by J0 — APPROVED** [review]

**Review by silentworks — CHANGES_REQUESTED** [review]
Please follow the url endpoint the other templates have in order to not confuse users.

**Comment by ciyer** [comment]
> Please follow the url endpoint the other templates have in order to not confuse users.

Oops! Good catch -- my own URL scheme was leaked into here. I have changed the URL structure to match the others.

**Comment by J0** [comment]
Thanks for the catch @silentworks!

**Comment by ciyer** [comment]
@J0 @silentworks -- following up here. I think I have addressed all the issues that were raised. Let me know if there are any further changes you want here.

**Review by silentworks — APPROVED** [review]
LGTM

**Comment by ciyer** [comment]
@J0 PR has been approved -- is there anything remaining that I need to do so that it can be merged?

**Comment by J0** [comment]
All good, thanks!

**Pull request merged**
