### PR TITLE
feat: add ability to create custom enumerated types from UI

### LINKED ISSUE #9661: Add Enum Support To Table Editor
# Feature request

Supabase has supported Postgres ENUM types for two years but the web UI (Table Editor) still does not yet appear to support creating columns with ENUM type. In order to do this, it looks like I'll need to modify the table manually after creating it. Given the prevalence of ENUM columns in table design, it would seem desirable to have support for creating ENUM columns in the web UI.

## Describe the solution you'd like

In the table creation wizard, the "Type" pulldown for a column should include an "Enum" option. A popup could then collect a list of allowable values from the user (or in a simpler first implementation, the user could be asked to comma separate the list of possible values in a TEXTAREA).

## Describe alternatives you've considered

The UI could expose a "..." next to types that require configuration, not just ENUM but also possibly VARCHAR. (It's not clear how to set character limits for a VARCHAR in the UI today).

## Additional context

ENUMs have been supported in Postgres for well over a decade and are not considered novel. Their use is widespread in database design; it would be very nice to have them supported as a first class citizen in the Table Editor UI.

### PR DESCRIPTION
**Pull request by diboune**
## What kind of change does this PR introduce?

feature

## What is the current behavior?

You can't create custom enumerated types unless from the SQL Editor.

Please link any relevant issues here.

fixes #9661 

## What is the new behavior?

Now you can create custom enumerated types from the UI

Screenshot from 2022-11-05 15-27-40
Screenshot from 2022-11-05 15-27-15

## Additional context

I tried to make the UX as dynamic as it can be so that in the future we can add other custom types, like character limited varchar, etc...

### CODE REVIEW

**Comment by MildTomato** [comment]
hey @diboune 

This looks like an awesome start. The team have been meaning to work on something like this for a long time.
Is it okay if we jump in this branch and make some changes?

We probably need to change some of the sidebar UI for creating a new type.

**Comment by diboune** [comment]
Of course! And sorry for not maintaining it

**Comment by darkomking** [comment]
+1 - Looking forward to this feature

**Comment by ivasilov** [comment]
@diboune thank you for your contribution. We've used some of your approach in https://github.com/supabase/supabase/pull/17953 which is now used in the dashboard.

**Pull request closed without merging**
