### PR TITLE
Beta page light mode

### LINKED ISSUE #4505: Beta page theme
# Bug report

## Describe the bug

Not sure if this was intentional or not but the beta page when switched to the light theme, the hero and the section below doesn't change to light theme.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com/beta](https://supabase.com/beta)
2. Click on `Theme Toggle in footer`
3. Scroll up to `hero`

## Expected behavior

To be in light theme

## Screenshots

https://user-images.githubusercontent.com/70828596/146305318-3975d11b-ff77-4d1f-96c8-712c98f80072.mov

## System information

- OS: macOS
- Browser FireFox
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

again I don't know if this was intentional or not.

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Fix beta page light mode.

## What is the current behavior?

Fix #4505 

## What is the new behavior?

light mode for Hero and Introduction.

## Additional context

I need an updated image for the light node.
Screen Shot 2021-12-16 at 10 54 14 PM

### CODE REVIEW

**Comment by kiwicopple** [comment]
> I need an updated image for the light node.

Yeah, it would be nice if the lines are a slightly darker grey than the bg. 

Is this something you can do or do you need help with it @Isaiah-Hamilton ? We could ask someone on Discord?

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple I can try but I'm not very good, so I think we should ask someone on Discord to help out.

**Comment by MildTomato** [comment]
Assigning myself as I can probably fix the image

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple @MildTomato Figured out how to use photoshop, and was able to come up with this. Thoughts? could always be darker or lighter.
Screen Shot 2022-02-22 at 11 41 15 PM

**Comment by MildTomato** [comment]
yea, looks alright 👍

**Review by MildTomato — APPROVED** [review]

**Pull request merged**
