### PR TITLE
misc(about): prevent snippets from creating individual pages

### PR DESCRIPTION
**Pull request by yangshun**
## What kind of change does this PR introduce?

When site is upgraded to docusaurus@2.0.0-beta (PR incoming), about.supabase.com will benefit from the following:

- Removes snipper pages from being built as individual pages
- Slight perf improvements (build speed) due to fewer pages being built

## What is the current behavior?

- All md/x files in a Docusaurus docs directory will have a page generated. As a result, the MDX files within `about/docs/careers/snippets` all have a page generated. E.g.
  - https://about.supabase.com/careers/snippets/process
  - https://about.supabase.com/careers/snippets/hiring-freeze (yes even this even though it's not being used on any other pages)

## What is the new behavior?

It's unlikely that these snippets were meant to have their own pages. In docusaurus@2.0.0-beta, directories can be excluded if they start with underscore. Hence I'm making a futureproof change by renaming the snippets folder to be prefixed with an underscore.

### CODE REVIEW

**Review by kiwicopple — APPROVED** [review]

**Comment by yangshun** [comment]
@kiwicopple will there be someone else doing the final merge?

**Comment by Isaiah-Hamilton** [comment]
sorry for the delay @yangshun I will merge, but there seems to be some conflicting files.

**Comment by yangshun** [comment]
@Isaiah-Hamilton I've resolved the merge conflicts. Thank you!

**Review by Isaiah-Hamilton — APPROVED** [review]
lgmt

**Pull request merged**
