### PR TITLE
Use restart-services endpoint for restart server button in project se…

### PR DESCRIPTION
**Pull request by joshenlim**
cc @darora - just to make sure i'm doing it right haha

### CODE REVIEW

**Comment by saltcod** [comment]
@joshenlim reviewed / looks good / works!   I'll leave it to Div to mark it as approved though?

**Comment by joshenlim** [comment]
needs changes - need to keep old endpoint
have 2 actions instead -> one to restart project, the other restarts db only

**Comment by joshenlim** [comment]
PR now ready, updated to this
image

@MildTomato need your opinion here though - you reckon this is good to go or should we include some description text about what to choose from? imo even i wouldn't know which to click if i need to restart something (or i'd come here with the intention to just restart everything)

**Comment by MildTomato** [comment]
@joshenlim we should add a description to each choice I think.
Project being all of the supabase services, and database just being the postgres database

we have similar descriptions in the member option dropdown:
Screenshot 2022-07-06 at 6 20 26 PM
.

**Comment by joshenlim** [comment]
Ah okay gotcha yeap

Just thinking about the phrasing here:

Restart project
- Restarts all supabase services of the project

Restart database
- Restarts only the postgres database

This okay? @MildTomato

**Comment by joshenlim** [comment]
updated UI as such:
image

**Review by alaister — APPROVED** [review]
lgtm!

**Pull request merged**
