### PR TITLE
Chore: Convert all independent PATCH and DELETE requests to RQ mutations

### PR DESCRIPTION
**Pull request by joshenlim**
Looks into converting all independent PATCH and DELETE requests on the dashboard to RQ mutations (Except StorageExplorerStore)

### CODE REVIEW

**Comment by alaister** [comment]
Thanks for doing this @joshenlim! Looking good!

One thing I noticed when updating the profile, the buttons seem to disappear too soon:
https://github.com/supabase/supabase/assets/10985857/54fcfbd5-10da-4975-abc9-d56e0be68579

**Comment by joshenlim** [comment]
Ahh okay - cause those are using SchemaFormPanel which expects an async method with the onSubmit prop - updated!

**Comment by joshenlim** [comment]
just FYI i decided to convert all independent delete requests as well since it was just 2 of them

**Review by alaister — APPROVED** [review]
LGTM!

**Pull request merged**
