### PR TITLE
feat: auth docs logo

### LINKED ISSUE #12294: Update Auth docs page with updated providers links
# Chore

## Describe the chore

The [main auth docs page](http://supabase.com/docs/guides/auth/overview) is using an old style of buttons.
See below:
Screenshot 2023-02-10 at 12 21 30 AM

Update them to use the same style as seen on social auth page and phone auth page
http://supabase.com/docs/guides/auth/social-login
http://supabase.com/docs/guides/auth/phone-login
Screenshot 2023-02-10 at 12 23 10 AM
Screenshot 2023-02-10 at 12 23 19 AM

this is for the docs site, located in `apps/docs`, a nextjs site.

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase Docs - [Auth Providers](https://supabase.com/docs/guides/auth/overview#providers)

## What is the current behavior?

The auth cards currently show no logos.

## What is the new behavior?

Logos have been added to the cards:

Screenshot 2023-02-09 at 18 30 45

## Additional context

Closes #12294

@MildTomato - I feel like more can be done e.g. styling with the other sections of the card, what do you think?

### CODE REVIEW

**Comment by MildTomato** [comment]
hey @Hallidayo, 

you can remove all the boxes and "platform", and "self hosted" parts, we don't really need these anymore I don't think.
It can just be exactly the same as what is in the Social Providers page. WDYT?

**Comment by Hallidayo** [comment]
Hi @MildTomato 

Yeah looks so much cleaner now:

Screenshot 2023-02-09 at 20 45 02

**Comment by MildTomato** [comment]
@Hallidayo so good. Should we split them up, so the social providers are separate from the phone provider. Be a bit more obvious then they are for different use cases.

Other than that, think we should merge it in 🚀

**Comment by Hallidayo** [comment]
@MildTomato - Yeah looks better split up:

Screenshot 2023-02-10 at 08 55 05

Should the headings be Auth or Provider?

**Review by MildTomato — APPROVED** [review]

**Comment by MildTomato** [comment]
great stuff

**Comment by MildTomato** [comment]
merging when checks are done

**Review by saltcod — APPROVED** [review]

**Comment by saltcod** [comment]
Beaut @Hallidayo !

**Pull request merged**
