### PR TITLE
Chore: Add links to documentation to the  Auth Providers page

### PR DESCRIPTION
**Pull request by monicakh**
## What kind of change does this PR introduce?

- Added a "Learn more" button with links to setup guides for each auth provider.

### CODE REVIEW

**Comment by joshenlim** [comment]
hmm this button is oddly placed - i can take a look at this tomorrow to see where might be a better position
image

**Review by charislam — APPROVED** [review]
Approving to unblock, with one minor nit about the layout

Would it look less obtrusive if we put the button in the header like so?
Screenshot 2024-09-12 at 11 33 51

(just a suggestion)

**Comment by joshenlim** [comment]
i think lets do it like this:
image

am thinking you'd typically want docs for a provider only when you're planning to edit it, so putting it within the Collapsible will be better. That and it doesn't distract the "Enabled and "Disabled" status badge too - it looks a bit too cluttered otherwise
image

**Review by joshenlim — APPROVED** [review]
LGTM - tested on staging preview that each documentation button works

**Pull request merged**
