### PR TITLE
feat: Additional Libraries

### PR DESCRIPTION
**Pull request by HarryET**
## What kind of change does this PR introduce?
Adds additional libraries from Supabase Community which have a `supabase-[language]` package

## What is the current behavior?
Missing SDKs

## What is the new behavior?
Added SDKs

## Additional context
https://github.com/supabase-community#client-libraries

### CODE REVIEW

**Comment by HarryET** [comment]
TODO: Add images to the /img/ folder

**Review by MildTomato — COMMENTED** [review]
we may need to reorder this in order of most used.
Although I think it generally goes JS, Python, Flutter, .. then everything else currently.
Just so we are surfacing the most used right now at top.

WDYT?

**Comment by HarryET** [comment]
Sure! I was just keeping up with the alphabetical order

**Comment by MildTomato** [comment]
@HarryET you ok to make changes to this so it's in order of popularity ?

**Comment by HarryET** [comment]
What order should that be? I've not looked at the ecosystem in a little while?

**Review by kiwicopple — COMMENTED** [review]
thanks @HarryET - I think we're going to wait until we have some more official support for these

**Pull request closed without merging**
