### PR TITLE
Typo fix tagalog translate

### PR DESCRIPTION
**Pull request by nicklm0**
## What kind of change does this PR introduce?

Making a correction on README tagalog translation

### CODE REVIEW

**Comment by charislam** [comment]
@nickaldwin, just checking if you want to keep this PR or your other translation one?

**Comment by nickaldwin** [comment]
@charislam, good morning. I hope you're having a good evening. I would like to keep the current PR #19137

**Comment by nickaldwin** [comment]
Hi @charislam Good Morning & Good Evening i want close the PR #19076

**Comment by k-ison** [comment]
Hey @nickaldwin ~ Sorry for the delay here. We're still in the process of reviewing the translations and may take more time. I'd suggest as well that we keep some tech jargons in English that we Filipinos don't usually have substitute Tagalog words for. 

i.e. [Supabase](https://supabase.com) Ay isang open-source na alternatibo sa Firebase.

Instead of [Supabase](https://supabase.com) Ay isang alternatibong bukas na mapagkukunan ng Firebase. (since "Bukas na mapagkukunan" sounds more like literal translation of words)

**Comment by nickaldwin** [comment]
Hi @k-ison i will fix the issue thank you so much

**Comment by nickaldwin** [comment]
Hi @k-ison good morning and good evening hope you doing great an merry christmas can i make it taglish?

**Pull request closed without merging**
