### PR TITLE
[WIP] Delete old reference docs files

### PR DESCRIPTION
**Pull request by dannykng**
## What kind of change does this PR introduce?

- Delete `apps/docs/docs/reference` directory (new reference docs directory is `apps/docs/docs/ref`)
- Delete `apps/docs/pages/reference/index.mdx` (old reference docs landing page)

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by kiwicopple** [comment]
cc @dannykng is this one still valid?

**Comment by dannykng** [comment]
> cc dannykng is this one still valid?

Yep, still need to delete these files. @saltcod can you see what's causing the docs build to fail? I'm not seeing anything locally. 🙏🏼

**Comment by kiwicopple** [comment]
ran a redeploy, but here is the original error:

**Comment by saltcod** [comment]
had a look and seems we still need these files. They get generated by the `gen:` scripts in package.json.

**Pull request closed without merging**
