### PR TITLE
Use downloadFile method in preview pane download button

### PR DESCRIPTION
**Pull request by joshenlim**

### CODE REVIEW

**Review by alaister — APPROVED** [review]
LGTM!

**Comment by MildTomato** [comment]
Studio Build failing

**Comment by MildTomato** [comment]
rerunning

**Comment by MildTomato** [comment]
Screenshot 2023-02-26 at 6 06 46 PM

why do we even have this? isn't this covered by the vercel build ?

**Comment by joshenlim** [comment]
> why do we even have this? isn't this covered by the vercel build ?

yeah tbh we can remove this imo, and make the vercel build a required action

**Pull request merged**
