### PR TITLE
fix: logs custom error messages

### PR DESCRIPTION
**Pull request by Ziinc**
Adds custom error messages to logs explorer and previewers.

Allows us to handle specific errors and prompt users to self-serve & fix them.

Screenshot 2022-08-03 at 3 07 49 AM

punctuation has been fixed.

### CODE REVIEW

**Comment by saltcod** [comment]
@Ziinc looks great! 

I'm wondering if these new warnings should replace the "No results :(" component in these instances. Feels like the messages are competing:

 
CleanShot 2022-08-09 at 08 28 35@2x
CleanShot 2022-08-09 at 08 28 16@2x

**Review by saltcod — APPROVED** [review]

**Comment by Ziinc** [comment]
@saltcod how did you get the second pic? It is missing a line in the error message, and the "No results" message actually gets hidden when there is an error.

**Comment by Ziinc** [comment]
@saltcod I'm open to merging the two types of alerts, I personally prefer the design/layout of the no results message. I'll defer to the design team to make the choice. The drawback of  the no results message is that there needs to be an icon/graphic for the error alert message.

**Comment by Ziinc** [comment]
internal ticket [created](https://www.notion.so/supabase/Logs-Merge-No-Results-Alert-with-Error-Alerts-531c4b7aca87499b886d34c63aa79e65)

**Pull request merged**
