### PR TITLE
Add free resource to the documentation

### PR DESCRIPTION
**Pull request by gdangelo**
## What kind of change does this PR introduce?

Documentation updates. Adding a new resource to the documentation website. It is a free online course created by me and teaches about building a full-stack app with Next.js, Supabase (db + storage), and Prisma.

## What is the current behavior?

N/A

## What is the new behavior?

N/A

## Additional context

N/A

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @gdangelo thanks for creating such a great course! Perhaps you can add it as a bullet point in the "Guides" section, rather than the "Featured" section (which we plan to keep for embedded videos)

Alternatively, I'd be happy to create a new section "Courses" and add it as a bullet point there

**Comment by gdangelo** [comment]
Hey @kiwicopple! Thanks for your feedback. At least, I've tried to get my course featured 😉

I agree with creating a new section named "Courses" and adding it here. How should we proceed? Should I resubmit a PR? Or could you push it yourself?

**Comment by kiwicopple** [comment]
Perhaps you can submit a new, or edit this one? Thanks!

**Comment by gdangelo** [comment]
> Perhaps you can submit a new, or edit this one? Thanks!

✅ Done!

**Review by Isaiah-Hamilton — APPROVED** [review]

**Pull request merged**
