### PR TITLE
Fixed one typo in README.bn.md

### PR DESCRIPTION
**Pull request by SoumyadeepOSD**
## What kind of change does this PR introduce?

It fixes the typo error

## What is the current behavior?

In Current state last line contains `রিপুর`

image

## What is the new behavior?

It has changed with `রেপোর`

image

## Additional context

Check issue #15319

### CODE REVIEW

**Review by gregnr — APPROVED** [review]
Thanks @SoumyadeepOSD!

**Comment by SoumyadeepOSD** [comment]
Hey @gregnr , My PR is not merged duo to Authorization problem in vercel, can you tell me what to do?

**Comment by gregnr** [comment]
We had some temporary issues with our CI build pipelines. All resolved now. Thanks again for contributing @SoumyadeepOSD!

**Comment by SoumyadeepOSD** [comment]
Thanks @gregnr for merging my PR!

**Pull request merged**
