### PR TITLE
docs: Fix broken SITE_URL link

### LINKED ISSUE #21897: [DOCS] SITE_URL link is broken
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/auth-signup

and more...

## Describe the problem

the link (https://supabase.com/docs/reference/auth/config#site_url) set to SITE_URL is broken and redirects to 404.

## Describe the improvement

SITE_URL redirects to a correct page or remove the link set to SITE_URL

### PR DESCRIPTION
**Pull request by hawkcookie**
## What kind of change does this PR introduce?

docs update
close #21897

## What is the current behavior?

When we click on the SITE_URL link in the document, we are redirected to a 404 page.

## What is the new behavior?

When we click on the SITE_URL link in the document, we are redirected to a correct page.

### CODE REVIEW

**Comment by hawkcookie** [comment]
I found SITE_URL link broken. Which page should this link currently redirect to? Since SITE_URL can be set within the project, should it be the same link destination set in allow_list? Or should I remove the link in the SITE_URL? 
I would like some advice.

**Comment by encima** [comment]
Thanks for opening this, I missed it when reading your issue, sorry! I have opened an additional PR that fixes this link and others. If you do not mind, I would close this in favour? If you would like to fix the additional pages, then I can close mine in favour of yours.

Let me know! 🙏

**Comment by hawkcookie** [comment]
@encima 

Thank you for letting me know! I'd like to commit it, so I'll fix it.

**Comment by hawkcookie** [comment]
@encima 
I fixed them just now!

**Review by charislam — APPROVED** [review]

**Pull request merged**
