### PR TITLE
adds dynamic cursor to Realtime product card

### PR DESCRIPTION
**Pull request by Filsommer**
## What kind of change does this PR introduce?

Adds automatically moving cursor to the Realtime product card. This small tweak improves the "realtime" feel :)

## What is the current behavior?

Hovering the Realtime product card only moves the cursors once.

## What is the new behavior?

While hovering the Realtime product card, one of the cursors keeps moving every 1.5 seconds.

## Additional context

See demo: https://giphy.com/gifs/8Z075ENwT3PKxABamU

### CODE REVIEW

**Comment by fsansalvadore** [comment]
Hah, interesting @Filsommer!

Maybe it can have an even shorter delay?
1.5s seems slow and not very "realistic". Something like 0.2s?

**Comment by Filsommer** [comment]
@fsansalvadore tried with 0.5s (and also with 0.2s) but it looks like the other user is on drugs 😅
See: https://giphy.com/gifs/C8Dn22JxWWFvWrE3iY

Any other ideas?

**Comment by fsansalvadore** [comment]
Ahah, ok @Filsommer. 🤣
Then we can meet some half way at 0.8-0.9s or something?

**Comment by Filsommer** [comment]
@fsansalvadore done! 900ms looks really good. Also added (a more subtle) movement to the second cursor

**Comment by Filsommer** [comment]
@fsansalvadore any news? :)
If not needed, I can close this PR to avoid too many open ones

**Comment by alaister** [comment]
Hey,

Thanks for your PR!

Unfortunately, this has got a little stale, so I'm going to go ahead and close it. Please feel free to fix any merge conflicts and open up a new PR if the changes are still relevant.

Thanks again!

**Pull request closed without merging**
