### PR TITLE
fix: safari icon svg | fixes #649

### LINKED ISSUE #649: Favicon not appearing correctly on Safari
# Bug report

## Describe the bug

image

## System information

- OS: mac
- Browser safari Version 14.0.1 (15610.2.11.51.10, 15610)

### PR DESCRIPTION
**Pull request by MildTomato**
replaced SVG and updated safari pin color

### CODE REVIEW

**Comment by MildTomato** [comment]
check if this works on the vercel preview before merging

**Comment by kiwicopple** [comment]
image


:(

**Comment by MildTomato** [comment]
😿

**Comment by kiwicopple** [comment]
@MildTomato - it may have actually worked, but because of the monorepo setup it's still pointing to the old site? I say this because I just tried to deploy some new docs and couldn't see the updates in the preview deploy

**Pull request closed without merging**
