### PR TITLE
Add dart to authentication docs

### LINKED ISSUE #6157: Add dart to authentication docs
# Improve documentation

## Describe the problem

Currently, the authentication docs only have javascript. It would be cool if we add dart just like [Login With Email](https://supabase.com/docs/guides/auth/auth-email) and [Login With Magic Link](https://supabase.com/docs/guides/auth/auth-magic-link).

## Describe the improvement

Add dart into the docs just like [Login With Email](https://supabase.com/docs/guides/auth/auth-email) and [Login With Magic Link](https://supabase.com/docs/guides/auth/auth-magic-link).

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

docs update
Fixes #6157

## What is the current behavior?

[CURRENT_IMPLEMENTATION_ON_DOCS](https://supabase.com/docs/guides/auth/auth-apple)

Plz look at the Login with apple,azure etc previously the dart code was not there. Implemented as of Login with email and magic_link now

## What is the new behavior?

[DEMO_LOOM_VIDEO](https://www.loom.com/share/cf4fb488385f4941bdb841bf8646d56e)

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by kiwicopple** [comment]
cc @dshukertjr - perhaps you want to use some of this PR?

**Comment by dshukertjr** [comment]
This is beautiful @gitstart!

Thanks @kiwicopple for the heads up. We should eventually edit the reference docs to look like this too huh?

**Comment by gitstart** [comment]
@kiwicopple @dshukertjr Any update on this?

**Comment by dshukertjr** [comment]
@kiwicopple @Isaiah-Hamilton  Did the preview always have issues?
https://zones-docs-1ashwzr8w-supabase.vercel.app/

**Pull request closed without merging**
