### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by periakteon**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Typo fix

## What is the current behavior?

Same.

## What is the new behavior?

Nothing

### CODE REVIEW

**Review by fsansalvadore — APPROVED** [review]
Thanks @periakteon

**Comment by fsansalvadore** [comment]
I'm afraid Prettier is failing. 
@periakteon could you please run `npm run format apps/www/_blog/2022-08-18-supabase-realtime-multiplayer-general-availability.mdx` locally to fix it?

It should format it like this:
Screenshot 2024-08-23 at 15 33 25

**Comment by periakteon** [comment]
> I'm afraid Prettier is failing. @periakteon could you please run `npm run format apps/www/_blog/2022-08-18-supabase-realtime-multiplayer-general-availability.mdx` locally to fix it?
> 
> It should format it like this: Screenshot 2024-08-23 at 15 33 25

I ran the command you gave locally and pushed it. Is there a problem now?

**Review by fsansalvadore — APPROVED** [review]
Now it's as pretty as Prettier wants it ✨

**Pull request merged**
