### PR TITLE
Fix/doc search

### LINKED ISSUE #6007: Search broken in docs
# Bug report

## Describe the bug

Looks like searching documentation is broken!

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://supabase.com/docs/reference/javascript/auth-session
2. Click on the Search box
3. Type anything in the search box

## Expected behavior
Results

## Actual behavior
The UI says I'm offline, the console is full of net::ERR_NAME_NOT_RESOLVED

## Screenshots
Screen Shot 2022-03-22 at 11 04 08 AM

## System information
Mac, Chrome

### PR DESCRIPTION
**Pull request by burmecia**
## What kind of change does this PR introduce?

This PR is to replace Algolia with Typesense for doc search engine. Fix #6007

## What is the current behavior?

The doc search currently uses Algolia free tier and it can easily exceed quota and make the doc search broken.

## What is the new behavior?

We built our own doc search engine using Typesense and use it to replace Algolia.

## Additional context

N/A

### CODE REVIEW

**Review by Isaiah-Hamilton — APPROVED** [review]
lgtm

**Comment by MildTomato** [comment]
Screenshot 2022-05-09 at 3 21 18 PM@burmecia rc=

@bo @Isaiah-Hamilton

**Comment by MildTomato** [comment]
Screenshot 2022-05-09 at 3 22 13 PM

@bo @Isaiah-Hamilton looks broken

**Comment by burmecia** [comment]
That's because the doc search backend is on bare IP address and port 80, browser forbidden http access in a https url.

**Pull request merged**
