### PR TITLE
docs: fix the redirectUrl for preview deployments in vercel

### PR DESCRIPTION
**Pull request by sarthakgupta072**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Documentation update

## What is the current behavior?

The url `https://*-username.vercel.app/**` is not valid in every scenario. The URL is determined by the vercel team` or account slug

## What is the new behavior?

The url `https://*-<team-or-account-slug>.vercel.app/**` should be the correct identifier

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by charislam** [comment]
Thanks for opening the issue @sarthakgupta072! Can you give me a few examples of your preview URLs if possible?

I'm wondering what they look like, because as far as I know there is no project appended to the end of the subdomain. For example, the preview URLs for our own Vercel deployments look like this:

https://docs-git-feat-contributing-supabase.vercel.app
https://docs-git-refactor-app-router-cli-supabase.vercel.app

But it's possible that there are many different formats and we're missing some.

**Comment by sarthakgupta072** [comment]
Hey @charislam. I recently noticed this in my own project while integrating social login.

https://deep-work-tracker-git-feat-goo-5f283f-sarthakgupta072s-projects.vercel.app/

Please lemme know if I am doing something different to get the `projects` appended to my deployment

**Comment by sarthakgupta072** [comment]
okay for my `main` branch I am noticing 3 URLs
* https://deep-work-tracker-chi.vercel.app/
* https://deep-work-tracker-sarthakgupta072s-projects.vercel.app/
* https://deep-work-tracker-git-main-sarthakgupta072s-projects.vercel.app/

image

**Comment by charislam** [comment]
👀 @sarthakgupta072 double-checking that your vercel slug is just `sarthakgupta072s` and not `sarthakgupta072s-projects`?

**Comment by sarthakgupta072** [comment]
@charislam hey. My team name is `sarthakgupta072's projects`, but my usename is `sarthakgupta072`.

image
image

And in the documentation it says `https://*-username.vercel.app/**`. I think that's what confused me. 😅 

Should it be `https://*-teamname.vercel.app/**` instead of existing `https://*-username.vercel.app/**`? What do you think?

**Comment by charislam** [comment]
@sarthakgupta072 you're right, according to Vercel it's the [account or team slug](https://vercel.com/docs/deployments/generated-urls#url-components), so we can change it to that!

**Comment by sarthakgupta072** [comment]
@charislam got it.

Does `https://*-<team-slug>.vercel.app/**` sounds good?

Or as per the [documentation](https://vercel.com/docs/deployments/generated-urls#url-components), we should go  with `https://*-<scope-slug>.vercel.app/**`?

I'll update the PR accordingly

**Comment by charislam** [comment]
@sarthakgupta072 maybe `<team-or-account-slug>`? I find `<scope-slug>` not particularly understandable without linking to a secondary doc 😄

**Comment by sarthakgupta072** [comment]
> @sarthakgupta072 maybe `<team-or-account-slug>`? I find `<scope-slug>` not particularly understandable without linking to a secondary doc 😄

I agree. Let me do this only then `https://*-<team-or-account-slug>.vercel.app/**`

**Review by charislam — APPROVED** [review]
Awesome thanks @sarthakgupta072!

**Pull request merged**
