### PR TITLE
latest blog posts in navbar

### PR DESCRIPTION
**Pull request by fsansalvadore**
## What kind of change does this PR introduce?

Retrieve latest blog posts in "Developers" navbar dropdown from all pages.

This has to be done via getStaticProps or getServerProps on all pages because it needs to build from the filesystem since we're serving blog posts via mdx.

## Additional notes

Avoided fetching latest posts in dynamic routes for now ("/integrations/experts", etc) because it would exceed the build serverless functions size limit as shown in the screenshot below.

Need to optimize further (or upgrade vercel to Enterprise plan) in future iteration.
These pages (with less traffic) simply fall back to previous behaviour.

Screenshot 2024-03-08 at 16 29 43

### CODE REVIEW

**Comment by MildTomato** [comment]
what?!

**Comment by MildTomato** [comment]
Maybe an alternative approach using a HOC.

(from chatgpt)

Here's how you can modify the approach to fetch the latest blog posts data once and share it across all pages:

```jsx
// components/Layout.js

import React from 'react';

const Layout = ({ children, latestBlogPosts }) => {
  // Render latest blog posts
  const renderLatestBlogPosts = () => {
    return (
      <div>
        <h2>Latest Blog Posts</h2>
        <ul>
          {latestBlogPosts.map(post => (
            <li key={post.id}>
              <a href={`/blog/${post.slug}`}>{post.title}</a>
            </li>
          ))}
        </ul>
      </div>
    );
  };

  return (
    <div>
      {renderLatestBlogPosts()}
      {children}
    </div>
  );
};

export default Layout;
```

Then, create a context to manage the latest blog posts data:

```jsx
// components/BlogContext.js

import React, { createContext, useContext, useState, useEffect } from 'react';
import { fetchLatestBlogPosts } from '../utils/api';

const BlogContext = createContext();

export const BlogProvider = ({ children }) => {
  const [latestBlogPosts, setLatestBlogPosts] = useState([]);

  useEffect(() => {
    const fetchPosts = async () => {
      const posts = await fetchLatestBlogPosts();
      setLatestBlogPosts(posts);
    };
    fetchPosts();
  }, []);

  return (
    <BlogContext.Provider value={latestBlogPosts}>{children}</BlogContext.Provider>
  );
};

export const useLatestBlogPosts = () => useContext(BlogContext);
```

In your `_app.js`, wrap your application with `BlogProvider` to make the latest blog posts data available globally:

```jsx
// pages/_app.js

import React from 'react';
import { BlogProvider } from '../components/BlogContext';
import Layout from '../components/Layout';

function MyApp({ Component, pageProps }) {
  return (
    <BlogProvider>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </BlogProvider>
  );
}

export default MyApp;
```

Now, in your layout component, you can use `useLatestBlogPosts` to access the latest blog posts data:

```jsx
// components/Layout.js

import React from 'react';
import { useLatestBlogPosts } from './BlogContext';

const Layout = ({ children }) => {
  const latestBlogPosts = useLatestBlogPosts();

  // Render latest blog posts
  const renderLatestBlogPosts = () => {
    return (
      <div>
        <h2>Latest Blog Posts</h2>
        <ul>
          {latestBlogPosts.map(post => (
            <li key={post.id}>
              <a href={`/blog/${post.slug}`}>{post.title}</a>
            </li>
          ))}
        </ul>
      </div>
    );
  };

  return (
    <div>
      {renderLatestBlogPosts()}
      {children}
    </div>
  );
};

export default Layout;
```

**Comment by fsansalvadore** [comment]
@MildTomato I remember trying to use a HOC but the problem was that we're not fetching from an API but reading from a file system, which needs to be done in getStaticProps per page. I'm not aware of being able to use getStaticProps in a HOC.

Anyway this PR is quite stale now, might close it for now.

**Comment by MildTomato** [comment]
check out ContentLayer.
You can create a .json file of all the posts and just play around with it like any other JSON data

**Pull request closed without merging**
