### PR TITLE
[Update] with-ionic-react.mdx file

### PR DESCRIPTION
**Pull request by 0amirk**
## Updated the docs for building a user management app with Ionic React.

docs update

## The current docs uses 
const [session] = useState(() => supabase.auth.session());
And
const user = supabase.auth.user();

This is mentioned in #17507 

## Updated the docs to reflect the new changes 
 const { data, error } = await supabase.auth.getSession();
And
const { data: { user } } = await supabase.auth.getUser();

### CODE REVIEW

**Comment by 0amirk** [comment]
@alaister could you please check this?

**Review by alaister — CHANGES_REQUESTED** [review]
Hey @0amirk,

Thanks for your PR. It's getting there, but still needs a few changes:
- `await` won't work in the `AccountPage` function due to it not being `async`.

You might like to follow the [React guide](https://supabase.com/docs/guides/getting-started/tutorials/with-react#launch) as it has an updated version of this code.

Thanks!

**Comment by 0amirk** [comment]
Should I declare the AccountPage function async or should I use this code block that I got from the link you gave.
Sorry for the trouble.

const [session, setSession] = useState(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

**Comment by 0amirk** [comment]
@alaister  I'm sorry to tag you again. Could you please help me.

**Comment by alaister** [comment]
@0amirk Unfortunately, just making the function `async` would be too easy 😅 (as far as I'm aware ionic doesn't support server components) so you'll need to use that code block 👍🏻

**Comment by 0amirk** [comment]
Thanks for the help. I'll update the pr in a few days. 👍

**Comment by 0amirk** [comment]
@alaister Done. Also could you please add the hacktober tag to this. 🙏

**Comment by alaister** [comment]
Hey,

Thanks again for the PR.

Unfortunately, this has gotten quite stale, so I'm going to go ahead and close this PR.

Please don't hesitate to open up a new PR if the changes are still relevant.

**Pull request closed without merging**
