### PR TITLE
feat: rls button table editor

### LINKED ISSUE #14130: Reduce RLS warning clutter
In the Table Editor, if you have RLS disabled, you'll see both of these warnings — a badge and a banner: 
In this case, the banner is sufficient. To reduce clutter there, we shouldn't show the badge. 

CleanShot 2023-05-04 at 12 27 01@2x

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase Studio > Table Editor

## What is the current behavior?

Currently if no RLS is enabled a lot of warnings appear.

## What is the new behavior?

RLS badge is now removed:

https://user-images.githubusercontent.com/22655069/236299202-3bc6410d-861a-413d-90f6-cc1de822425a.mov

## Additional context

Closes #14130

### CODE REVIEW

**Comment by saltcod** [comment]
Thanks for looking at this @Hallidayo . There's another state to consider: 

Here, I've dismissed the warning and now no longer have a badge of any kind. The "RLS disabled"  badge should show here when I've dismissed the banner. 

CleanShot 2023-05-08 at 12 19 27@2x

**Comment by Hallidayo** [comment]
Hi @saltcod 

The button is coming through now once the acknowledgement has been accepted:

Screenshot 2023-05-08 at 20 28 09

**Comment by saltcod** [comment]
Thanks @Hallidayo 

there's still that in-between state where you've clicked Dismiss but haven't reloaded the page yet:

CleanShot 2023-05-10 at 15 04 56@2x

We'd need to pass a prop down to trigger that rerender.

**Comment by MildTomato** [comment]
> We'd need to pass a prop down to trigger that rerender.

Anyone want to update this with the rerender stuff ?

**Comment by saltcod** [comment]
Thanks for this @Hallidayo — going to close this one as it was resolved in another PR. Thanks!

**Pull request closed without merging**
