### PR TITLE
Feat/kill switch for project creation and add on updates

### PR DESCRIPTION
**Pull request by joshenlim**
[Updated on 06 June 22]

## Added kill switches to disable project creation and billing updates.  
- Project creation and add-on updates are toggled by a single feature flag.
- Deprecate use of `nativeBilling` feature flag
- Change subscription button on settings/billing is disabled if flag is true
- Also added logic to disable upgrade buttons on settings/billing/update
  - But enterprise contact form is still clickable
  - If try to access free or pro upgrade pages, will redirect back to settings/billing

Disabled state for project creation

Disabled state for project add on update

## Added flag to show incident banner if need to
- Controlled by a separate single flag
- Shows a banner up top the entire dashboard to direct users to status.supabase.com

### CODE REVIEW

**Comment by saltcod** [comment]
@joshenlim looks great! 

Couple of contrast things again with light mode there. Using text size and weight to differentiate the copy might be enough there.   The icon(`<IconAlertCircle className="text-white" size="large" strokeWidth={1.5} />`) has a text-white class instead of a generic colour. 

 
CleanShot 2022-06-03 at 08 32 24@2x

The `You can rename your project later` line caught my eye as I was going over this. For a second I thought:  "Can I create and name the project now and put it into a queue or something until the service is back up and then rename it?"   Maybe guard that line? `{!projectCreationDisabled && <span className="text-scale-900 text-xs">You can rename your project later</span>}`

**Comment by joshenlim** [comment]
Ahh great catches on this one - will update! 🙏

**Comment by joshenlim** [comment]
@saltcod Updated based on your comments, but also updated some logic after chatting with @MildTomato

**Comment by saltcod** [comment]
@joshenlim pushed up a small commit to make the text colour the same in light and dark mode — it was black on green in light mode originally. 

Now this, in both light and dark:
CleanShot 2022-06-06 at 09 13 52@2x

**Comment by saltcod** [comment]
@joshenlim looks great! Happy to approve, but wouldn't mind Alaister having a quick peek first as well.

**Review by alaister — APPROVED** [review]
Working beautifully! 🚢

**Pull request merged**
