### PR TITLE
feat/studio: Enable .env provisioned values for "Default Organization" and "Default Project"

### PR DESCRIPTION
**Pull request by TokenChingy**
## What kind of change does this PR introduce?

This feature allows users to provide values to override the "Default Organization" and "Default Project" through a `.env` file.

## What is the current behavior?

The values on the studio landing page for "Default Organization" and "Default Project" are not configurable.

## What is the new behavior?

The values on the studio landing page for "Default Organization" and "Default Project" are now configurable using a `.env` file.

## Additional context

[Related discussion](https://github.com/supabase/supabase/discussions/4907)

### CODE REVIEW

**Comment by MildTomato** [comment]
Studio changes look ok.
Not sure about the docker suggestions though, need another reviewer

**Review by adityadhawan22 — COMMENTED** [review]
LGTM 👍

**Review by adityadhawan22 — APPROVED** [review]

**Comment by TokenChingy** [comment]
Fixed merge conflicts @adityadhawan22

**Review by kiwicopple — APPROVED** [review]
sorry for the delay here, completely missed this. 

Looks great!

**Review by saltcod — APPROVED** [review]

**Comment by MarcusMorter** [comment]
For any1 who stumbles here wondering why changing the organization and project name values does not work in the docker-compose file, you need to rename the enviremnt variables for the studio service from 
```
DEFAULT_ORGANIZATION: ${STUDIO_DEFAULT_ORGANIZATION}
DEFAULT_PROJECT: ${STUDIO_DEFAULT_PROJECT}
```
to
```
DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}
```

as the values with the "_NAME" suffix are the actual variables used in studio

**Comment by philmas** [comment]
Thank you @MarcusMorter! That solved it for me.

**Pull request merged**
