### PR TITLE
Fixes docs search input cursor (#28685)

### LINKED ISSUE #28685: The cursor jumping  to the end of the sentence after the first backspace press in the search input field of supabase docs
# Improve documentation

## Link 
https://supabase.com/docs

## Describe the problem

When editing text on the search input field of the supabase docs, the backspace key shows unexpectedly behavoiour. Specifically:

When I am trying to search for a long word or a sentence in the supabase docs but then I see I have made a spelling error I will move the cursor to the part of the query where i want to rectify it then the following things happen.

Initial Backspace Press: When I press backspace for the first time, it correctly deletes the character to the left of the cursor.

Cursor Movement:  But immediately after the first deletion, the cursor jumps to the end of the sentence.

Subsequent Backspace Presses: Any further presses of the backspace key delete characters from the end of the sentence instead of the cursor’s original position when i first started changing my input.

## Describe the improvement

The cursor should remain in its original position after the first backspace press, allowing for continuous deletion from the middle of the sentence.

## Additional context
Steps to Reproduce:

Type a sentence in the search input field.
Place the cursor in the middle of the sentence.
Press the backspace key once (observe the character deletion and cursor movement).
Press the backspace key again (the deletion happens from the end of the sentence).

### PR DESCRIPTION
**Pull request by preetDev004**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.
YES

## What kind of change does this PR introduce?
Bug fix,

## What is the current behavior?
When we try to delete or insert from the mid-part of the input in [docs](https://supabase.com/docs) search menu the cursor moves to end of the line/to the right which ruins UX.
https://github.com/user-attachments/assets/763baef6-60ee-4c38-9eed-481b73e41a09

Please link any relevant issues here.
closes #28685 

## What is the new behavior?
When Fixed the cursor is not moving to the end of the line.
https://github.com/user-attachments/assets/9b972e8d-dff4-4c7f-9fb5-3ff0888fd8fc

Feel free to include screenshots if it includes visual changes.
## Additional context
N/A

Add any other context or screenshots.
N/A

### CODE REVIEW

**Comment by fsansalvadore** [comment]
Thanks for the PR @preetDev004.
Your solution loses the query string when hitting the `Search the docs` option.

See recording:
https://github.com/user-attachments/assets/e7b0109b-1201-4249-97dc-497d835b31f1

**Review by fsansalvadore — DISMISSED** [review]
Thanks for the PR @preetDev004.
Your solution loses the query string when hitting the Search the docs option.

See recording:
https://github.com/user-attachments/assets/dc3cab31-5062-41db-9d46-c4875282cd04

**Comment by preetDev004** [comment]
> Thanks for the PR @preetDev004. Your solution loses the query string when hitting the Search the docs option.
> 
> See recording: https://github.com/user-attachments/assets/dc3cab31-5062-41db-9d46-c4875282cd04

Hey @fsansalvadore, thanks for pointing it out.

it's fixed now:
https://github.com/user-attachments/assets/2c80f067-7372-490b-a33e-5b28f80b5aa2

**Review by charislam — APPROVED** [review]
Thanks @preetDev004!

**Pull request merged**
