### PR TITLE
refactor: update empty tables placeholder

### LINKED ISSUE #15425: Better "no tables" view in database/tables
When you first create a project and go to the database tables page, it’s not clear to some customers what it’s meant for or how to use it. Easy to miss the + New table button in the top right, especially on large screens.

An interface like Functions has would be better here.

CleanShot 2023-06-28 at 14 12 33@2x

### PR DESCRIPTION
**Pull request by takanome-dev**
## What kind of change does this PR introduce?

This PR introduces a new component called `ProductEmptyState` to the `TableList` component. This component is displayed when there are no tables to show. It provides a clear message and a call-to-action button to create a new table. Additionally, it includes some explanatory text about tables and their usage in Postgres. This change improves the user experience by providing helpful information and guiding the user to take appropriate actions.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What is the current behavior?

Currently, it’s easy to miss the `+ New table` button in the top right, especially on large screens.

## What is the new behavior?

The default placeholder is replaced with a placeholder like the one on the functions page.

Will provide a screenshot shortly

## Additional context

Closes #15425

### CODE REVIEW

**Comment by saltcod** [comment]
Thanks @takanome-dev 

Had a look and updated the text, fixed the merge conflicts. 

We still need to handle the case where someone has tried to search for a table but found no results from that query. That could use the old "hummm...no tables found" interface from the old component. 

CleanShot 2023-08-25 at 17 13 41@2x

**Comment by takanome-dev** [comment]
Thanks for taking the time reviewing this, @saltcod 

> We still need to handle the case where someone has tried to search for a table but found no results from that query. That could use the old "hummm...no tables found" interface from the old component.

I totally missed that, I did it. Thanks.

How about using the new `no search results` component in `components/ui` which has the ability to reset filters over the old one?

**Comment by awalias** [comment]
looks like we have some new merge conflicts sorry @takanome-dev 

if you're able to fix we'll try and get this one merged asap

**Comment by takanome-dev** [comment]
> looks like we have some new merge conflicts sorry @takanome-dev
> 
> if you're able to fix we'll try and get this one merged asap

No worries @awalias. It looks like this has been fixed. I can't tell what it looks like but looking at the code, I think it's all good now. 

Fixed in https://github.com/supabase/supabase/pull/17234 by @joshenlim

Feel free to close this pr if that's the case. Thanks for the heads up :+1:

**Comment by saltcod** [comment]
Yes it has. Thanks @takanome-dev — appreciate the contribution. Sorry for the delay on this one.

**Pull request closed without merging**
