### PR TITLE
fix: deprecated docker-compose in favour of compose v2

### PR DESCRIPTION
**Pull request by ethicnology**
## What kind of change does this PR introduce?

This PR replace docker-compose v1 which is deprecated by compose v2.
It will fix the deprecated error
It contains an update for scripts and documentation

## What is the current behavior?

```sh
docker-compose up
```

```
CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
```

In fact, the docker-compose python script is deprecated.

## What is the new behavior?

```sh
docker compose up
```

```sh
WARN[0000] The "MFA_ENABLED" variable is not set. Defaulting to a blank string. 
[+] Running 8/0
 ⠿ Container supabase-kong      Running                                    0.0s
 ⠿ Container supabase-studio    Running                                    0.0s
 ⠿ Container supabase-db        Running                                    0.0s
 ⠿ Container supabase-rest      Created                                    0.0s
 ⠿ Container supabase-meta      Created                                    0.0s
 ⠿ Container supabase-storage   Created                                    0.0s
 ⠿ Container supabase-auth      Created                                    0.0s
 ⠿ Container supabase-realtime  Created                                    0.0s
Attaching to supabase-auth, supabase-db, supabase-kong, supabase-meta, supabase-realtime, supabase-rest, supabase-storage, supabase-studio
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Attempting to connect to the database...
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Listening on port 3000
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Connection successful
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Config reloaded
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Listening for notifications on the pgrst channel
supabase-rest      | 03/Dec/2022:16:55:45 +0000: Schema cache loaded
supabase-meta      | 
supabase-meta      | > @supabase/postgres-meta@0.0.0-automated start
supabase-meta      | > NODE_ENV=production node bin/src/server/app.js
supabase-meta      | 
supabase-storage   | 2022-12-03T16:55:46: PM2 log: Launching in no daemon mode
supabase-storage   | 2022-12-03T16:55:46: PM2 log: App [server:0] starting in -fork mode-
supabase-storage   | 2022-12-03T16:55:46: PM2 log: App [server:0] online
supabase-auth      | {"level":"info","msg":"Go runtime metrics collection started","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"component":"pop","level":"info","msg":"Migrations already up to date, nothing to apply","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"args":[0.016566615],"component":"pop","level":"info","msg":"%.4f seconds","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"level":"info","msg":"GoTrue migrations applied successfully","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"component":"api","level":"warning","msg":"DEPRECATION NOTICE: GOTRUE_JWT_ADMIN_GROUP_NAME not supported by Supabase's GoTrue, will be removed soon","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"component":"api","level":"warning","msg":"DEPRECATION NOTICE: GOTRUE_JWT_DEFAULT_GROUP_NAME not supported by Supabase's GoTrue, will be removed soon","time":"2022-12-03T16:55:46Z"}
supabase-auth      | {"level":"info","msg":"GoTrue API started on: 0.0.0.0:9999","time":"2022-12-03T16:55:46Z"}
supabase-meta      | {"level":"info","time":"2022-12-03T16:55:46.996Z","pid":18,"hostname":"5dcd962a3312","msg":"Server listening at http://0.0.0.0:8080"}
supabase-meta      | {"level":"info","time":"2022-12-03T16:55:46.997Z","pid":18,"hostname":"5dcd962a3312","msg":"App started on port 8080"}
supabase-meta      | {"level":"info","time":"2022-12-03T16:55:47.003Z","pid":18,"hostname":"5dcd962a3312","msg":"Server listening at http://0.0.0.0:8081"}
supabase-meta      | {"level":"info","time":"2022-12-03T16:55:47.003Z","pid":18,"hostname":"5dcd962a3312","msg":"Admin App started on port 8081"}
supabase-storage   | running migrations
supabase-realtime  | 2022-12-03 16:55:47.630 [info] Migrations already up
supabase-storage   | finished migrations
supabase-storage   | {"level":"info","time":"2022-12-03T16:55:48.107Z","pid":18,"hostname":"fbd23821b108","msg":"Server listening at http://0.0.0.0:5000"}
supabase-storage   | Server listening at http://0.0.0.0:5000
```

## Additional context

- [Docker announcing compose v2](https://www.docker.com/blog/announcing-compose-v2-general-availability/)
- [docker-compose vs docker compose on stackoverflow](https://stackoverflow.com/a/66516826/16010394)

### CODE REVIEW

**Comment by alaister** [comment]
Hey @ethicnology,

Thanks for this! Would you mind merging in `master` so there isn't a merge conflict?

@sweatybridge, would you mind doing a quick review? Am I correct in assuming you're up on all the docker stuff?

**Comment by ethicnology** [comment]
@alaister sorry I didn't get it, I'm already merging into master

**Comment by alaister** [comment]
I mean to merge the Supabase master branch into your branch again, so we are able to merge this. Currently, there is a merge conflict:
Screenshot 2022-12-20 at 10 56 38 pm

**Comment by ethicnology** [comment]
@alaister done (synchronization with master, has temporarily closed the PR)

**Review by sweatybridge — APPROVED** [review]
Yup LGTM. No changes to compose file required.

**Comment by alaister** [comment]
Thanks again @ethicnology!

**Pull request merged**
