### PR TITLE
fix: cmdk key bindings clash with Supabase Studio’s built-in GraphiQL…

### PR DESCRIPTION
**Pull request by PurnenduMondal**
To fix the bug, I added onFocus and onBlur props to the GraphiQL QueryEditor component. These props are used to set the focus state of the QueryEditor. Then I created a new context named GraphiQLQueryEditorFocusContext to store and access the focus state of the QueryEditor globally and then I fetched the isGraphiQLEditorOnFocus state in CommandMenuWrapper and passed it as a prop to the CommandMenuProvider, with the help of this prop I am restricting the command menu to open when the GraphiQL QueryEditor is in focus so that cmd + / shortcut can only be used to comment out the code in the QueryEditor.

Issue: [18269](https://github.com/supabase/supabase/issues/18269)

### CODE REVIEW

**Comment by alaister** [comment]
Hey @PurnenduMondal,

Thanks for your PR!

I'm worried that this approach adds both user-land complexity (getting a different cmd+k menu than you're expecting) and code complexity (the existing cmd+k menu has to worry about GraphiQL now).

So, what do you think about just modifying the existing GraphiQL shortcut? Could be something like cmd+option+k?

**Comment by PurnenduMondal** [comment]
Hi @alaister 

Thank you for taking the time to review the PR, and I appreciate your feedback. 

Modifying the existing GraphiQL shortcut, such as using cmd+option+k, seems like a reasonable suggestion. This approach could help avoid conflicts with the default cmd+k menu and minimize disruptions for users. I will try it out and let you know.

**Comment by PurnenduMondal** [comment]
Hi @alaister 

I am currently experiencing some issues while running the master branch locally. In order to run it, I am following these steps:

1. Running all the containers except the studio.
2. Running the studio using 'npm run dev'.

However, when accessing the GraphiQL Editor page at http://localhost:8082/project/default/database/graphiql, it always returns a 404 error in response to these API calls:

GET http://localhost:8082/api/projects-resource-warnings
GET http://localhost:8082/api/integrations/default-org-slug?expand=true

I believe this is causing the page to remain in a 'Loading' state. Could you please let me know if I am doing something wrong and what I can do to resolve this issue?

Thank you.

**Comment by alaister** [comment]
Sorry, we're moving GraphiQL around a bit. Please make sure your branch is up to date, then visit [http://localhost:8082/dashboard/project/default/api/graphiql](http://localhost:8082/dashboard/project/default/api/graphiql).

If it's still not working, I'll dig a bit deeper!

**Comment by PurnenduMondal** [comment]
Hi @alaister 

It's returning a 404 page at http://localhost:8082/dashboard/project/default/api/graphiql. 

I have also attempted the following URL: 
http://localhost:8082/project/default/api/graphiql. 
However, after a prolonged loading period, it throws the following error: 
FATAL ERROR: Reached heap limit. Allocation failed - JavaScript heap out of memory. 

System information: 
OS: Windows 11, 
Browser: Chrome 119.0.6045.124.

**Comment by saltcod** [comment]
Hey @PurnenduMondal sorry for the back and forth on this PR. At the moment, we're considering moving GraphiQL to a different part of the Dashboard which might indirectly fix this with no additional code. I'm going to mark this as closed, but appreciate your effort here!

**Pull request closed without merging**
