### PR TITLE
Fix height issue

### LINKED ISSUE #21193: [bug] height issue in dashboard homepage
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Homescreen side bar is not full height when content on right is smaller than screen height.

Screenshot 2024-02-12 at 11 08 47 AM

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to homepage in dash
2. Make sure you only have a few projects

### PR DESCRIPTION
**Pull request by joshenlim**
Resolves https://github.com/supabase/supabase/issues/21193

### CODE REVIEW

**Review by alaister — COMMENTED** [review]
Not sure if this is really an issue, but if you have a lot of projects the sidebar doesn't continue down:

Screenshot 2024-02-13 at 16 27 51

**Review by alaister — COMMENTED** [review]
Also the scrolling in safari still seems a bit borked :/



https://github.com/supabase/supabase/assets/10985857/f9046b98-2dc3-42c3-a3ab-bf00e238a79e

**Comment by joshenlim** [comment]
> scrolling safari seems a bit borked

ahh yup - got a separate ticket for that here https://github.com/supabase/supabase/issues/21178
It's cause we removed all the magic numbers (which is a great thing) and safari isn't happy about it :/

**Comment by joshenlim** [comment]
> Not sure if this is really an issue, but if you have a lot of projects the sidebar doesn't continue down:

this one's on chrome? i can't seem to repro on latest staging here https://studio-staging-juplf812u-supabase.vercel.app/dashboard/projects

**Comment by alaister** [comment]
Ahh sorry I should have said that was Safari also!

**Comment by joshenlim** [comment]
> Ahh sorry I should have said that was Safari also!

Ahh okay yeah we'll look into that separately, this PR would resolve the height issue for the other browsers for now

**Review by alaister — APPROVED** [review]
LGTM!

**Pull request merged**
