### PR TITLE
docs: Sveltekit connect guide update

### PR DESCRIPTION
**Pull request by JR-G**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

### Docs update
Amend the instructions for the Sveltekit connect guide.

## What is the current behavior?

https://github.com/supabase/supabase/issues/28943

Following the Sveltekit connection guide on the project dashboard causes:
```
[vite] Error when evaluating SSR module /src/lib/supabaseClient.js:
|- Error: supabaseUrl is required.
```

## What is the new behavior?

Follow the [$env/static/public](https://kit.svelte.dev/docs/modules#$env-static-public) implementation.

`.env.local`:
Prefixing with `PUBLIC_`

```
PUBLIC_SUPABASE_URL=xxxx
PUBLIC_SUPABASE_ANON_KEY=xxxx
```

`src/lib/supabaseClient.js`:

```
import { createClient } from "@supabase/supabase-js";
import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from "$env/static/public"

const supabaseUrl = PUBLIC_SUPABASE_URL;
const supabaseKey = PUBLIC_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseKey);
```

### CODE REVIEW

**Comment by ivasilov** [comment]
Hi @JR-G can you provide SvelteKit documentation where it uses `VITE_` env vars? I tried to find it, but couldn't. Shouldn't the env vars be using [this approach](https://kit.svelte.dev/docs/modules#$env-dynamic-public) (`PUBLIC_` prefix)?

**Comment by JR-G** [comment]
> Hi @JR-G can you provide SvelteKit documentation where it uses `VITE_` env vars? I tried to find it, but couldn't. Shouldn't the env vars be using [this approach](https://kit.svelte.dev/docs/modules#$env-dynamic-public) (`PUBLIC_` prefix)?

Hi @ivasilov  — you're right. The `PUBLIC_` prefix initially wasn't working for me, which I put down to complete user error 🥴.

Do you have a preference between `static/public` and `dynamic/public`? Otherwise, I'll follow the `static` implementation due to: 

> Note that public dynamic environment variables must all be sent from the server to the client, causing larger network requests — when possible, use $env/static/public instead.

**Comment by JR-G** [comment]
Hi @ivasilov 👋  — I've updated the PR to follow the `static/public` convention.

**Review by ivasilov — APPROVED** [review]

**Comment by ivasilov** [comment]
Ty @JR-G for your contribution!

**Pull request merged**
