### PR TITLE
fix: persist pgsodium encryption key between restarts

### PR DESCRIPTION
**Pull request by ghost**
## What kind of change does this PR introduce?

Bug fix for https://github.com/supabase/vault/issues/27

## What is the current behavior?

Currently, the docker-compose example does not persist the `pgsodium` encryption key that is used by supabase vault (a new, random key is generated on each `docker compose down`/`docker compose up` combination). 

## What is the new behavior?

**WARN** needs: https://github.com/supabase/postgres/pull/901

The `pgsodium` key `/etc/postgresql-custom/pgsodium/pgsodium_root.key` is cached in `/volumes/db/pgsodium`

## Additional context

NEEDS: https://github.com/supabase/postgres/pull/901

~~See https://github.com/supabase/vault/issues/27#issuecomment-1984187441 for the `:Z` flag requirement.~~

### CODE REVIEW

**Review by sweatybridge — APPROVED** [review]

**Comment by nbarrow-inspire-labs** [comment]
closing due to this not fixing the issue on clean installs

**Comment by nbarrow-inspire-labs** [comment]
@sweatybridge hold off on this, noticed a bug. Will update momentarily.

**Comment by nbarrow-inspire-labs** [comment]
@sweatybridge and others, we would need something like https://github.com/supabase/postgres/pull/901 before this would work (it would need modifications as I did here)

**Comment by nbarrow-inspire-labs** [comment]
Okay I think this would work, as updated, but it needs https://github.com/supabase/postgres/pull/901 first, or something of the like.

**Comment by nbarrow-inspire-labs** [comment]
Thanks for getting to this @sweatybridge , your fix was a lot more elegant than mine.

**Pull request merged**
