### PR TITLE
Chore/rename open ai key name

### PR DESCRIPTION
**Pull request by saltcod**
Renames instances of OPENAI_KEY to OPENAI_API_KEY to be inline with industry convention

**Areas replaced**

- [ ]  Edge functions on the [LIVE] supabase-com project (done)
- [ ]  GitHub Actions (done)
- [ ]  Vercel (studio, www, docs) (done)
- [ ]  aws secrets manager (done)

### CODE REVIEW

**Review by charislam — COMMENTED** [review]
Where does the newly named secret need to be added? At a glance:

- [x] Edge functions on the [LIVE] supabase-com project
- [ ] GitHub Actions
- [ ] Vercel (studio, www, docs)

Am I missing any?

**Comment by saltcod** [comment]
oooh thanks @charislam had the others but missed Edge functions on the [LIVE] supabase-com !

not planning to merge this till Monday as it touches...everything :^)

**Comment by saltcod** [comment]
https://www.notion.so/supabase/All-AI-capabilities-available-on-local-f3ae9b67c46d4c4e8921b83bdfb165c9

**Comment by saltcod** [comment]
- [ ] aws secrets manager

**Review by charislam — APPROVED** [review]

**Pull request merged**
