### PR TITLE
Documentation: Add section about testing row-level-security

### PR DESCRIPTION
**Pull request by tvogel**
## What kind of change does this PR introduce?

Documentation update to get started with testing RLS policies.

## What is the current behavior?

You need to google to find hints on how to switch roles (and JWT context).

## What is the new behavior?

When reading about supabase RLS, you'll immediately get pointed to testing your policies.

## Additional context

I think, it would be a good idea having those `login_*/logout()` procedures included in the `auth` schema by default because they seem to be of general interest (unless when not using RLS at all). The use of the internal `auth` schema might be a point of argument?

### CODE REVIEW

**Review by dannykng — COMMENTED** [review]
Thanks @tvogel! 

@hf mind taking a look at this too? 🙏🏼

**Comment by tvogel** [comment]
Anything still for me to do on this? I think, the confusing vercel messages came in because I used the `master` branch on my forked repo instead of making a PR branch which somehow inherited automation setup, right?

**Comment by kiwicopple** [comment]
thanks @tvogel ! it looks good, I think it just needs a bit more info on how to use the functions. For example:

> To switch to a given user (by email), use `CALL auth.login_as_user('my@email.com');`. 

Perhaps you can show this in a full codeblock - something like this (or however you're using it):


```sql
call auth.login_as_user('my@email.com');

select * from public.profiles;

call auth.logout();
```

or as steps:

1. Go to the SQL Editor
2. Run `call auth.login_as_user('my@email.com');`
3. Any SQL query will now run as that user `select * from public.profiles;`
4. Call `call auth.logout();`

I don't actually know how you're using these functions, so I also don't know what the right approach is :)

**Comment by kiwicopple** [comment]
(as an aside, we typically use lower-case SQL in the doc)

**Comment by tvogel** [comment]
@kiwicopple I changed to lower-case SQL and added an example `psql` interaction. I did not find a suitable syntax highlighter for `psql` interactive sessions, so I used `shell` as a last resort because it is sort of a shell but if you known anything better, let me know!

**Review by kiwicopple — APPROVED** [review]
this is a great PR @tvogel !

Feel free to reach out on twitter if you want some swag - I can send you some codes for our swag store

**Comment by kiwicopple** [comment]
seems like prettier is failing - I will need to check out what's the problem before merging

**Comment by tvogel** [comment]
> seems like prettier is failing - I will need to check out what's the problem before merging

Are these again runs on my forked repo, or running against the original repo? Next time, I won't use `master` again, promise!

**Comment by mansueli** [comment]
Hey @tvogel, I think making a new PR on a new branch might be easier to get this deployed. Then, you can add a link to the new PR here and get it fast-tracked to approval & close this one. I would love to be able to share this with users contacting support about RLS.

**Comment by tvogel** [comment]
> Hey @tvogel, I think making a new PR on a new branch might be easier to get this deployed. Then, you can add a link to the new PR here and get it fast-tracked to approval & close this one. I would love to be able to share this with users contacting support about RLS.

OK, just did: #12637 !

**Comment by kiwicopple** [comment]
thanks ! merged that one, closing this one 👍

**Comment by tvogel** [comment]
Thanks a lot, great that contributions are appreciated!

**Pull request merged**
