### PR TITLE
Home page improvements

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## What kind of change does this PR introduce?

Home page improvements.

## What is the current behavior?

The home page feels too light or too dark, and the nav Flyout is weird.

## What is the new behavior?

- I tweaked some colors (mainly grays).
- I deleted the Badge component since the one from `@supabase/ui` is now used instead.
- I modified the Flyout component to make it full width. And because the Nav is now sticky, this menu disappears when the user clicks out and not when scrolling.
- I added a space for news at the top: it's stored in `www/data/NavNews.json`. As an example, I've put the April recap but any url can be linked there. It can even be disabled if not needed with `"show": true` in the same file.

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @florian-lefebvre - there seem to be a few issues with the Preview Deployment? Would you mind taking a couple of screen-caps of the changes?

I'll provide some input & then @MildTomato can provide a few comments when he gets back to work!

**Comment by inian** [comment]
Hey @@florian-lefebvre , the issue with the preview deploy was due to bug in master which [has been fixed](https://github.com/supabase/supabase/commit/a696caa6339a62a9f65043b3fc00817db2be802f). If you rebase / merge with master, we can inspect the preview deploy to see the changes you made.

**Comment by MildTomato** [comment]
Hey @florian-lefebvre, thanks for taking the time on this 👍 

It might be easier and quicker for us to merge changes in if this is split into different pull requests.

For example, split into, 
#1 color and navbar layout changes, 
#2 announcement bar feature, 
#3 navbar handleClick changes, 
and so on

**Comment by florian-lefebvre** [comment]
Hi @MildTomato, sure I'll do that when I have the time.

**Pull request closed without merging**
