### PR TITLE
feat: auth users search

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase Authentication > Users

## What is the current behavior?

You can only search by email or phone number.

Also the delete icon is not the same as other dropdowns.

## What is the new behavior?

You can now search by UID and also the delete icon is now red:

Screenshot 2024-01-11 at 21 49 33

## Additional context

Discussed in #20040

### CODE REVIEW

**Comment by alaister** [comment]
Hey @Hallidayo,

Thanks for this! Unfortunately, this will only work on self-hosted since our platform API doesn't use the Next.js API routes. I'll ask them if they can make this same change there and then we should be able to get this in 👍

**Comment by Hallidayo** [comment]
Brilliant thanks @alaister

**Comment by Hallidayo** [comment]
Hi @alaister - Do you know if has been changed?

**Comment by saltcod** [comment]
No movement yet @Hallidayo  — tracking internally here 
https://www.notion.so/supabase/Allow-filtering-users-by-id-91fc1437706f4612885e151c8ab47dda?pvs=23

**Comment by kamilogorek** [comment]
API has been implemented. This can be merged now.

**Review by alaister — APPROVED** [review]
LGTM! Thanks, @Hallidayo and sorry for the delay!

**Pull request merged**
