### PR TITLE
Fix Typo: Correct 'druation' to 'duration

### PR DESCRIPTION
**Pull request by hawkcookie**
## What kind of change does this PR introduce?

docs update

### CODE REVIEW

**Comment by fsansalvadore** [comment]
Hey @hawkcookie, can you please fix the conflict locally?

**Comment by hawkcookie** [comment]
@fsansalvadore 
sure.

**Comment by hawkcookie** [comment]
@fsansalvadore fix conflict.

**Review by fsansalvadore — APPROVED** [review]
Thanks for the contribution @hawkcookie

**Pull request merged**
