### PR TITLE
Chore/update rls warnings

### PR DESCRIPTION
**Pull request by saltcod**
CleanShot 2023-03-29 at 15 26 36@2x

CleanShot 2023-03-29 at 15 26 48@2x

You get the confirm modal now, only when you go from on → off: 
Screenshot 2023-04-06 at 10 56 15 AM

Hitting Dismiss here also triggers the same modal:
Screenshot 2023-04-06 at 10 57 03 AM

screenshots updated by @MildTomato to reflect changes during discussion in thread

### CODE REVIEW

**Comment by joshenlim** [comment]
The language here needs to be dynamic - for e.g if im creating a table, it should be "RLS will be turned on"

image

**Comment by MildTomato** [comment]
to catch others up.

me and @saltcod spoke about this offline.

> Can we also condense this? you could remove the Important heading and make that into one whole paragraph:
>
> **You are turning Row Level Security (RLS)** 
> Before querying data from this table, it is necessary to write RLS policies. If access policies are not in place, your queries will always return an empty array of results.
> Then just make the button say Learn more about RLS (no need for a heading + a button)

my feedback on this particular messaging is to stress the knock on effect, not the setting name change.

the headline warning "you are turning X on", could be "You are making this table public"

Then its a case of explaining, "if you turn RLS off then unauthenticated ... etc "

I agree there is too much text on here, I tried to find a better example of a warning dialog but the example i was trying to find has been changed I think.

I can mock up a change quickly in this PR if you like @saltcod - maybe easier than me trying to explain.

**Comment by kiwicopple** [comment]
> All requests with anon will be accepted
> Anyone with the anon key will be able to copy, modify, add and delete any row in this table

can just condense these ones too

**Comment by MildTomato** [comment]
> Sounds good Jonny, can just condense these into one sentence

Just marking the warnings here and some explanation.

---

### Turning RLS (Row level security) off

---


** ⚠️ `The table foo will be publicly writable and readable`**
`Anyone with the anon key will be able to interact with this table. Please consider all the points below.`

---


**`• All requests with an anon key will be accepted`**
`Anyone with the anon key will be able to copy, modify, add and delete any row in this table`
> _make the developer aware that the anon key will now behave differently_


**`• Auth policies will not be enforced`**
`There are X (number) of policies on this table that will no longer be enforced. `
> _Developer should be aware that they are also turning off every policy._
> future idea - We could go even further in future update, and spell out every policy that is no longer going to be working as well.

`**• Before you make public, consider:**`
`Any personal information in this table will be publicly accessible`
`The table could be abused by a 3rd party repeatedly making requests against this table`
> make the developer aware of personal information violations and potential abuse. 

---

**Comment by saltcod** [comment]
Latest iteration here. Let's try and have a swarm on this and get it over the line. Too many interactions and word choices to async I think. 


CleanShot 2023-04-04 at 21 20 51@2x

**Comment by MildTomato** [comment]
@saltcod i updated screenshots in the main comment at top to reflect the kaizening :D 

approved

**Review by MildTomato — APPROVED** [review]

**Comment by saltcod** [comment]
@MildTomato you took dark mode screenshots ...............😭

[ 🤗 ]

**Pull request merged**
