### PR TITLE
React native example

### PR DESCRIPTION
**Pull request by kiwicopple**
## What kind of change does this PR introduce?

Adds a todo list app using expo

### CODE REVIEW

**Comment by ykdojo** [comment]
@kiwicopple What's the status of this PR? Should I take a look at it?

**Comment by kiwicopple** [comment]
@thorwebdev up to you - do you want YK to jump in on this one?

**Comment by thorwebdev** [comment]
My next planned steps are:

- Incorporate the UserContext from https://github.com/thorwebdev/nextjs-subscription-payments/blob/main/components/UserContext.js
- Add the DB stuff while watching out for https://github.com/supabase/supabase/issues/353#issuecomment-741519612

I'm definitely planning to do this as I want to get a feel for Supabase + React native, I'll add a WIP tag and assign to myself, but would definitely appreciate a review/comments @ykdojo

**Comment by ykdojo** [comment]
Okay sounds good, @thorwebdev! Let me know when you want me to review it.

**Comment by thorwebdev** [comment]
@ykdojo all functionality is now implemented. It definitely could do with some more design love, feel free to add commits if you feel like it.

**Comment by ykdojo** [comment]
@thorwebdev Just reviewed it. It's true that it could use some design love, but I think it's good enough for what it is. I'm just going to merge it.

**Pull request merged**
