### PR TITLE
chore(studio): update color scheme navbar

### PR DESCRIPTION
**Pull request by Chensokheng**
## What kind of change does this PR introduce?
Supabase  Studio's navbar color scheme is not right. 

## What is the current behavior?
Screen Shot 2022-10-11 at 2 50 14 PM

## What is the new behavior?
Feel free to include screenshots if it includes visual changes.
Screen Shot 2022-10-11 at 2 59 57 PM

### CODE REVIEW

**Comment by Isaiah-Hamilton** [comment]
@Chensokheng can you provide what browser and os you are running becuase I can't seem to reproduce this.

CleanShot 2022-10-12 at 12 11 00@2x

**Comment by Chensokheng** [comment]
> @Chensokheng can you provide what browser and os you are running becuase I can't seem to reproduce this.

@Isaiah-Hamilton I am using chrome on a Mac OS machine.

**Comment by Isaiah-Hamilton** [comment]
> can reproduce
> 
> * chrome
> * brave
> 
> can't reproduce
> 
> * safari

So this seems to be a chromium based browser issue, got it. The problem though is if someone is using light theme then they will have a dark scrollbar which wouldn't be ideal. Can you change it where the scrollbar color changes based on the current theme, that would be great.

**Comment by Chensokheng** [comment]
@Isaiah-Hamilton just updated. The navbar will change base on the user computer theme.  But we have another problem is on Studio dark theme is set to default and we do not have a button to toggle it  
Screen Shot 2022-10-13 at 11 32 18 AM

**Review by pucho — APPROVED** [review]

**Pull request merged**
