### PR TITLE
fix: remove unnecessary line wrap

### PR DESCRIPTION
**Pull request by juliusmarminge**
https://x.com/kiwicopple/status/1735336719254274366?s=46&t=Uy_Hg1WWwsYDe1YleBLsaA

### CODE REVIEW

**Comment by charislam** [comment]
ahaha thanks for this one 🍦

**Review by charislam — APPROVED** [review]

**Review by kiwicopple — APPROVED** [review]

**Comment by bautistaaa** [comment]
please do not merge, this was mine 👿

**Comment by charislam** [comment]
@bautistaaa, did you have an open PR? we don't assign issues here (it prevents stale assignments from slowing down fixes) so we try to merge in order of complete PR submission

If you want to help us with fixes, I'm sure we can find other weird formatting things! We have a few 😅

**Comment by bautistaaa** [comment]
> @bautistaaa, did you have an open PR? we don't assign issues here (it prevents stale assignments from slowing down fixes) so we try to merge in order of complete PR submission
> 
> If you want to help us with fixes, I'm sure we can find other weird formatting things! We have a few 😅

i’m just trolling. take it julius 😩

**Comment by charislam** [comment]
hahaha I see I am behind on the Twitter 😂

**Pull request merged**
