### PR TITLE
fix: Enhance the <title> tag on dashboard pages

### LINKED ISSUE #12818: Enhance the <title> tag on dashboard pages
We could enhance the <title> tag with more useful & contextual information. 

1. We could probably add the org name  everywhere 
2. Add the current table name when in the editor 
CleanShot 2023-03-05 at 20 36 37@2x

Per a great suggestion from https://twitter.com/blackevilgoblin/status/1632412048733663232

### PR DESCRIPTION
**Pull request by gitstart**
Fixes https://github.com/supabase/supabase/issues/12818

## What is the current behavior?
<title> tag have current-project | Supabase </title> information

## What is the new behavior?

This PR enhance the <title> tag with more useful & contextual information.

1. Org name is added to `title` everywhere
2. Current table name is added to `title` when in the editor 

https://user-images.githubusercontent.com/51731962/233342504-0156f421-41eb-42ee-8d9c-f741195c3387.mov

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @saltcod,
Noticed the project name is not included in the title suggestion below, do you think adding the project name in there would be equally benefitial?

222994047-fa581412-849f-4035-9b7e-c3c2ffcd9af4

**Comment by saltcod** [comment]
Yeah that would be good @gitstart — good idea.

**Comment by gitstart** [comment]
Thanks @saltcod, added now.

**Review by saltcod — APPROVED** [review]

**Comment by saltcod** [comment]
Looks great! thanks @gitstart!

**Pull request merged**
