### PR TITLE
Chore: move legal pages and oss page

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

move legal pages and oss page

## What is the current behavior?

legal pages and oss page in docs site

## What is the new behavior?

move legal pages and oss page on main site

### CODE REVIEW

**Review by dannykng — COMMENTED** [review]
I think we need redirects for these pages too:
- /docs/company/terms
- /docs/company/privacy
- /docs/company/aup
- /docs/company/sla

**Review by saltcod — APPROVED** [review]

**Comment by saltcod** [comment]
I added these redirects and hit approve. I'll merge it tomorrow when there's more people online just in case.

Thanks @Isaiah-Hamilton !

**Comment by MildTomato** [comment]
Could we improve the layout on these.. have a max width like on other pages?

Screenshot 2022-12-09 at 10 01 59 AM

**Comment by MildTomato** [comment]
@Isaiah-Hamilton see above comment.

then we can merge it in 🔥

**Comment by saltcod** [comment]
Note that we should move http://localhost:3001/docs/handbook/supasquad as well.  Can do that after this gets merged.

**Pull request merged**
