### PR TITLE
Chore/shift table editor sort filter page state to url

### PR DESCRIPTION
**Pull request by joshenlim**
Share your table editor state by copy pasting URLs
- Removed sort and filters from internal grid state
- Shifted sort and filters to URL state (thanks @alaister for the `useUrlState` hook)
- If client is entering the table editor with sort and filter params, table editor will load the data based on those
- Else the table editor will load what's from the local storage to "resume" the user's session
- Will eventually move page to URL state as well, but just to keep things within scope and not change too many things at once, just doing sort and filter in this PR

https://user-images.githubusercontent.com/19742402/176119836-92ffa126-eb90-45e2-9b99-d94b0ff7be47.mov

### CODE REVIEW

**Review by alaister — COMMENTED** [review]
Awesome feature!
One thing I ran into while testing was trying to use dates in the filters. For example a date with the format `2022-03-03 07:07:15` would produce the following error:
Screen Shot 2022-06-29 at 2 35 14 pm
It also chopped the date before the first `:`, so I think that character may be the problem.

**Comment by joshenlim** [comment]
ahh great catch on this one @alaister - will look into this! i've only tested real quick with simple inputs so thanks for this one 💪

**Review by alaister — CHANGES_REQUESTED** [review]
This works much better but still running into that bug when I change the filter operator. See in video:

https://user-images.githubusercontent.com/10985857/176611237-77422c39-281c-43ce-8b2e-31a3d1abb510.mov

**Review by alaister — APPROVED** [review]
lgtm! Thanks @joshenlim

**Pull request merged**
