### PR TITLE
feat: career page

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

New career page.

## What is the current behavior?

No career page

## What is the new behavior?

New career page

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by MildTomato** [comment]
Screenshot 2022-10-19 at 4 02 40 PM

fyi @Isaiah-Hamilton build is failing

**Review by kiwicopple — COMMENTED** [review]
qq: should this be "/career" or "/careers"?

**Comment by Isaiah-Hamilton** [comment]
> qq: should this be "/career" or "/careers"?

I think we should use `/careers` and have `/career` redirect to the correct url.

**Comment by MildTomato** [comment]
Needs to updated from `master` branch and conflicts resolving 😄 
@Isaiah-Hamilton

**Comment by MildTomato** [comment]
These 2 can be ignored.

Screenshot 2022-10-28 at 10 30 16 AM
Screenshot 2022-10-28 at 10 30 23 AM

please don't ignore the "Docs" build though

**Comment by Isaiah-Hamilton** [comment]
closing in favor for https://github.com/supabase/supabase/pull/9948

**Pull request closed without merging**
