### PR TITLE
astro middleware

### PR DESCRIPTION
**Pull request by kmalloy24**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

No middleware example included for Astro

## What is the new behavior?

Adds a middleware example for Astro

## Additional context

- Per this guide [Supabase SSR 😎 - one package to rule them all - No framework / Next.js / Remix / Astro](https://youtu.be/dcbyjeLe9Tc?t=1165)
- Reproduceable example with data fetching here: https://github.com/kmalloy24/astro-supabase-ssr-auth/blob/main/src/middleware.ts
- https://docs.astro.build/en/guides/middleware/

### CODE REVIEW

**Review by charislam — APPROVED** [review]
Thanks @kmalloy24!

**Comment by kmalloy24** [comment]
@charislam any interest in a larger PR for an Astro SSR Auth guide similar to the ones for Sveltekit & Next? I'd be happy to contribute once I have an example finished. 

I could reach out to the Astro team as well to work it into their [Supabase auth guide](https://docs.astro.build/en/guides/backend/supabase/#adding-authentication-with-supabase), which currently uses the JS client.

**Comment by charislam** [comment]
@kmalloy24  that would be awesome! 💚 Very appreciated.

Btw it looks like this PR is failing Prettier check, can you run a quick `npm run format` on it?

**Comment by kmalloy24** [comment]
@charislam should be all set. sorry for the delay - I ran into issues getting up and running locally on windows so just ended up using codespaces

**Pull request merged**
