### PR TITLE
Update supabase.yml

### PR DESCRIPTION
**Pull request by officiallymarky**
Remove references to stored procedures as they are not supported.

### CODE REVIEW

**Comment by soedirgo** [comment]
Reason for closing [here](https://discord.com/channels/839993398554656828/843999948717555735/877851018682064917), but thanks for the PR nonetheless!

**Comment by officiallymarky** [comment]
> Reason for closing [here](https://discord.com/channels/839993398554656828/843999948717555735/877851018682064917), but thanks for the PR nonetheless!

There is a significant difference between Functions and Stored Procedures, they are **not the same thing**.  I wasted hours on this thinking you supported *stored procedures* as your documentation called it stored procedures.

Stored procedures support transactions, functions do not, this can be a big limitation for some.  Either way, your documentation is confusing as a result.

**Comment by steve-chavez** [comment]
> Stored procedures support transactions, functions do not, this can be a big limitation for some.

@officiallymarky Do note that SQL functions called through RPC are already wrapped in a transaction - so you can do a `RAISE EXCEPTION` and the transaction will be rolled back(it will also be rolled back on any error like constraint failures).

**Comment by steve-chavez** [comment]
> There is a significant difference between Functions and Stored Procedures, they are not the same thing and Postgres supports both. 

Before PostgreSQL 11, they used to be the same thing for most postgres users which referred to "functions" as "stored procedures". This is a problem because we'd lose searchability if we were to call them "remote functions"(which is not a commonly used term).

**Comment by steve-chavez** [comment]
I think instead of renaming the term, we could put a note mentioning the above.

**Comment by soedirgo** [comment]
@officiallymarky thanks for the clarification - the docs should be updated now with https://github.com/supabase/supabase/pull/2905

> This is a problem because we'd lose searchability if we were to call them "remote functions".

Agreed, but calling them stored procedures is also problematic since people confuse the with Postgres functions, and there's barely any mention of "stored procedures" in the Postgres docs - we should just do away with "stored procedures" and use functions, procedures, or "routines" for either of them.

> I think instead of renaming the term, we could put a note mentioning the above.

Hmm, I already went ahead with the rename 😅 Feel free to revert them if you prefer

**Comment by soedirgo** [comment]
@officiallymarky thanks for the clarification - the docs should be updated now with https://github.com/supabase/supabase/pull/2905

> This is a problem because we'd lose searchability if we were to call them "remote functions".

Agreed, but calling them stored procedures is also problematic since people confuse the with Postgres functions, and there's barely any mention of "stored procedures" in the Postgres docs - we should just do away with "stored procedures" and use functions, procedures, or "routines" for either of them.

> I think instead of renaming the term, we could put a note mentioning the above.

Hmm, I already went ahead with the rename 😅 Feel free to revert them if you prefer

**Comment by steve-chavez** [comment]
> Hmm, I already went ahead with the rename sweat_smile Feel free to revert them if you prefer

"Postgres functions" is better than "remote functions", LGTM.

**Pull request closed without merging**
