### PR TITLE
docs: update postgress CDC message

### PR DESCRIPTION
**Pull request by IcedTea2K**
## What kind of change does this PR introduce?
According to #21660, the structure of the documented Postgres CDC message is outdated with the current message. This PR updates the docs.

## What is the current behavior?
The main difference is in the **payload**.

The current structure and instructions:
image

## What is the new behavior?

The new structure and updated instructions:
image

### CODE REVIEW

**Comment by IcedTea2K** [comment]
Will need someone to verify on the `topic`, `ids`, `data` part of the message. When a client receives a realtime message, only the content of the `payload` is passed into the callback. There's not much information about the external structure of it, so I kept it the same way. It might also be outdated....

**Comment by IcedTea2K** [comment]
@filipecabaco @charislam are there any updates on this?

**Comment by damien-schneider** [comment]
Why isn't this PR checked as this is just an update of documentation ? 😢

**Comment by filipecabaco** [comment]
sorry we've been really full of work for our special announcement. tomorrow I will tackle this one. really apologize for the delay 🙏

**Comment by filipecabaco** [comment]
I'm getting a prettier format error, could you run prettier on the file?
`npx prettier apps/docs/content/guides/realtime/protocol.mdx`

**Comment by IcedTea2K** [comment]
@filipecabaco should be good now 👍 
```
supabase on  doc_update_cdc_msg via ⬢ v21.6.2
➜ npx prettier apps/docs/content/guides/realtime/protocol.mdx --check
Checking formatting...
All matched files use Prettier code style!
```

**Review by charislam — APPROVED** [review]

**Review by filipecabaco — APPROVED** [review]

**Pull request merged**
