### PR TITLE
Add example for deleting multiple records with delete().in()

### PR DESCRIPTION
**Pull request by sossost**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

docs update

## What is the current behavior?

#25361

## What is the new behavior?

Update delete documentation to include multi-record removal example using delete().in()

## Additional context

image

### CODE REVIEW

**Comment by charislam** [comment]
Thanks @sossost! Would you mind making this a separate example so the expected data/response is clearer?

**Comment by sossost** [comment]
@charislam sure! I'll update the documentation accordingly. Thank you!

**Comment by sossost** [comment]
@charislam Updated additional commits. Did I do it right??

**Review by charislam — APPROVED** [review]

**Comment by charislam** [comment]
Yes @sossost, this is perfect! Thank you!

**Pull request merged**
