### PR TITLE
Fix #1304 , Define the defualt behavior of signUp

### LINKED ISSUE #1304: Show return value for "Confirmation Email Sent" in guide
it's not clear from the [Client Libary Guide](https://supabase.io/docs/guides/client-libraries) that the default behavior of `signUp` when used with the hosted platform is to send an email confirmation,

we should:

1) include this as a note [here](https://supabase.io/docs/guides/client-libraries) 
2) add an example showing the return value when this happens
3) update any auth [examples](https://github.com/supabase/supabase/tree/master/examples) to handle this scenario

there is a debate whether to have email confirmations on or off by default but I believe having them on is more secure, open to opinions however

### PR DESCRIPTION
**Pull request by illuzan**
- Updated auth example to handle this.
- signUp function now gives error if the user is already registered.
- signIn function gives error when invalid email or password is entered.

### CODE REVIEW

**Review by mocktarissa — APPROVED** [review]

**Comment by kiwicopple** [comment]
@awalias can also get your approval on this one?

**Comment by awalias** [comment]
For the example I think we need to check the response itself to know whether a confirmation email has been sent or not. If confirmations are disabled the response will contain an access token and also a confirmed_at value, otherwise it will just contain a confirmation_sent_at attribute.

It should be easy enough to get it to work with both configurations

**Comment by awalias** [comment]
Additionally we should include this info in the docs 👍

**Review by awalias — APPROVED** [review]
thanks for the edits @allstargaurav !

**Pull request merged**
