### PR TITLE
Portuguese translation improvements

### PR DESCRIPTION
**Pull request by jose-donato**
## What kind of change does this PR introduce?

Improves some portuguese translation issues.

## What is the current behavior?

Some non-translated words (in english and spanish)

## What is the new behavior?

Translated those words to portuguese

One question, this translation is currently portuguse-brazilian only. Shouldn't exist an portuguese-portuguese file as well? I can make that translation if so.

### CODE REVIEW

**Comment by kiwicopple** [comment]
> Shouldn't exist an portuguese-portuguese file as well

Yes, it would be great to have fully-localized translations! Do you want to append the file to this PR or create a new one?

**Comment by jose-donato** [comment]
> > Shouldn't exist an portuguese-portuguese file as well
> 
> Yes, it would be great to have fully-localized translations! Do you want to append the file to this PR or create a new one?

Whatever it is more convenient for the project 😁

What should be the name of the files?
README.pt-pt.md 
README.pt-br.md
etc?

**Comment by kiwicopple** [comment]
Yes, those look correct! https://github.com/ladjs/i18n-locales

**Comment by kiwicopple** [comment]
@jose-donato there is a conflict on this one, but if you resolve I can merge 👍

**Pull request merged**
