### PR TITLE
Added an Angular Quickstart.

### LINKED ISSUE #14323: Add an Angular Quickstart
# Improve documentation

## Describe the problem

There is no Angular Quickstart.

## Describe the improvement

add an Angular Quickstart just like the [React Quickstart](https://supabase.com/docs/guides/getting-started/quickstarts/reactjs)

### PR DESCRIPTION
**Pull request by jobayer12**
## What kind of change does this PR introduce?

Added an Angular Quickstart #14323 

## What is the current behavior?

Please link any relevant issues here.

## Additional context

Add any other context or screenshots.
Screenshot 2023-05-13 at 4 41 53 PM

Closes https://github.com/supabase/supabase/issues/14323

### CODE REVIEW

**Review by dshukertjr — COMMENTED** [review]
@jobayer12 Thanks for this, and sorry for the delay for reviewing it. This is awesome! Would you be able to take the merge conflict?

**Comment by awalias** [comment]
running this quickstart gives:

```bash
lar/platform-server/fesm2022/platform-server.mjs:17109:26) {
  code: 907
}
3:02:45 PM [vite] Internal server error: NG0907: The _AppComponent component is not marked as standalone, but Angular expects to have a standalone component here. Please make sure the _AppComponent component has the `standalone: true` flag in the decorator.
      at assertStandaloneComponentType (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/@angular/core/fesm2022/core.mjs:11504:1)
      at internalCreateApplication (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/@angular/core/fesm2022/core.mjs:31335:5)
      at Module.bootstrapApplication (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs:1053:8)
      at bootstrap (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/src/main.server.ts:7:16)
      at eval (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/@angular/platform-server/fesm2022/platform-server.mjs:17111:1)
      at Generator.next (<anonymous>)
      at eval (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/chunk-OGTRFHQR.mjs:83:61)
      at ZoneAwarePromise (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
      at Module.__async (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/chunk-OGTRFHQR.mjs:67:10)
      at renderApplication (/Users/supabase/Documents/projects/my-app/.angular/vite-root/my-app/node_modules/@angular/platform-server/fesm2022/platform-server.mjs:17109:26)
```

when you try to run the app

**Comment by awalias** [comment]
fixed the previous issue now getting:

```bash
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ul' (used in the '_AppComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ul' (used in the '_AppComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ul' (used in the '_AppComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ul' (used in the '_AppComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.
```

**Comment by awalias** [comment]
tried to fix with this: https://stackoverflow.com/a/39058082

but now the page just hangs when I try to open in the browser

@jobayer12 if you know how to fix then we can get this one merged 👍

**Review by awalias — CHANGES_REQUESTED** [review]
example currently doesn't function

**Comment by awalias** [comment]
closing as stale for now - feel free to reopen as needed

**Pull request closed without merging**
