### PR TITLE
chore(ci): avoid typos

### PR DESCRIPTION
**Pull request by stavares843**
## What kind of change does this PR introduce?

CI to avoid typos. 

## What is the current behavior?

Atm typos are getting merged, and with this PR we can have review dog adding them as annotations.

## What is the new behavior?

If there are typos in the PR, a annotation will appear with that typo warning

Captura de ecrã 2022-12-30, às 22 25 52

## Additional context

Similar to https://github.com/supabase/supabase/pull/9947 but for typos.

### CODE REVIEW

**Comment by dannykng** [comment]
Thanks @stavares843! Apologies for the delay.

@pucho @sweatybridge mind reviewing this one? Seems like it'd be very useful! 🙏🏼

**Review by sweatybridge — APPROVED** [review]
Nice

**Comment by dannykng** [comment]
This might not be working correctly for contributions from forks. 

https://github.com/supabase/supabase/pull/11986 ([job](https://github.com/supabase/supabase/actions/runs/4027712822/jobs/6925972288)) is failing with this error:
```
reviewdog: This GitHub token doesn't have write permission of Review API [1], 
so reviewdog will report results via logging command [2] and create annotations similar to
github-pr-check reporter as a fallback.
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target, 
[2]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
```

https://github.com/supabase/supabase/pull/11989 ([job](https://github.com/supabase/supabase/actions/runs/4028053580/jobs/6926306172)) is failing with this error:
```
/home/runner/work/_actions/reviewdog/action-suggester/v1/script.sh: 15: reviewdog: not found
```

**Comment by stavares843** [comment]
Yes, due to be a forked repo 😅 

i can try adding this

```+    permissions:
+      contents: read
+      pull-requests: write ``` 



to see if works

based in https://github.com/reviewdog/action-eslint/issues/148#issuecomment-1282861097

what do you think?

**Comment by dannykng** [comment]
@stavares843 let's try it!

**Comment by stavares843** [comment]
gonna update 🔨

**Comment by stavares843** [comment]
https://github.com/supabase/supabase/pull/11991

**Comment by dannykng** [comment]
Seems to be working now! 🤷🏼

**Comment by stavares843** [comment]
🎉

**Pull request merged**
