### PR TITLE
Added Nuxt guide to project homepage.

### PR DESCRIPTION
**Pull request by alt-glitch**
## What kind of change does this PR introduce?
Add NuxtJS guide on project homepage.
As discussed here: https://github.com/orgs/supabase/discussions/17902

## What is the new behavior?
image

### CODE REVIEW

**Review by jordienr — APPROVED** [review]
Great!

**Comment by alt-glitch** [comment]
Hey @jordienr
I forgot to run prettier, sorry.

Pushed now

**Comment by jordienr** [comment]
> Hey @jordienr I forgot to run prettier, sorry.
> 
> Pushed now

Looks like the prettier check is still failing, my guess is your workspace is not using the repos prettier config. Can you check? 

for reference here's how I have it set up in VSCode settings:

CleanShot 2024-01-11 at 13 05 35@2x

**Comment by alt-glitch** [comment]
Hey @jordienr 
Thanks for being patient with me on this. I do have `prettier` installed and the correct configuration file. 
image

However because I'm unable to set up my local dev environment (https://github.com/supabase/supabase/issues/20370), I think it doesn't seem to be formatting properly.

(eyeballing it, I can see that I just need to remove the trailing new line. let me know if you want me to just go ahead and push that :))

**Comment by jordienr** [comment]
@alt-glitch No worries, and yep you can fix it manually, as long as the prettier check passes we're good! I'll take a look at your issue with the local dev environment set up.

**Pull request merged**
