### PR TITLE
New logo concepts

### PR DESCRIPTION
**Pull request by royquilor**
## What kind of change does this PR introduce?

New logo concepts relating to #194 

## Additional context

Part of Hacktoberfest 2020 event.

logo-concepts

I just put the image in a design folder

### CODE REVIEW

**Comment by royquilor** [comment]
@kiwicopple thanks for your feedback, I gave the circle the same thickness as the S. If you decide to go with it, I can also provide SVG's.

**Comment by kiwicopple** [comment]
Thanks @royquilor  - I added a hacktoberfest label (in case you're participating).

Thanks for the awesome work here - I'll loop back in a few days

**Comment by 0xflotus** [comment]
grafik
grafik


This reminds me on the Simson logo or Trabant logo. 

I like it.

**Comment by royquilor** [comment]
> grafik
> grafik
> 
> This reminds me on the Simson logo or Trabant logo.
> 
> I like it.

Trabant looks awesome. Timeless logo

**Pull request closed without merging**
