### PR TITLE
fix: allow and suggest trying again on JWT secret update failure

### PR DESCRIPTION
**Pull request by thebengeu**
Manually triggering a JWT secret update job seemed to work for previous failures, so we should allow users to do that themselves.
Screenshot 2022-03-22 at 11 30 11

### CODE REVIEW

**Review by darora — COMMENTED** [review]
In principle I agree with this change, but am not the best person to review the implementation of it

**Comment by thebengeu** [comment]
Yeah, just added you to confirm that this change is safe, i.e. there's no further harm in trying to update the JWT secret again when in a failure state.

**Comment by kiwicopple** [comment]
lgtm

from a visual pov it would be nice to put the warning above the "Generate a new JWT secret" panel. Currently it's a panel within a panel within a panel

**Review by joshenlim — APPROVED** [review]
yeap lgtm!

**Pull request merged**
