### PR TITLE
feat: Replace hubspot api call with forms api

### PR DESCRIPTION
**Pull request by dshukertjr**
## What kind of change does this PR introduce?

HubSpot has a [handy API](https://legacydocs.hubspot.com/docs/methods/forms/submit_form) that will take care of upserting a contact and attaching a note (like timeline object) to it. This PR replaces the create or update contact call along with the subsequent api calls to create notes and create deals. With this update, deals will no longer be created via API, but will created from HubSpot's workflow tool instead. 

## What is the current behavior?

Using combination of HubSpot APIs. 

## What is the new behavior?

Using the following API to take care of creation of a contact along with creating a note (form submission object to be precice).
https://legacydocs.hubspot.com/docs/methods/forms/submit_form

## Other context

This function is currently the deployed version.

### CODE REVIEW

**Review by alaister — APPROVED** [review]
+71 −157 love to see it!

**Review by kiwicopple — APPROVED** [review]
looks great @dshukertjr - might need to run prettier on it FYI (we don't use semi-colons)

**Comment by dshukertjr** [comment]
@kiwicopple Sorry for that. Fixed now!

**Comment by kiwicopple** [comment]
feel free to merge whenever you're ready @dshukertjr

**Pull request merged**
