### PR TITLE
Update social links in www footer

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Updates social links in `www` footer to match the social links in the `docs`.

## What is the current behavior?

CleanShot 2023-06-23 at 14 27 44

## What is the new behavior?

CleanShot 2023-06-23 at 14 27 00

### CODE REVIEW

**Review by gregnr — APPROVED** [review]
Are these copy-pasta? Worth abstracting to a common package? (not blocking this PR)

**Comment by Isaiah-Hamilton** [comment]
> Are these copy-pasta? Worth abstracting to a common package? (not blocking this PR)

Yeah its a copy-pasta, but I don't think this will get changed enough to be moved to a common package.

**Comment by MildTomato** [comment]
Feel a bit bad saying this, but I preferred it the old way.

The icons also lined up with the logo.

**Comment by Isaiah-Hamilton** [comment]
> Feel a bit bad saying this, but I preferred it the old way.

No worries didn't take long to throw together. Designer should have final say anyways.

**Pull request closed without merging**
