### PR TITLE
fix: studio logs no results styling

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Studio Logs Explorer

## What is the current behavior?

When you go into the logs explorer and you get no results you see the following:
Screenshot 2022-09-26 at 17 12 20

## What is the new behavior?
Screenshot 2022-09-26 at 17 12 15

- Frown icon moved and changed colour to suit the users theme
- `x` icon colour changed to suit uses theme
- reduced the gap size

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by saltcod** [comment]
Hey @Hallidayo — here's how this looks for me for some reason: 

CleanShot 2022-09-26 at 16 07 46@2x


I think we'll keep this mostly as it is, as it's used in a few places. To fix the frown icon colour — looks like the issue is that svg is set to stroke="currentColor".   Since its parent doesn't have a colour set, it doesn't inherit one. 

Adding a colour to its parent div will fix that: 
`<div className="absolute right-1 -bottom-4 text-scale-1200">`

**Comment by Ziinc** [comment]
the smiley face is actually supposed to be off-center. the x is also supposed to be overlapping on the log lines

**Comment by saltcod** [comment]
@Hallidayo thanks for that. Looks good now!  If you could fix that merge conflict, I'm happy to merge this. Thank you!

**Comment by pucho** [comment]
@Hallidayo Let us know if it's possible to fix that merge conflict so we can merge this in. Thanks!

**Comment by Hallidayo** [comment]
Hi @pucho, I think this  has been sorted/fixed now as when I go to the logs and recreate the svgs change based of theme colour.

shall I close it off?

**Comment by pucho** [comment]
> Hi @pucho, I think this has been sorted/fixed now as when I go to the logs and recreate the svgs change based of theme colour.
> 
> shall I close it off?

I just checked, yes, close if off. Thank you!

**Pull request closed without merging**
