### PR TITLE
docs: fix 404 errors in multilingual README files by updating relative links

### PR DESCRIPTION
**Pull request by ghost**
## What kind of change does this PR introduce?

Documentation update.

## What is the current behavior?

The current README files in multiple languages contain links to the DEVELOPERS.md file with incorrect relative paths. Because of these wrong paths, some links are leading to a 404 page.

## What is the new behavior?

This PR updates the paths to absolute paths. Now, multilingual README files should correctly link to the DEVELOPERS.md file.

## Additional context

All README files were using relative paths to link to the DEVELOPERS.md file. Some of these were correct, but others were not due to different file hierarchies. Changing all relative paths to absolute paths ensures that they will work regardless of the file structure. Additionally, it provides a consistent approach across all README files.

### CODE REVIEW

**Review by Isaiah-Hamilton — CHANGES_REQUESTED** [review]
Can the links to be updated to `../DEVELOPERS.md`

**Comment by takpen** [comment]
Thank you for the suggestion. I will work on updating the links to "../DEVELOPERS.md" as requested.

**Review by Isaiah-Hamilton — APPROVED** [review]
lgtm

**Comment by takpen** [comment]
I have made the changes based on your suggestion. Could you please have another look at the update?

**Pull request merged**
