### PR TITLE
Hybrid RLS Assistant

### PR DESCRIPTION
**Pull request by joshenlim**
This change aims to streamline the existing RLS policy user flow by
- Not hiding templates on a separate "step"
- Showing the SQL that will be triggered from creating/updating RLS policies

Eventually we'll plan to see how we can integrate the AI assistant into this workflow as well

Before:
image

After:
image

### CODE REVIEW

**Review by alaister — COMMENTED** [review]
Small one but this dropdown looks a little busted in both dark and light mode:

Screenshot 2024-03-25 at 10 56 37

**Comment by joshenlim** [comment]
> Small one but this dropdown looks a little busted in both dark and light mode:

@alaister i'll probably fix this in another PR - this component needs fixing in general, but is used in several places
it's functionality is okay though right?

**Review by alaister — APPROVED** [review]
LGTM!

**Review by alaister — APPROVED** [review]
Double approved!

**Pull request merged**
