### PR TITLE
fix: support page to be mobile responsive

### PR DESCRIPTION
**Pull request by kevinseo16**
## What kind of change does this PR introduce?

Changes `https://supabase.com/dashboard/support/new` to be mobile responsive.

## What is the current behavior?

`https://supabase.com/dashboard/support/new` page is not mobile responsive

image

## What is the new behavior?
image

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by J0** [comment]
Hey @hgseo16 any chance we could trouble you to run `prettier` on this one? 

`prettier apps/studio/components/interfaces/Support/SupportForm.tsx --write` and similar for other files. I've reached out to frontend team to see if they can review when free

Thanks!

**Comment by hgseo16** [comment]
@J0 sorry about that. My editor's `format on save` function was acting buggy with the new prettier upgrade from last week. Hopefully, the newest commit would solve the issue.

**Comment by joshenlim** [comment]
@hgseo16 thanks so much for this! all these contributions definitely help improve the UX of the dashboard and we really appreciate it :) 🙏

**Review by joshenlim — APPROVED** [review]

**Comment by hgseo16** [comment]
@joshenlim the pleasure is all mine! Please let me know if there are issues I can contribute to!

**Pull request merged**
