### PR TITLE
fix: Changed logo path to svg in nav and footer

### PR DESCRIPTION
**Pull request by karan316**
## What kind of change does this PR introduce?
Changes the file path of the logo to SVG

## What is the current behavior?
The nav and footer have PNG logos
[Linked Issue](https://github.com/supabase/supabase/issues/2943)

## What is the new behavior?
The logo path has been changed to point to the SVG logos

### CODE REVIEW

**Review by kiwicopple — CHANGES_REQUESTED** [review]
Hey @karan316 - this looks great but would you also be able to copy the files from "brand-assets" to `/images/`?

Don't remove "brand-assets" - we just want to make sure we don't break the site if we decide to move the brand assets folder in the future

**Comment by karan316** [comment]
> Hey @karan316 - this looks great but would you also be able to copy the files from "brand-assets" to `/images/`?
> 
> Don't remove "brand-assets" - we just want to make sure we don't break the site if we decide to move the brand assets folder in the future

Okay! That's done.

**Comment by karan316** [comment]
> Hey @karan316 - this looks great but would you also be able to copy the files from "brand-assets" to `/images/`?
> 
> Don't remove "brand-assets" - we just want to make sure we don't break the site if we decide to move the brand assets folder in the future

Okay! That's done.

**Comment by karan316** [comment]
Hey @kiwicopple, I've copied the files to images as mentioned. Please check if its okay 😃

**Review by kiwicopple — APPROVED** [review]
looks good! thanks for your contribution

**Pull request merged**
