### PR TITLE
Fix/update other project links

### PR DESCRIPTION
**Pull request by aminamos**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Some example project links are out of date and lead to a 404. In one case (Vue) this breaks the "deploy with Vercel" button.

## What is the new behavior?

Links have been updated to their current locations.

### CODE REVIEW

**Comment by aminamos** [comment]
This builds on https://github.com/supabase/supabase/pull/6730

**Comment by MildTomato** [comment]
Wait for #6733 to merge first. looks like same files being modified

**Comment by MildTomato** [comment]
@aminamos 
you may need to merge `master` into this branch, might be behind

**Comment by aminamos** [comment]
@MildTomato merged, thank you!

**Review by kiwicopple — APPROVED** [review]
you're a legend @aminamos , thank you!

**Pull request merged**
