### PR TITLE
Correction for "Migrating and Upgrading Projects" storage script

### PR DESCRIPTION
**Pull request by ojasaklechayt**
Correction for "Migrating and Upgrading Projects" storage script

## What kind of change does this PR introduce?
docs update
Bug fix, feature, docs update, ...

## What is the current behavior?
db { } not there

Please link any relevant issues here.
#13794 

## What is the new behavior?
db { } added

Feel free to include screenshots if it includes visual changes.
image

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@tourbillonlabs @soedirgo @sweatybridge can you please check my pr ?

**Review by gregnr — APPROVED** [review]
Thanks for fixing this one @ojasaklechayt

**Comment by ojasaklechayt** [comment]
@gregnr seems like " supabase-studio-staging  " testing is failing.

**Comment by ojasaklechayt** [comment]
I have done some minor changes too

**Comment by gregnr** [comment]
> seems like " supabase-studio-staging " and some other testings is failing.

Yeah something is up with our CI right now - stay tuned.

> I have done some minor changes too

Actually we typically keep the trailing comma here - for consistency, would you mind adding back? Thanks!

**Comment by ojasaklechayt** [comment]
> > seems like " supabase-studio-staging " and some other testings is failing.
> 
> Yeah something is up with our CI right now - stay tuned.
> 
> > I have done some minor changes too
> 
> Actually we typically keep the trailing comma here - for consistency, would you mind adding back? Thanks!

okay

**Comment by ojasaklechayt** [comment]
> > seems like " supabase-studio-staging " and some other testings is failing.
> 
> Yeah something is up with our CI right now - stay tuned.
> 
> > I have done some minor changes too
> 
> Actually we typically keep the trailing comma here - for consistency, would you mind adding back? Thanks!

Done

**Comment by ojasaklechayt** [comment]
@gregnr it need 2 workflows approval.

**Pull request merged**
