### PR TITLE
Add Ethereum Settings

### PR DESCRIPTION
**Pull request by HarryET**
## What kind of change does this PR introduce?

Settings for Ethereum Support, see PR: https://github.com/supabase/gotrue/pull/282

## What is the current behavior?

No Ethereum Settings in Studio

## What is the new behavior?
Adds new Ethereum Settings pannel

## Additional context

- Haven't had the ability to get it running locally so I am not 100% sure its working, some help getting setup would be cool or if someone else could validate its working?

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @HarryET - I think it's important to confirm the design of the gotrue PR before we can make any commits here. web3 logins are (potentially) a fundamental change to the auth design. building things fast is important, but building things right is critical. 

perhaps the best next step is to add a design doc to our RFC repo? We'd need to understand the design which you've implemented, any other designs you considered, why you chose the approach you did etc.

If you're happy with that, let's close this until we confirm on the RFC (after Launch Week 😄 )

**Comment by HarryET** [comment]
> Hey @HarryET - I think it's important to confirm the design of the gotrue PR before we can make any commits here. web3 logins are (potentially) a fundamental change to the auth design. building things fast is important, but building things right is critical. 
> 
> perhaps the best next step is to add a design doc to our RFC repo? We'd need to understand the design which you've implemented, any other designs you considered, why you chose the approach you did etc.
> 
> If you're happy with that, let's close this until we confirm on the RFC (after Launch Week 😄 )

Hey @kiwicopple, I could set this PR as a draft and change it as it goes. I have been working with @kangmingtay in the GoTrue PR so not sure an RFC is fully needed - unless you think otherwise? There is a diagram there as well as explanations

**Comment by kiwicopple** [comment]
> not sure an RFC is fully needed - unless you think otherwise

I definitely think so! 

> There is a diagram there as well as explanations

The key part of an RFC would be to document down which designs you _didn't_ implement, and why.
Some things off the top of my head:

- I know some Auth providers only allow "normal" logins, and then the account acts as a "custodian" for various web3 wallets. Is this how it works? If not, would this be possible with the current design?
- Will it be a single eth address per account? Will there be a way to associate accounts?
- Does the design work with many web3 providers? Only Metamask? 
- Is it extensible? What are the limitations? Any problems we will face in the future?

We aren't a team of web3 experts (and I assume you might not be either 😛), so we should make sure we aren't shooting ourselves in the foot with the current design - possibly even share with some of the web3 communities to make sure we're compatible

**Comment by kiwicopple** [comment]
Hey @HarryET - we're doing a big cleanup this week, so I'm going to close this until we're ready to merge. Hope that's OK!

**Pull request closed without merging**
