### PR TITLE
Add `✏ Edit this page` links to doc pages

### PR DESCRIPTION
**Pull request by sa3dany**
This pull request make a single change to Docusaurus config to enable the `Edit this page` links at the end of **all pages** in the docs site. I think this reduces friction and makes it easy for contributors to make changes on the spot easily through pull requests.

From this [pull](https://github.com/supabase/supabase/pull/429) it appears you are auto generating some parts of the docs though 🤔. I am not familiar enough with Docusaurus or how you generate the docs at this time but, could we somehow mark the auto-generated parts inside source files to warn contributors?

## Additional context

See: [https://v2.docusaurus.io/docs/migration/manual/#customdocspath-docsurl-editurl-enableupdateby-enableupdatetime](https://v2.docusaurus.io/docs/migration/manual/#customdocspath-docsurl-editurl-enableupdateby-enableupdatetime)

image

### CODE REVIEW

**Comment by kiwicopple** [comment]
Nice one @sa3dany - Yeah we generate all of the items in the "Docs" sections from `yaml` files.


Perhaps we can add some Markdown comments to the [Page generator](https://github.com/supabase/supabase/blob/master/web/spec/gen/components/Page.ts)

Ideally we would show the input file in the comments - if you're really feeling up to it, then you would inject the `inputFileName` here: https://github.com/supabase/supabase/blob/dd2eebdd804d7c7e7d86507f3898fad271c8947d/web/ReferenceGenerator.ts#L70

You could then use the filename in the comment to direct user to the relevant file in the repo

**Comment by sa3dany** [comment]
Thank you @kiwicopple for the pointers. Luckily I landed upon this [pull request](https://github.com/facebook/docusaurus/pull/2166) and discovered that we can customize a page's edit URL using front matter, specifically the `custom_edit_url` variable.

So no need for any comments inside markdown as we now link directly to the `yaml` file for auto-generated pages 👍

**Comment by kiwicopple** [comment]
woah nice. Docusaurus is impressive.

the input file string doesn't need the path stripped right? Could you gen up some pages just to make sure they are coming out OK? (perhaps `npm run gen:realtime`)

**Comment by sa3dany** [comment]
I tested it earlier with `gen:supabase` and it came out ok. I did run `gen:realtime` now and got correct edit URLs for both the index and other pages.
```mdx
---
id: index
title: "Realtime Client"
slug: realtime-client
custom_edit_url: https://github.com/supabase/supabase/edit/master/web/spec/realtime.yml
---
```

**Comment by kiwicopple** [comment]
Legend. Great PR thanks @sa3dany

**Pull request merged**
