### PR TITLE
feat: add Cloudflare Turnstile to LW ticket page.

### PR DESCRIPTION
**Pull request by thorwebdev**
TODOS:

- [x] Switch to prod turnstile creds

### CODE REVIEW

**Comment by MildTomato** [comment]
getting a 403 in the vercel preview
Screenshot 2022-12-12 at 2 46 44 PM
Screenshot 2022-12-12 at 2 46 04 PM

**Comment by thorwebdev** [comment]
@MildTomato you will need to use the https://zone-www-dot-rfckwxwah-supabase.vercel.app/launch-week url instead. that's the only domain whitelisted for testing.

**Comment by MildTomato** [comment]
ah no. does turnstile not support wildcard urls?

**Comment by thorwebdev** [comment]
Unfortunately it doesn't look like it does. Will check with the CF team.

**Comment by thorwebdev** [comment]
Holding off on this until Cloudflare supports domain wildcards/vercel preview domains.

**Comment by MildTomato** [comment]
closing temporarily (😢)

**Pull request closed without merging**
