### PR TITLE
Add docs for Estuary integration

### PR DESCRIPTION
**Pull request by oliviamiannone**
## What kind of change does this PR introduce?

Adds documentation for integrating [Estuary](https://github.com/estuary) with Supabase. This is part of a pending request from Estuary to join the Supabase partner program.

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by dannykng** [comment]
Hey @oliviamiannone, thanks for your contribution! We've just migrated our docs from Docusaurus to NextJS (but we still have some directories to clean up). Apologies for the inconvenience, but would you mind porting these changes to `/apps/docs` instead of `/apps/reference`? 

- `apps/reference/docs/guides/integrations/estuary.mdx` -> [apps/docs/docs/guides/integrations/estuary.mdx](https://github.com/supabase/supabase/tree/master/apps/docs/docs/guides/integrations)
- `apps/reference/nav/_referenceSidebars.js` -> [apps/docs/components/Navigation/Navigation.constants.ts](https://github.com/supabase/supabase/blob/master/apps/docs/components/Navigation/Navigation.constants.ts#L294-L302)

Let us know if you have any questions! Thanks and apologies in advance!

**Comment by oliviamiannone** [comment]
@dannykng No problem, thanks for clarifying that! Should be fixed now; let me know if there are any other edits or changes you need from me.

**Comment by dannykng** [comment]
Thanks @oliviamiannone! Our devrel team will reach out to you shortly on your partner program application.

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks 💚

**Review by awalias — APPROVED** [review]

**Pull request merged**
