### PR TITLE
Added Dart docs in reference

### PR DESCRIPTION
**Pull request by dshukertjr**
## What kind of change does this PR introduce?

Added Dart docs in reference. Auth, Data, Storage, Modifier, and Filter methods are added.

## What is the current behavior?

There are no Dart docs. 

## What is the new behavior?

Sidebar of reference will have a Dart section where users can view Auth, Data, Storage, Modifier, and Filter docs.

### CODE REVIEW

**Comment by dshukertjr** [comment]
I'm able to run this locally, but what seems to be the error on Vercel here?

**Comment by kiwicopple** [comment]
I'm seeing this error in Vercel @dshukertjr :

image


I'll check again later tonight on my local machine 👍

**Comment by dshukertjr** [comment]
@kiwicopple 
Ah, thanks! This is really helpful. I will try to see if I can replicate it and fix it!

**Comment by dshukertjr** [comment]
@kiwicopple 
I do see the error now that I tried building it with a freshly cloned repo. I will fix this issue and get back with this one!

**Comment by dshukertjr** [comment]
@kiwicopple 
It should be good now!

**Comment by kiwicopple** [comment]
image

Interesting that there is a `stream()` and a `subscribe()`.  Should we put them both into the "Realtime" section?

As far as I can tell, they do the same thing except that stream fetches the data as well? Is there any reason why the functions are separate? I would have thought that it could be cleaner (DX) to just use `subscribe()` and then just add a `{ fetch: true }` or something similar to the function params/options

**Comment by dshukertjr** [comment]
@kiwicopple 
>Interesting that there is a stream() and a subscribe(). Should we put them both into the "Realtime" section?

That makes sense. I will put it under `Realtime` section!

>just use subscribe() and then just add a { fetch: true } or something similar to the function params/options

That is brilliant! I really like that direction. Maybe in the future `stream()` can be an option within realtime. 
Yeah, the implementation might not have been the best for `stream()` method, but it is actually doing a bit more than just standard realtime functionality. It's combining the initially fetched data and incoming realtime data into one array end emit it as a `Stream` (kind of like observables in js). Being able to receive data as `Stream` had been a huge ask from the community.

**Pull request merged**
