### PR TITLE
feat: implement google analytics 4

### PR DESCRIPTION
**Pull request by phamhieu**
## What kind of change does this PR introduce?

```
https://developers.google.com/analytics/devguides/collection/protocol/ga4
Geographic information is only available via automatic collection from gtag, Google Tag Manager, 
or Google Analytics for Firebase.
```

Support server side analytics with geographic information

- on initial, ga4 will generate a `client_id`. We will send this `client_id` as headers for every request to api server.
  - page view tracking on client is disable as default
  - `client_id` is saved to local storage. It can be used by docs,... when sending page event
- new params for event request: `language`, `screen_resolution `

## TODO

- [ ] create Vercel env for staging + prod
- [ ] update local env template

### CODE REVIEW

**Comment by phamhieu** [comment]
The unit test failed. But the error is not related to my code.

```
studio:test:     console.error
studio:test:       Warning: Each child in a list should have a unique "key" prop.
studio:test:       
studio:test:       Check the render method of `HeaderRow`. See https://reactjs.org/link/warning-keys for more information.
studio:test:           at HeaderCell (/home/runner/work/supabase/supabase/node_modules/@supabase/react-data-grid/src/HeaderCell.tsx:42:3)
studio:test:           at HeaderRow (/home/runner/work/supabase/supabase/node_modules/@supabase/react-data-grid/src/HeaderRow.tsx:50:3)
studio:test:           at div
studio:test:           at DataGrid (/home/runner/work/supabase/supabase/node_modules/@supabase/react-data-grid/src/DataGrid.tsx:179:14)
```

**Comment by MildTomato** [comment]
>create Vercel env for staging + prod

@phamhieu we already have studio running vercel previews for staging. 
Screenshot 2023-02-06 at 11 18 44 AM

**Comment by MildTomato** [comment]
>The unit test failed. But the error is not related to my code.

looks like a lot of `window` errors. that screenshot just shows a warning 👀

**Comment by joshenlim** [comment]
@phamhieu this should be the error from the unit tests that is failing
image

**Review by kiwicopple — APPROVED** [review]

**Pull request merged**
