### PR TITLE
fix: column primary key toggling errors

### LINKED ISSUE #13651: Error when edit column with name containing upper case character
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a table named `products` and has a column named `productId`. I can still retrieve data with this column name. However, when I tried to make this column to be primary key, I got an error message saying that `productid of relation products does not exist`. Actually my column name is `productId`, not `productid`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Precondition:
Create a table with a column contains name with an upper case letter
1. Go to table
2. Click on edit column
3. Make this column to be primary key

## Expected behavior
The field should be set as primary field. (I tried on another table with _id and id then I do the same for id, it works)

## Screenshots
Video

https://user-images.githubusercontent.com/43868345/231496970-87042043-03a4-454a-9394-35bc77153fdd.mov

## Workaround
I tried renaming the column and it works

https://user-images.githubusercontent.com/43868345/231498537-3ada8426-01ad-49e7-9631-98d1cc120b3b.mov

## System information

- OS: macOS
- Browser (if applies) Edge
- Version of supabase-js: Dashboard
- Version of Node.js: Dashboard

## Additional context
Dashboard

### PR DESCRIPTION
**Pull request by gitstart**
## What kind of change does this PR introduce?

Fixes https://github.com/supabase/supabase/issues/13651

## What is the current behavior?

Error when edit column with name containing upper case character

## What is the new behavior?

Toggling primary key config for columns works without any errors

## Steps to test

Create a table with a column contains name with an upper case letter

- Go to table
- Click on edit column
- Toggle primary key config for this column
- Make sure all actions are done without any errors

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@joshenlim Could you help to review this PR?

**Comment by saltcod** [comment]
Hey all!

Had a look at this, seems to be failing on creating a new table.  Renaming a column works great, but new columns get double quotes here:
`primaryKeyColumns: "id"",""test"",""test_AA"`

CleanShot 2023-04-17 at 16 45 54@2x

**Comment by gitstart** [comment]
@saltcod Thanks for checking this. I updated PR with the fixes. Could you take a look again?

https://www.loom.com/share/88ab6f6967ef4d08b8d2985bcda7ef3a

**Comment by saltcod** [comment]
Thanks @gitstart!   Looks great 

— 

Testing notes:
 
**From Table Editor:** 
— create table, with lowercase column name
	— change column name to uppercase 
— add new column, lower case
	— change column name to uppercase 
— add new column, uppercase
	— change column name to lowercase 


**From database/tables:**
— create table, with lowercase column name
	— change column name to uppercase 
— add new column, lowercase
	— change column name to uppercase 
— add new column, uppercase
	— change column name to lowercase

**Review by saltcod — APPROVED** [review]

**Pull request merged**
