### PR TITLE
📝  Update pg_cron documentation with examples for calling function

### PR DESCRIPTION
**Pull request by thibault-chausson**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Documentation update for the pg_cron extension.

## What is the current behavior?

When we use CALL to call a function, an error occurs. 

| jobid | runid | job_pid | database  | username | command                    | status | return_message                                                                                                  | start_time                    | end_time                      |
|-------|-------|---------|-----------|----------|----------------------------|--------|---------------------------------------------------------------------------------------------------------------|-------------------------------|-------------------------------|
| 1     | 1     | 731000  | postgres  | postgres | CALL reset_user_quotas()   | failed | ERROR:  reset_user_quotas() is not a procedure\nLINE 1: CALL reset_user_quotas()\n             ^\nHINT:  To call a function, use SELECT.\n | 2024-05-08 03:30:00.15997+00 | 2024-05-08 03:30:00.164664+00 |

## What is the new behavior?

| jobid | runid | job_pid | database  | username | command                    | status    | return_message                                                                                                  | start_time                    | end_time                      |
|-------|-------|---------|-----------|----------|----------------------------|-----------|---------------------------------------------------------------------------------------------------------------|-------------------------------|-------------------------------|
| 1     | 1     | 731000  | postgres  | postgres | CALL reset_user_quotas()   | failed    | ERROR:  reset_user_quotas() is not a procedure\nLINE 1: CALL reset_user_quotas()\n             ^\nHINT:  To call a function, use SELECT.\n | 2024-05-08 03:30:00.15997+00  | 2024-05-08 03:30:00.164664+00 |
| 1     | 2     | 736555  | postgres  | postgres | SELECT reset_user_quotas() | succeeded | 1 row                                                                                                         | 2024-05-09 03:30:00.086112+00 | 2024-05-09 03:30:00.092458+00 |

## Additional context

To assist other users, I have updated the documentation to use `SELECT` to call a function, and `CALL` for a stored procedure.

Additionally, I specified that the `cron.schedule()` function can be used to modify a cron : [pg_cron documentation](https://github.com/citusdata/pg_cron).

### CODE REVIEW

**Review by charislam — APPROVED** [review]
Thanks @thibault-chausson!

**Comment by thibault-chausson** [comment]
You're welcome @charislam! 
I'm sorry I updated my branch, but I didn't think Vercel authorized a particular commit.
Sorry again!

**Review by charislam — APPROVED** [review]

**Comment by charislam** [comment]
No problem @thibault-chausson! For the future, it's best not to push to the branch after approval (unless of course you want to make more changes 😄), otherwise we have to reapprove the Vercel checks.

But it's a very minor problem, so don't worry about it! We appreciate your help!

**Comment by thibault-chausson** [comment]
Thanks for these explanations!

**Comment by charislam** [comment]
Ahh, that's the main supabase.com website. That failure looks like a fluke, I just reran the check and hopefully this will merge 🤞🏼

**Pull request merged**
