### PR TITLE
Fix: text link width

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Fixes the width of the `TextLink` component.

### CODE REVIEW

**Review by fsansalvadore — COMMENTED** [review]
does this fix some specific example?

**Comment by Isaiah-Hamilton** [comment]
> does this fix some specific example?

This doesn't fix anything specific.

**Comment by gregnr** [comment]
@Isaiah-Hamilton I think @fsansalvadore is asking for an example link or screenshot to help test/review this change (one of the noticeable places you mentioned)

**Comment by Isaiah-Hamilton** [comment]
> @Isaiah-Hamilton I think @fsansalvadore is asking for an example link or screenshot to help test/review this change (one of the noticeable places you mentioned)

Sorry for it being so blurry

CleanShot 2023-06-21 at 17 51 41
CleanShot 2023-06-21 at 17 52 30

**Comment by Isaiah-Hamilton** [comment]
> Oh I see what you mean @Isaiah-Hamilton
> 
> I saw that it doesn't fix the specific case you mentioned because there's a duplicate component in `apps/www/components/TextLink.tsx` which is being used in www.
> 
> You could safely remove the one in www/components and update all imports to point to the one in the `ui` package. Or apply the same fix to the one in www/components, up to you.

@fsansalvadore I updated the all imports to use the ui package.

**Comment by awalias** [comment]
closing as stale, feel free to reopen as needed

**Pull request closed without merging**
