### PR TITLE
feat(schema visualizer): legends for null, unique, identity & update

### PR DESCRIPTION
**Pull request by adiologydev**
## What kind of change does this PR introduce?

This PR introduces icons/legends to denote the constraint per column of a table in the schema visualizer.

## What is the current behavior?

image
Currently only includes a primary key denoted by a border-left.

## What is the new behavior?

- Layout has been updated to account for space for the icons on the left, this should probably be a toggle in a schema visualizer control options (suggested feature).
- Primary keys are now marked by the key used everywhere else in the studio.
- Null columns have an empty diamond.
- Not null columns have a filled diamond based on `currentColor` (so it works in both light and dark mode).
- Unique columns have a fingerprint icon, this probably needs to be changed to whatever you find relevant.
- Not updatable fields are denoted by a lock icon.

image

## Additional context

Foreign key data is not present in the column property itself, if someone can suggest for a good way to get that data, please let me know and I'll add an icon for it as well.

These legends were suggested by @kamilogorek in his PR https://github.com/supabase/supabase/pull/15739

These icons are an inspired adaptation of MySQL Workbench icons as shown below:
image
[Source](https://stackoverflow.com/a/28859886)

### CODE REVIEW

**Review by ivasilov — CHANGES_REQUESTED** [review]
The PR seems ok, the diamond icon seems cut off by the hashtag icon. Can you add some space between them (1-2px should be enough)? This is on Firefox, btw.

Thank you for your contribution.

Screenshot 2023-08-04 at 09 33 26

**Comment by adiologydev** [comment]
> The PR seems ok, the diamond icon seems cut off by the hashtag icon. Can you add some space between them (1-2px should be enough)? This is on Firefox, btw.
> 
> Thank you for your contribution.
> 
> Screenshot 2023-08-04 at 09 33 26

I've increased the flex gap, I think it should solve this issue, was having some trouble testing this on Firefox but let me know if the issue persists. I'll add a 1px margin per icon.

**Review by ivasilov — CHANGES_REQUESTED** [review]
This looks perfect. 

One last thing, can you resolve the merge conflict? You also have a minor spelling issue there `justifty-start`.

**Comment by adiologydev** [comment]
> 

Thanks! I've fixed the typo and resolved the conflicts, should be good to go now.

**Review by ivasilov — APPROVED** [review]
Great work @adiologydev

**Pull request merged**
