### PR TITLE
Fix/side panel editor invalid date inputs

### PR DESCRIPTION
**Pull request by saltcod**
Addresses several recent reports of dates not working in the SidePanelEditor

ie: https://support.supabase.org/a/tickets/6380

I added and double checked that these fields work: 
- date
- time, 
- timetz
- timestamp
- timestamptz

**To test:** 
1. Create a new table
2. Add all of the above fields to it
3. Ensure a date/time/timestamp can be added successfully 

CleanShot 2022-05-16 at 22 20 40@2x

We should do a triple check before we merge this.

### CODE REVIEW

**Review by alaister — APPROVED** [review]
I was able to recreate the issue and then test again with your changes.
They seem to work beautifully locally 🎉 I was unable to break it.
Code makes sense too - nice work! 👍

**Comment by alaister** [comment]
Although is #6823 related to this at all?

**Comment by saltcod** [comment]
@alaister looks like that one fixed a couple of other issues as well.   Merged merged master into this branch & fixed the conflict listed.  Mind another quick recheck on this before we merge it please? 
Thanks for the 👀 !

**Comment by saltcod** [comment]
Actually, @alaister going to close this one for the moment. It looks like #6823 fixes this after all.

**Pull request closed without merging**
