### PR TITLE
examples: update auth helpers version of presence example app

### PR DESCRIPTION
**Pull request by dshukertjr**
## What kind of change does this PR introduce?

Updates the nextjs auth presence example app's auth helper version to resolve an unknown token issue that was preventing the app launch.

### CODE REVIEW

**Comment by alaister** [comment]
@dshukertjr who's the best person to review this?

**Comment by dshukertjr** [comment]
@alaister Sorry, I forgot to tag someone. @thorwebdev would you be able to take a look?

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks

**Comment by thorwebdev** [comment]
Oh actually, one question, should be be having both a `package-lock.json` and a `yarn.lock` json file, or can we remove one or the other?

**Comment by dshukertjr** [comment]
@thorwebdev Good point. I think it makes more sense to delete yarn.lock, right? Should we also delete the instruction to run the app usin yarn [here](https://github.com/supabase/supabase/tree/master/examples/realtime/nextjs-auth-presence#5-now-run-the-development-server) as well? I will remove it as well, but if we think the instruction should be there, we can always put it back!

**Pull request merged**
