### PR TITLE
Partner pages changes + sitemap generation

### LINKED ISSUE #12461: Add integration/partner pages to sitemap
# Chore

## Describe the chore

Integration pages are currently missing from the sitemap

Index pages:
https://supabase.com/partners/integrations
https://supabase.com/partners/experts

individual pages:
https://supabase.com/partners/ory

on another note, these urls are perhaps not good.
Could be: https://supabase.com/partners/*integrations*/ory for more clarity in url as to what it is

## Additional context

The sitemap is generated [here](https://github.com/supabase/supabase/blob/chore/case-studies/apps/www/internals/generate-sitemap.mjs).

The sitemap can be updated from here, and it runs on build (ie, `npm run build`)

Add any other context or screenshots that help clarify the task.

### PR DESCRIPTION
**Pull request by vozmi**
Resolves #12461

Changes:
- Sitemap generation of partners pages added to _**sitemap_www-partners.xml**_ because of API request
- _**partners/[slug].tsx**_ splitted to two differents slugs (_partners/:slug -> partners/integrations/:slug_ and _/partners/experts/:slug_)

### CODE REVIEW

**Comment by vozmi** [comment]
Resolves #12461

**Comment by MildTomato** [comment]
@vozmi You could just make an API request [in this file](https://github.com/supabase/supabase/blob/master/apps/www/internals/generate-sitemap.mjs) ?
And then add the partner/integrations pages to this site map generator ?

**Comment by vozmi** [comment]
@MildTomato, couldn't add API request to `generate_sitemap.mjs`. Maybe because of typescript or something. 
But I added generation of `partners/integration` and `partners/experts` pages from to `generate_sitemap.mjs` from builded folder `.next/server/pages`. 
This idea based on cutlope PR #12738

**Comment by vozmi** [comment]
Sitemap will be updated with new pages only after `build` and `postbuild` scripts. We can make sitemap for partners pages dynamic, but in this case we should move it to separate page, like I did before [here](https://github.com/supabase/supabase/pull/12709/commits/fa4c6166b930ece9641d189af1d287c4785c8a01).

**Comment by vozmi** [comment]
> Sitemap will be updated with new pages only after `build` and `postbuild` scripts. We can make sitemap for partners pages dynamic, but in this case we should move it to separate page, like I did before [here](https://github.com/supabase/supabase/pull/12709/commits/fa4c6166b930ece9641d189af1d287c4785c8a01).

Should mention that I revert this changes to make all sitemap generation in `generate_sitemap.mjs` :) 
But I can add it again if dynamic sitemap is necessary

**Comment by fsansalvadore** [comment]
Hey @vozmi, can you please resolve conflicts here? 
I'll double check and approve once that's done. Thank you!

**Comment by vozmi** [comment]
@fsansalvadore, conflitcs were resolved. Also, sitemap_www.xml was updated.

**Review by saltcod — APPROVED** [review]

**Pull request merged**
