### PR TITLE
SQL Editor support opening cell into side panel for read only detailed view

### PR DESCRIPTION
**Pull request by joshenlim**
Accessible via right click context menu on the cell
image

For textual values, you have the option to either view in raw or markdown
image
image

For JSON values, it'll automatically be prettified
image

### CODE REVIEW

**Review by alaister — COMMENTED** [review]
Working well! One small issue is you have to right click on the cells text content to get the custom menu. Clicking slightly below the text doesn't work

**Comment by joshenlim** [comment]
Gotcha on this - just pushed up to refactor the context menu in SQL editor results to use the UI lib's context menu component which should help to mitigate it

**Review by alaister — COMMENTED** [review]
Something else I've run into – viewing the value of a NULL column just shows as empty. Is this okay? or should we be showing NULL?

**Comment by joshenlim** [comment]
Great point! i'll make it such that it'll show NULL placeholder in the code editor
image

also pushed up a small style fix in the results table to capitalize null and make it darker
image

**Review by alaister — APPROVED** [review]
LGTM!

- Tested on preview with text, jsonb, and markdown

**Pull request merged**
