### PR TITLE
fix: BecomeAPartners form layout changed

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Supabase website fix

## What is the current behavior?

On the [Partners](https://supabase.com/partners/integrations) section, the layout of the form on the page is squashed and not aligned on mobile:

Screenshot 2022-06-03 at 16 47 16

## What is the new behavior?

The form has been change so that the fields are aligned on the mobile version and also matching in the same way as the layout on the [contact page](https://supabase.com/contact/enterprise):

Screenshot 2022-06-03 at 16 42 52

## Additional context

The form on bigger screen sizes will match the mobile with just a form field per line apart from the first two fields of First Name and Last Name

### CODE REVIEW

**Review by alaister — CHANGES_REQUESTED** [review]
Hey @Hallidayo, thanks for spotting this and the fix!

The rationale behind the original decision of making the fields side-by-side was due to this being a reasonably large form. I also like the grouping that it gives the form.
In keeping with this, would you mind putting all the fields back side-by-side, excluding the phone number and timezone fields (and any field that was previously full width)?

I agree that they could do with some more room to breathe on mobile, though. So maybe we can reduce the space between the fields (say `space-x-2` instead of `space-x-4`)?

I like your logic of making this more consistent with the enterprise contact form. For bonus points, you could grab the company size `<select />` from the enterprise contact form page and drop it in here.

Thanks again! 😄

**Comment by Hallidayo** [comment]
Hi @alaister, thankyou for checking this over for me.

I've reverted the layout on the fields that you said so the form looks like the following:

Screenshot 2022-06-06 at 15 45 07

I did have a look originally at changing the values on the company size dropdown but it seems that the `size` field on the `partner_contacts` looks like an Int/numeric field whilst the `company_size` field on the `enterprise_contacts` is a varchar field looking at the way the forms are sent back to the database table so a conflict may occur?

**Review by alaister — CHANGES_REQUESTED** [review]
Thanks for making the requested changes @Hallidayo!

If I could ask for one more small change:
To add a bit more breathing room between fields on larger screens, could you try `space-x-2 sm:space-x-4`?

You're right in saying that a conflict may occur with the `partner_contacts` size field – thanks for reminding me why we didn't have these two the same from the start. We will fix it at a later date.

**Comment by Hallidayo** [comment]
@alaister - I've added some more space on the bigger devices, Originally:

Screenshot 2022-06-13 at 09 22 47

Now:

Screenshot 2022-06-13 at 09 23 16

**Review by alaister — APPROVED** [review]
Thanks again @Hallidayo!
LGTM!

**Review by alaister — CHANGES_REQUESTED** [review]
Actually, it looks like prettier is failing - seems like there's some extra whitespace. Would you mind running prettier on the file?
I'll merge once the build is passing.

**Review by alaister — APPROVED** [review]

**Pull request merged**
