### PR TITLE
fix(studio): empty arrays become empty string in row editor

### LINKED ISSUE #15111: Empty array values aren't included when opening the row editor
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Empty array values aren't included when opening the row editor

## To Reproduce

Edit a record with `[]` like this
image

Click Save without making any changes. Result:
image

The error actually shows up even if the column is nullable

## Expected behavior

When editing a `[]` cell, it should not change to ``.

## System information

- OS: macOS
- Browser: Brave
- Supabase 1.64.2
- Node.js v18.14.2

### PR DESCRIPTION
**Pull request by rmrt1n**
## What kind of change does this PR introduce?
Empty arrays are now shown as `[]` instead of empty in the row editor. Fixes [#15111](https://github.com/supabase/supabase/issues/15111).

## What is the current behavior?
Currently, empty arrays from non-nullable columns are parsed into empty strings instead of being parsed into its string representation.

## What is the new behavior?
Now users should see `[]` instead of an empty input field in the row editor. Previously, users aren't able to save the changes if this input field remained empty.
### Old
image

### New
image

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by probablykasper** [comment]
Hey any chance to get this one merged? @sweatybridge

thank you! ❤️

**Review by sweatybridge — APPROVED** [review]

**Comment by saltcod** [comment]
@rmrt1n  any test cases to use for this one? These lines have a bunch of history entries, I'd want to make sure we're still covering all the possible edge cases that this check was meant to cover. 

Thinking things like: 

- nothing
- empty arrays
- empty objects 
- NULL
- etc

**Comment by rmrt1n** [comment]
There were existing test cases for this. The change failed one of the test cases that expected `parseValue([])` to be an empty array `[]`. This PR changes the output of `parseValue([])` to be its string representation `"[]"`, which is the same behavior as `parseValue({})`, which returns `"{}"`. The other test cases, which includes: null; empty strings; non-empty objects, passed.

**Comment by alaister** [comment]
Hey @rmrt1n,

Thanks for the PR!

Are the changes still relevant? If so, would you mind fixing the merge conflicts, please? 🙏

**Comment by rmrt1n** [comment]
Hey, @alaister , fixed the conflicts. ptal

**Review by joshenlim — APPROVED** [review]

**Pull request merged**
