### PR TITLE
[#196] Initiate Supabase UI Structure

### PR DESCRIPTION
**Pull request by mikqi**
## What kind of change does this PR introduce?

Initiate Supabase UI component library #196  

## Additional context

I built the architecture as minimal as possible, the project was initiate using create-react-app and I extend it using rollup for module bundler.
Currently I just add Button component, and I think I need list of colors config that we use for app.supabase.

image

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hi @mikqi - this is awesome. Really a great MVP. I have just one suggestion before merging:

`@tailwindcss/ui` is actually a commercial product. Can we instead use their new library [headless-ui](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react)?

**Comment by mikqi** [comment]
> Hi @mikqi - this is awesome. Really a great MVP. I have just one suggestion before merging:
> 
> `@tailwindcss/ui` is actually a commercial product. Can we instead use their new library [headless-ui](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react)?

Ahhh.. I just realize that [Tailwind UI](https://github.com/tailwindlabs/tailwindui-react) is deprecated and change to [Headless UI](https://github.com/tailwindlabs/headlessui). 😂

But if you look at in [tailwind.config.js](https://github.com/tailwindlabs/headlessui/blob/develop/tailwind.config.js#L26) at headless-ui. It also include @tailwindcss/ui, I don't know what is that for.
But if we want add headless-ui/react we can add it to default export it [here](https://github.com/supabase/supabase/pull/238/files#diff-4684ca2262176b85c9f0811814e2a6e8R1) so it will included in supabase-ui bundle files.

**Comment by kiwicopple** [comment]
I just spent 10 mins looking through their repos and I am more confused than when I started. Looks like `tailwind-ui` might actually be MIT, even though the website is not. 

image

Either way, I think that `headless-ui/headless-ui-react` is what we want, because it has some of the things we're using our Dashboard (like `transitions`). So if you're able to switch it to headless, I'll merge it in and we can iterate on it

**Comment by mikqi** [comment]
I just updated with new approach. Previously I use emotion and macro for styling, but the bundle size is not so good and hard to integrate with headless-ui because emotion is used inline but headless need tailwind classes.
So I try to use with postcss and it works well. FYI. if we remove plugin tailwindcss/ui from `tailwind.config.js` it will break some styling that needed for headless-ui, so I keep it there.
cc: @kiwicopple 
Sample component using headless-ui.
image

**Comment by kiwicopple** [comment]
> but the bundle size is not so good

❤️ thanks for putting performance first - very important

> headless need tailwind classes

I don't mind this at all - I think the classes are easy enough to reason about.

I'm going to merge this - I think it's an amazing start @mikqi, and I'm looking forward to trying it out on our website !

If you have any other improvements you can add them as separate PR's

**Pull request merged**
