### PR TITLE
docs: fix inconsistent naming of the SupabaseClient instance

### LINKED ISSUE #9864: inconsistent naming for `const supabase = createClient()`
# Improve documentation
In most of the documentation the supabaseClient Instance is named just `supabase`.    
All tutorials I have seen use the name `supabase`   

based on a search in the repository, there are 22 occasions where it says `const supabaseClient = createClient()`   

As a new user of supabase this has confused me.  
**Is there a good reason for the different naming conventions?**

## Link 

image

## Describe the improvement

I propose a careful search and replace with VSCode Regular expression in all .mdx files:   
search: `supabaseClient`  
replace: `supabase`  

## Additional context

Things to watch out when search and replacing: 
- the file in which createClient is usually invoked is called supabaseClient.[js, ts, jsx]; we don't want to change that.
- some other exceptions

the `const supabaseClient = createClient()` naming is also used in some examples in .tsx files visible at https://supabase.com/edge-functions

**I would be happy to make a pull request.**

### PR DESCRIPTION
**Pull request by walkerdustin**
From the users (developers) perspective, the instance of the SupabaseClient is basically the entire backend.
Having a consistent naming convention for this instance is important.
most of the time it is called 'supabase' but sometimes it is also called 'supabaseClient' or 'client' or other
There were even some inconsistencies within the same file, so this change is quite important so that readers of the docs 
don't think that they are stupid for not knowing the difference between the supabase and the supabaseClient object.

@thorwebdev  mentioned, that used to distinguish between a browser client and a server client, but I think this naming convention is not consistently followed in the docs.

## what did I do?
I searched for supabaseClient  
in all .mdx files and all .md files  
and changed all references to the instance

## Considerations for the reviewer:

sometimes const supabaseServerClient = createServerSupabaseClient<Database>({
is used. Is this the same supabaseClient Instance or are there differences?
I dont know.
maybe it could make sense, to name that instance differently, if there is a good reason for it and it is done consistently
for this PR I have changed that instance name to supabase

apps\docs\guides\auth\auth-helpers
and apps\reference\docs\guides\auth\auth-helpers 
are not changed, because then the README in the supabase/auth-helpers repo would need to change as well.

in some migrating guides there is an
oldSupabaseClient and newSupabaseClient 
I did not change these names. (because this naming makes sense for a migration guide)

There are also references in the old docs version-v1 
you may decide, if you want to include them in the merge.

There are just a handfull of references to a supabaseClient object in .tsx files. 
I did not touch any tsx file for this PR

There are some references in js and ts files.
I did not touch these files.

would you change the object name in comments like 
	Start off by creating a `db.ts` file inside of the `src/lib` directory and instantiate the `supabaseClient`.
to something like 
	Start off by creating a `db.ts` file inside of the `src/lib` directory and instantiate the `supabase` object.

## Files and Folders where I am unsure
The reviewer of this PR is encouraged to take an extra look at these files.  

apps\docs\guides\storage.mdx
  final client = SupabaseClient('supabaseUrl', 'supabaseKey');

apps\docs\guides\with-nextjs.mdx
	<SessionContextProvider
      supabaseClient={supabaseClient}
	  
apps\docs\guides\auth\auth-helpers\nextjs.mdx
	// Please review the changes in this file 
	  // in the same file different syntax is used 
	    const supabaseServerClient = createServerSupabaseClient<Database>({
		const supabaseClient = useSupabaseClient<Database>()
	    const supabase = createServerSupabaseClient({ req, res })
		const supabase = createMiddlewareSupabaseClient({ req, res })
		const [supabaseClient] = useState(() => createBrowserSupabaseClient<Database>())
	// Do these functions all return the same object or is there a difference?
	// I honestly don't have much clue about nextjs 
	// I did not changed the object names because they are related to auth-helpers

apps\docs\guides\integrations\authsignal.mdx
	apparently there is an export named supabaseClient from auth-helpers-nextjs
	import { supabaseClient } from "@supabase/auth-helpers-nextjs";
	I do not understand this. Please review.
	I did not touch apps\docs\guides\integrations

### CODE REVIEW

**Comment by Dustin-dusTir** [comment]
#9864

**Comment by thorwebdev** [comment]
Awesome, thank @Dustin-dusTir 🔥

cc @dannykng for docs and @dshukertjr for flutter/dart clients.

**Review by dshukertjr — COMMENTED** [review]
Love this! I have been defaulting to `supabase` whenever possible with Flutter/ Dart docs and samples as well!

**Comment by Dustin-dusTir** [comment]
@dshukertjr sorry, I I have just accidentally pressed some button in the mobile GitHub interface.
I do not need an extra review from you. 
Sorry😅

**Review by dannykng — APPROVED** [review]
This LGTM—thanks @Dustin-dusTir!

@thorwebdev can you review the nextjs and auth-helpers content?
> The reviewer of this PR is encouraged to take an extra look at these files.
> 
> apps\docs\guides\storage.mdx
> final client = SupabaseClient('supabaseUrl', 'supabaseKey');
> 
> apps\docs\guides\with-nextjs.mdx
> <SessionContextProvider
> supabaseClient={supabaseClient}

> apps\docs\guides\auth\auth-helpers\nextjs.mdx
> // Please review the changes in this file
> // in the same file different syntax is used
> 
> const supabaseServerClient = createServerSupabaseClient({
> const supabaseClient = useSupabaseClient()
> const supabase = createServerSupabaseClient({ req, res })
> const supabase = createMiddlewareSupabaseClient({ req, res })
> const [supabaseClient] = useState(() => createBrowserSupabaseClient())
> 
> // Do these functions all return the same object or is there a difference?
> // I honestly don't have much clue about nextjs
> // I did not changed the object names because they are related to auth-helpers

> apps\docs\guides\integrations\authsignal.mdx
> apparently there is an export named supabaseClient from auth-helpers-nextjs
> import { supabaseClient } from "@supabase/auth-helpers-nextjs";
> I do not understand this. Please review.

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
