### PR TITLE
Streams edge function example

### PR DESCRIPTION
**Pull request by gregnr**
Streams edge function example as shown in upcoming Edgy Edge Function video.

### CODE REVIEW

**Review by thorwebdev — APPROVED** [review]
LGTM, thanks

**Comment by deepak-coding-art** [comment]
How to connect the stream with supabase-js library

**Comment by gregnr** [comment]
Hey @deepak-coding-art, the JS library doesn't support streams at the moment, but it's something we'll consider in the future. In the mean time you can check out our Clippy implementation here, which uses [`sse.js`](https://github.com/mpetazzoni/sse.js):
https://github.com/supabase/supabase/blob/b2625c96d8b64855696f6d2e13518362a4701bd2/apps/docs/components/Search/SearchModal.tsx#L116-L123

**Comment by JSmithOner** [comment]
@deepak-coding-art only problem is that SSE is for node environment and I'm not able to use it using angular.If you have any clue how to handle this, I'm following your video tutorial.Best

**Comment by gregnr** [comment]
@JSmithOner are you using edge functions for server-side logic? If so, [sse.js](https://github.com/mpetazzoni/sse.js) should work perfectly fine in your Angular app.

**Comment by JSmithOner** [comment]
@gregnr Yes I'm using what you've told on the video with the `fetch` function. I think SSE uses the `require` which is mainly not accepted in angular that uses `import` (sorry for the approximation bu basically there are incompatibilities of context, I've already faced this kind of problems without a chance), I think this has also to do with webpack.So if you have any ideas?

**Comment by gregnr** [comment]
@JSmithOner You can pull in `sse.js` using `import` - check out our implementation:
https://github.com/supabase/supabase/blob/b2625c96d8b64855696f6d2e13518362a4701bd2/apps/docs/components/Search/SearchModal.tsx#L5

The code above is for a React (Next.js) project, but the same ideas should apply to Angular. Both use Webpack under the hood. Let me know if you have any specific question or error that's blocking you and we can try to resolve.

**Comment by JSmithOner** [comment]
@gregnr 
I've tried it and get this error


```
ERROR in ./node_modules/sse/lib/sse.js 3:10-24

Module not found: Error: Can't resolve 'url' in '/Users/vv/Documents/t/a/p/node_modules/sse/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }
```

so if that speaks to you?thanks in advance.

**Comment by JSmithOner** [comment]
@gregnr Is it the `sse` package from `npm` because if so it says it's for server side.Could you give me the `npm` command please?

**Comment by gregnr** [comment]
@JSmithOner I'm going to move this conversation over to a discussion: https://github.com/supabase/supabase/discussions/13124.

I've filled in as much context as I can there which might answer your latest questions. If not, please reply there and we can keep debugging your issue. Thanks!

**Pull request merged**
