### PR TITLE
feat: Add Supabase Auth components, update password, and SSR Cookie example.

### PR DESCRIPTION
**Pull request by thorwebdev**
## What kind of change does this PR introduce?

- Adds the Supabase Auth component.
- Adds handling of password reset & update.
- Adds SSR example using the auth cookie.

@ykdojo let me know what you think of the reset password experience here. I think it's pretty decent now \o/

@MildTomato any chance you could add a lick of paint to this?

### CODE REVIEW

**Comment by MildTomato** [comment]
@thorsten-stripe nice!

I just ran it now - I'll tidy it up a bit and set it to dark mode.

**Comment by kiwicopple** [comment]
Looks SICK! 

@ykdojo if you're happy with this, let's merge?

**Comment by thorwebdev** [comment]
@MildTomato looks 🔥 thank you!

Did you have a chance to look at this in supabase/ui?
image

**Comment by MildTomato** [comment]
I'll get a patch release on `ui` lib to fix that key issue. there's other components affected by this as well.

cc @thorwebdev

**Comment by scarsam** [comment]
@thorwebdev, would it be possible to run API call to `/api/auth` on the server before hitting the `useEffect` on the client? I'm trying to prevent the first call to the client and instead make the auth check before the user sees the page. My guess is that `event` and `session` from `onAuthStateChange` isn't available on the server?

**Comment by thorwebdev** [comment]
> My guess is that event and session from onAuthStateChange isn't available on the server?

@scarsam correct, this data is not available on the server unless sent by the client.

**Pull request merged**
