### PR TITLE
fix: auth policies removed truncation styling

### LINKED ISSUE #9302: Unnecessary truncation on RLS policy name
# Bug report

We're unnecessarily truncating the policy name. We should try and have this line wrap rather than truncate, or if it actually does need to truncate, maybe we can show the full name on hover. 

CleanShot 2022-10-03 at 12 37 51@2x

### PR DESCRIPTION
**Pull request by Hallidayo**
## What kind of change does this PR introduce?

Studio -> Auth -> Policies

## What is the current behavior?

The current policy name gets truncated when this is not needed

## What is the new behavior?

As their is a limit of 63 characters on the policy name the whole name can be shown:

Screenshot 2022-10-04 at 15 50 16

## Additional context

Closes #9302

### CODE REVIEW

**Comment by saltcod** [comment]
Hey @Hallidayo thanks for picking this one up. 

 I think we need to remove the `truncate` from the div above this one as well. But when we do that, the layout breaks:
CleanShot 2022-10-04 at 12 27 40@2x

CleanShot 2022-10-04 at 12 28 53@2x


Mind another look?

**Comment by Hallidayo** [comment]
Hi @saltcod - Just made a change now to remove the other `truncate` and fix the width when this is replied.

**Comment by saltcod** [comment]
Thanks @Hallidayo — looks like just a conflict to resolve and we're good to go.

**Review by saltcod — APPROVED** [review]

**Comment by Hallidayo** [comment]
Hi @saltcod - Just push a conflict change now.

**Comment by Hallidayo** [comment]
Closing this due to conflict, will open a new PR.

**Pull request closed without merging**
