### PR TITLE
new logs & analytics sidebar

### PR DESCRIPTION
**Pull request by jordienr**
- new sidebar following same patterns as sql editor sidebar
- you can now update saved queries

### CODE REVIEW

**Comment by saltcod** [comment]
Auto-name via AI appropriate here? Or will it be hard to gather the context from the query as to what the script is about?


screenshot-2024-09-24-at-09 16 24

**Comment by saltcod** [comment]
screenshot-2024-09-24-at-09 20 59

**Comment by saltcod** [comment]
nit: do a truncate on the label so the icon doesn't change width 

screenshot-2024-09-24-at-09 21 53

**Comment by saltcod** [comment]
not sure if planning to get this into the sidebar template ui style like RLS policies in this iteration, but would be great. Navigating to this templates page is such a weird ux

screenshot-2024-09-24-at-09 23 36

**Comment by joshenlim** [comment]
> small empty state maybe?

yup! can borrow from SQL editor too :)
image

**Comment by joshenlim** [comment]
some z-index thingy happening here

image

**Comment by joshenlim** [comment]
let's do align="end" to follow the sql editor here
image

**Comment by joshenlim** [comment]
separately - i know this has come up many times before, but just wanted to check if updating / deleting warehouse collections has been patched on the BE? i still can't update collections on the preview, and deleting a collection throws an error although the collection does actually get deleted (it goes away after a refresh)

**Comment by jordienr** [comment]
> separately - i know this has come up many times before, but just wanted to check if updating / deleting warehouse collections has been patched on the BE? i still can't update collections on the preview, and deleting a collection throws an error although the collection does actually get deleted (it goes away after a refresh)

Ziinc has a PR open with the fix, should be merged soon!

**Comment by jordienr** [comment]
> just a thought - i'm on the fence about using this icon for collections, initially thought this was a database image

Agree, I went with this one after trying many from lucide because its the most neutral. Will ping design team to get some feedback.

**Comment by saltcod** [comment]
create query button? 

screenshot-2024-09-27-at-15 21 17

**Review by saltcod — APPROVED** [review]

**Pull request merged**
