### PR TITLE
feat: add DocSearch as recommended by docusaurus

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).

This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by s-pace** [comment]
Any help needed on this?

**Comment by kiwicopple** [comment]
I like the idea of it @s-pace but we override the Theme header so the search bar isn't showing up. If you want, you can add it back in and I will merge this

Something missing in this file
https://github.com/supabase/supabase/blob/master/web/src/theme/Navbar/index.js

**Comment by s-pace** [comment]
Are you sure? It seems you have the same cd-ode without the latest update (mostly using React hooks)

**Comment by s-pace** [comment]
It does work on https://deploy-preview-28--supabase.netlify.com/

**Comment by s-pace** [comment]
image

**Comment by kiwicopple** [comment]
Yes you're right, thanks @s-pace

**Comment by kiwicopple** [comment]
Thanks for the PR @s-pace - it does have one bug, but I've merged it anyway and we can fix the bug later

https://github.com/supabase/supabase/issues/49

**Pull request merged**
