### PR TITLE
Restore enterprise pricing col

### PR DESCRIPTION
**Pull request by fsansalvadore**
## What kind of change does this PR introduce?

Restore Enterprise pricing column.

## Before

Screenshot 2023-08-25 at 14 50 15

## After

Screenshot 2023-08-25 at 14 50 02

### CODE REVIEW

**Comment by kevcodez** [comment]
Screenshot 2023-08-25 at 18 24 09

Looks a bit too compact on this resolution IMO (shortly before it goes into two columns).

**Comment by kevcodez** [comment]
Screenshot 2023-08-24 at 15 52 56

Quite a lot of padding for the Enterprise row, if it's just a single column

**Review by kevcodez — APPROVED** [review]
Just two nits, feel free to tackle or leave them be

**Comment by fsansalvadore** [comment]
@kevcodez yeah the "compact" version is actually intentional because otherwise the text would be much more squashed and it looked worse.

For the Enterprise spacing, I agree it could be better but it's preferable to keep the bullet points section aligned with the other columns.

**Pull request merged**
