### PR TITLE
chore: AreaChart extraction and refactor

### PR DESCRIPTION
**Pull request by Ziinc**
Refactors the AreaChart, extracts and separates components for better maintainability.

changes
- mouse over focus handling fixes, now can hover over data points on the y axis.
- code cleanup
- separate NoData message component, conditionally shows when chart is of length 0.
- separate ChartHeader component
- proper typings

Todos:
- [ ] ~~timeseries prop~~ no use case for non-timeseries yet.
- [x] header minimal
- [x] No data message

Screenshot 2022-10-10 at 11 54 38 PM

Supercedes #7454  and #7453

### CODE REVIEW

**Comment by Ziinc** [comment]
added fix for highlight value rendering

https://user-images.githubusercontent.com/22714384/195263806-190d985e-795d-41fa-a1cb-64617c823767.mov

**Review by joshenlim — CHANGES_REQUESTED** [review]
adding comment here as well for visibility, 2 more issues found: 

image


- the percentage values are not rounded off to 2dp
- the value is now updating on hover but the time isn't
- need a bit more padding between the date and the chart itself

**Comment by Ziinc** [comment]
added in the number formatting and padding, but can’t seem to simulate the hover label changing bug that you mentioned.

https://user-images.githubusercontent.com/22714384/197132203-f08c38f5-7eaf-4a88-a347-b1eee4445776.mov

**Comment by Ziinc** [comment]
- [ ] figure out why datetime label does not change on hover

**Comment by Ziinc** [comment]
Figured out why the label wasn't changing and why the x-axis was off, looks like i had set the x-axis key wrongly 🤦 

https://user-images.githubusercontent.com/22714384/201140024-04800efe-b93b-4f46-9813-c526d2de30fc.mov

**Review by joshenlim — APPROVED** [review]

**Pull request merged**
