### PR TITLE
docs: wrap url and anon key strings in quotes for flutter connection example

### LINKED ISSUE #26910: Issues with Flutter Connection sample
# Bug report

When we try to get the sample code for connecting to supabase from Flutter app, the code sample is not readable, and the parameters to be pass, i.e. url and anonKey are not wrapped inside quotes (not marked as strings), causing them to cause syntax errors.
image

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The sample connection code is not properly formatted, and contains syntax errors.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Supabase project
2. Click on Connect Button on Project Home
3. Go to Mobile Frameworks tab
4. Select Flutter Framework

## Expected behavior

The code should be formatted, and must contain string quotes for initialization of connection.

## Screenshots

image

## System information

- OS: [e.g. macOS, Windows]: MacOS
- Browser (if applies) [e.g. chrome, safari]: Brave

### PR DESCRIPTION
**Pull request by officer-kd6-3dot7**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Docs: PR to fix the initialize function example for a  flutter connection

## What is the current behavior?

Behaviour as mentioned in Issue #26910
image

## What is the new behavior?

New behaviour 
image

### CODE REVIEW

**Review by MananGandhi1810 — COMMENTED** [review]
Wont this change cause duplication of quotation marks, in the case that the apiUrl or anonKey is null (''your-project-url'' or ''your-anon-key'') ?

**Comment by MlNl-PEKKA** [comment]
I'm pretty sure it won't. The quotes within the braces just makes sure that the default placeholder is a string. The quotes outside the braces are actually required, according to the requirement.  To sum it up, we do want only one set of quotes, the inner quotes won't be show it just says that, that's a string.

**Comment by MlNl-PEKKA** [comment]
image

**Review by Hallidayo — APPROVED** [review]
LGTM! Thank you @MlNl-PEKKA 👍

**Review by charislam — APPROVED** [review]
Thanks @MlNl-PEKKA!

**Pull request merged**
