### PR TITLE
editing baseUrl to correct urls for search results for blog articles

### PR DESCRIPTION
**Pull request by rpie3**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Currently on the live docs site, if you click on a result for a blog article, the page shows "Page Not Found"
The URL is constructed as `https://supabase.com/docs/blog/...`

## What is the new behavior?

The URL is constructed as `https://supabase.com/blog/...`

## Additional context

Running locally, this seems to resolve the broken blog links without breaking any other search result links, thought I am not 100% confident I have covered every possible case with regards to types of results.

### CODE REVIEW

**Comment by florian-lefebvre** [comment]
Are you sure that modifying the base url won't break all the links of the documentation? For instance, I don't know if sidebar links rely on the base url internally but it would make sense to me.

**Comment by rpie3** [comment]
I am not 100% certain, no. Running locally, I can't find any links in the sidebar that are broken, but some are modified...

For example, the last link in the sidebar (to the Acceptable Use Policy) is `https://supabase.com/docs/company/aup` on the live site. With this change, running locally, it becomes `http://localhost:3005/company/aup` but the page still loads as expected, where as going to `https://supabase.com/company/aup` currently yields a 404.

That being said - I did just notice some links breaking, specifically, anything under `/docs/guides/...` - I think the PR does need one small tweak. I will update momentarily, it seems like `/docs` _does_ need retained, just moved under the presets option.

**Comment by rpie3** [comment]
From what I am seeing, all links seem to be working as expected in the Vercel preview now - maybe you could put a second set of eyes on it @florian-lefebvre ?

**Comment by florian-lefebvre** [comment]
https://zones-docs-agz6dp1u5-supabase.vercel.app/ is a 404 page now

**Comment by Isaiah-Hamilton** [comment]
@rpie3 wouldn't this be a problem with the marketing website since it's on supabase.com/ and the changes that you are making also puts it on supabase.com/

**Comment by florian-lefebvre** [comment]
@Isaiah-Hamilton I don't think so, the goal is only to get the right url for blogs but I might be wrong, I'm not familiar with Docusaurus.

**Comment by kiwicopple** [comment]
closing this as the search is now fixed !

**Pull request closed without merging**
