### PR TITLE
docs: self-hosting - checkout only docker directory from supabase project

### PR DESCRIPTION
**Pull request by cyluss**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

docs update

## What is the current behavior?

'Self-hosting with docker' document guides to checkout full project repository, which weighs around 766 MiB at 2024-05-01. Please refer supabase/supabase#23454.

## What is the new behavior?

'Self-hosting with docker' document guides to checkout only docker directory from project repository using git sparse checkout. Please refer supabase/supabase#23454.

## Additional context

supabase/supabase#23454

### CODE REVIEW

**Review by encima — CHANGES_REQUESTED** [review]
looks good and works fine. `pushd` is an optional extra but no preference of leaving it in or removing.

Imo, this is an optional addition to running it locally. Yes, the repo is large but the instructions are designed for all technical levels and the original instructions are more recognisable.

I would suggest having this as a tabbed option for: `General` and `Advanced` maybe.

**Comment by encima** [comment]
@supabase/docs in case you have opinions

**Comment by cyluss** [comment]
I tried to rebase my repository up to date but failed. Can we discuss on the issue #23454 or change issue into discussion?

**Comment by cyluss** [comment]
Yes, this is optional and complicates the document. And it does not run in old versions of git which does not support clone filtering and sparse checkout.

However the repository will get bigger as time goes by, and some readers would copy and paste line-by-line what says on the document. IMO this is inherent complexity of monorepo and it is questionable to assume that all readers are on sufficiently fast broadband and cloning will end in short time period.

**Comment by cyluss** [comment]
I agree with @encima's point and applied suggestion to the original issue. I will send another pull request in the weekend

**Pull request closed without merging**
