### PR TITLE
Studio: reduce Docker image size

### PR DESCRIPTION
**Pull request by bnjmnt4n**
## What kind of change does this PR introduce?

Feature.

## What is the current behavior?

Docker image size is currently ~600MiB, after https://github.com/supabase/supabase/pull/4769.

## What is the new behavior?

This PR uses [Next.js 12.1's new standalone output build](https://nextjs.org/blog/next-12-1#self-hosted-nextjs-improvements) to create Docker builds which are much smaller than the current builds (~220MiB). Note that this is still an experimental Next.js feature, but I ran a quick test of `docker-compose up` with the full standalone suite using the new build image and everything seems to work largely fine.

This is similar to @Ziinc's suggestion in https://github.com/supabase/supabase/pull/4769#discussion_r779311410, except it is explicitly supported by Next.js (albeit being in experimental mode right now).

## Additional context

This PR is stacked on top of https://github.com/supabase/supabase/pull/5580.

### CODE REVIEW

**Comment by Ziinc** [comment]
From my understanding, since the migration to platform api, we no longer need the server logic under `studio/pages/api`, and we could technically serve only the static build of the nextjs frontend.

If so, we can build the static assets, copy it over to a fresh alpine nginx image, enable gzip/brotli, and call it a day. Thoughts? @joshenlim

**Comment by bnjmnt4n** [comment]
> From my understanding, since the migration to platform api, we no longer need the server logic under `studio/pages/api`, and we could technically serve only the static build of the nextjs frontend.

This might be true for the hosted platform, but I believe for local setups the `studio/pages/api` directory is required as an interface to the `postgres-meta` server.

**Comment by joshenlim** [comment]
You're right here @bnjmnt4n - at the moment for self-hosted studio, it still relies on its internal `/api` for pg-meta so we can't remove it yet

**Comment by pucho** [comment]
I'll close this for now since, we'll revisit the docker image sizes during our efforts on Self-hosted in the coming weeks. @bnjmnt4n you can find me on the community discord if you want to have a conversation around this topic. Thanks!

**Pull request closed without merging**
