### PR TITLE
chore: amend docs to include info about custom templates

### PR DESCRIPTION
**Pull request by MildTomato**
— added "SMS custom template" text to the twilio guide
— some prettier formatting

### CODE REVIEW

**Review by kiwicopple — APPROVED** [review]

**Review by asperpharma — COMMENTED** [review]
Approve

**Review by asperpharma — COMMENTED** [review]
accept

**Review by asperpharma — COMMENTED** [review]
Accept

**Review by asperpharma — COMMENTED** [review]
f

**Review by asperpharma — COMMENTED** [review]
vcv

**Pull request merged**
