### PR TITLE
fix(ResourceContent): add null coalesce on resourceDefinition, add types and tests

### LINKED ISSUE #14766: API Preview crashing for tables in custom schema
# Bug report

## Describe the bug

The API preview in the table editor crashes when viewing a table in a custom schema

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new schema
2. Create a new table in that custom schema
3. Select that table from the Table Editor 
4. Click the API button  
5. Page crashes

## Expected behavior

You should be able to view the API docs for a table in a custom schema
CleanShot 2023-06-02 at 16 25 33@2x
CleanShot 2023-06-02 at 16 30 10@2x

### PR DESCRIPTION
**Pull request by brandongregoryscott**
## What kind of change does this PR introduce?

Fixes #14766

## What is the current behavior?

The current behavior causes a runtime exception when the `resourceDefinition` object in `ResourceContent.tsx` is accessed w/o properly null checking it first. It seems like this was just an oversight, since there's a null check for this object later on in the `ResourceContent` component.

## What is the new behavior?

I added some types to this component and null coalescing on the `resourceDefinition` object since it might not be present in a custom schema it seems. Additionally, the `resourceId` seems like it should be a required prop, but based on existing usage, is nullable:

https://github.com/supabase/supabase/blob/1d5a53e8fd2671f64f75c69e334e0e85e3ca5a9c/studio/components/interfaces/TableGridEditor/APIDocumentationPanel.tsx#L113

I typed it as `string | undefined` so consumers must pass a value to it, but added a falsy check since you can't index into an object with `undefined`. Let me know if you think we should change this back to the previous behavior and add a `@ts-ignore` or some other behavior.

## Additional context

N/A

### CODE REVIEW

**Comment by saltcod** [comment]
Hey @brandongregoryscott ! Amazing, thanks for this!

Just testing this out (created a new schema, exposed that on the api settings page, then added a new table to it). 

Getting this: 
CleanShot 2023-06-05 at 17 21 15@2x

**Comment by brandongregoryscott** [comment]
Ah, whoops! I thought I added a safe guard for that. I'll push up a change.

**Comment by brandongregoryscott** [comment]
Let me know if that fixes it up @saltcod!

**Comment by saltcod** [comment]
aah yup that fixed that error, thanks!

Are you seeing column data though on your end? 

CleanShot 2023-06-06 at 09 21 29@2x

**Comment by brandongregoryscott** [comment]
I'm not that familiar with this feature, tbh - should it be rendering additional components? There might be a deeper issue w/ whatever is creating or loading the underlying table/column data 🤔

**Pull request closed without merging**
