### PR TITLE
Update docusaurus.config.js

### LINKED ISSUE #89: Add Stackshare link to our footer
We were somehow picked up by Stackshare, so we should add the link to our footer in the "Community" section: https://stackshare.io/supabase

(While we're at it, we should add the Product Hunt link).

### PR DESCRIPTION
**Pull request by AmanDev-Code**
changes have been done please rectify them.

### CODE REVIEW

**Review by AmanDev-Code — COMMENTED** [review]
review back the problems to solve

**Comment by soedirgo** [comment]
Looks good to me. 👍

Do you mind adding the Product Hunt link as well? It's this one: https://www.producthunt.com/posts/supabase-alpha

**Comment by Exploringtechnologies** [comment]
Thankyou sir, yes ill work on it

**Comment by Exploringtechnologies** [comment]
sir  may i know the changes have been commited or not the first one? and should i close the first pull request

**Comment by Exploringtechnologies** [comment]
both the changes is okay?

**Review by soedirgo — APPROVED** [review]
Perfect! Thanks for contributing @Exploringtechnologies :)

FYI, you didn't need to make another pull request, just make another commit on your branch, as you did here. 👍

**Comment by kiwicopple** [comment]
Amazing job @Exploringtechnologies. Is this your first open source contribution?

**Comment by Exploringtechnologies** [comment]
Yes @kiwicopple this is my very first contribution after uploading my first repo 😊

**Comment by kiwicopple** [comment]
image

Wow, you're off to a flying start. It took me years to build up the courage to contribute to a project. Keep up the awesome work 💪

**Comment by Exploringtechnologies** [comment]
Thankyou @kiwicopple so much sir it means a lot to me, 🤗😊😊 Very cliche phrase 😀

**Pull request merged**
