### PR TITLE
docs: Added inner join example to javascript reference docs 

### PR DESCRIPTION
**Pull request by danielbolivar**
This adds inner join example to the javascript reference docs addresing part of the issue #15053

### CODE REVIEW

**Comment by gregnr** [comment]
Thanks @danielbolivar! Can we do the same for the other client libs mentioned in #15053 (python, swift, kotlin)?

**Comment by danielbolivar** [comment]
> Thanks @danielbolivar! Can we do the same for the other client libs mentioned in #15053 (python, swift, kotlin)?

I'm not as good on those languages but I'll give it a try!

**Comment by saltcod** [comment]
Merging this before it gets stale

**Comment by alaister** [comment]
Hi @danielbolivar,

Would you mind fixing the merge conflicts or closing this if it's no longer relevant?

Thank you! 🙏🏻

**Pull request closed without merging**
