### PR TITLE
chore: Improve Navigation menu dropdown to disable background scrolling

### PR DESCRIPTION
**Pull request by clarencepenz**
## What kind of change does this PR introduce?

 prevent background scrolling when the Navigation menu dropdown is open

## What is the current behavior?

Scrolling occurs when the  Navigation menu dropdown is open

https://github.com/supabase/supabase/assets/11736897/562805a8-fc92-4b0e-b6cd-96adccad383a

## What is the new behavior?
Scrolling is prevented when the  Navigation menu dropdown is open

https://github.com/supabase/supabase/assets/11736897/76209517-f2e0-453e-ba89-b537620a1d50

### CODE REVIEW

**Comment by clarencepenz** [comment]
Hey, @ivasilov can you help take a look at this?

**Comment by clarencepenz** [comment]
Hey, @alaister  can you help take a look at this?

**Comment by alaister** [comment]
hey @clarencepenz, @fsansalvadore might be the person for this one 🙌🏻

**Comment by clarencepenz** [comment]
Thanks @alaister! Looking forward to @fsansalvadore review

**Comment by fsansalvadore** [comment]
Hey @clarencepenz, thanks for the thoughtful PR!

We feel this kind of behaviour would be more appropriate if the dropdown menu was full page, similar to what happens on mobile when the menu is open. The scroll lock here feels unnecessarily blocking in this case.

Unless there's a strong case for this feature, we'd go without the scroll lock.

Thanks! 🙏

**Comment by clarencepenz** [comment]
Hey @fsansalvadore, thanks for reviewing this PR!

One of the main reasons I thought about implementing this feature was that I often get distracted by the whole background scroll and lose the exact location on the page when I am on the navbar or the nav menu when I use my external mouse. 

Also, here are a couple of reasons:

- Preserving User Context: When users open a menu, the scroll lock ensures they don't lose track of where they are on the page.
- Improving Focus: By locking the screen, users can concentrate better on the menu options without distractions.
- Reducing Mental Effort: Users don't have to juggle multiple scrolling behaviors, making navigation less mentally taxing.

Looking forward to your next review

**Comment by fsansalvadore** [comment]
@clarencepenz thanks for taking your time to argument your case.

After reviewing your PR again we continue to prefer keeping the current behaviour, which is the most commonly expected when using this kind of component. See https://ui.shadcn.com/docs/components/navigation-menu

Blocking the scroll can sometimes be annoying to the user. In fact just yesterday I happened to be on the Nextjs docs and while having the app vs page router dropdown open, I switched context for a few minutes and when I came back I wasn't able to scroll. I thought the page had frozen, just to find out the dropdown was still open and blocking scroll.

I suggest opening a [discussion](https://github.com/orgs/supabase/discussions) to find out if your proposal gains traction.

**Pull request closed without merging**
