### PR TITLE
Fix Spanish translation

### PR DESCRIPTION
**Pull request by owlnai**
## What kind of change does this PR introduce?

Docs' translation update. It fixes some translations errors of the Spanish README.md.

## What is the current behavior?

There was a PR for the Spanish translation (#1352). While the translation quality was overall fine, I noticed some translation mistakes. I was doing a PR review to suggest every change, but it got merged; so I decided to implement these changes in a separate PR.

## What is the new behavior?

Improved translations. 

Edit: Mentioning @gomflo in case they want to review these changes.

### CODE REVIEW

**Comment by mkiisoft** [comment]
"Panel" doesn't give any context. We should use "Panel de control" as that's what a Dashboard really is.

**Comment by owlnai** [comment]
> "Panel" doesn't give any context. We should use "Panel de control" as that's what a Dashboard really is.

Good catch!

**Review by mkiisoft — APPROVED** [review]
LGTM

**Comment by kiwicopple** [comment]
thanks team 🔥

**Pull request merged**
