### PR TITLE
Update docs to maybe optimize RBAC functions performance

### PR DESCRIPTION
**Pull request by felixgabler**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

The RBAC docs do not use subqueries in the RLS policies and also do not mark the `authorize` function as `stable`.

## What is the new behavior?

I added `stable` to `authorize`, made it fetch the user role into a variable to save calls and also added subqueries to the RLS policies. I am not sure the subqueries really help in this case but generally it is advisable to get people to think about using subqueries for their auth functions in RLS so subquery caching can take effect. Curious for your thoughts!

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by charislam** [comment]
LGTM but I'm not super familiar with this flow, so I'll get @thorwebdev's second opinion as the author

**Comment by felixgabler** [comment]
@thorwebdev what do you think about this PR?

**Review by pashkinelfe — APPROVED** [review]

**Comment by thorwebdev** [comment]
@felixgabler very sorry, this slipped through the cracks. Would you mind resolving the conflicts and then we can get it merged in? Thanks for bearing with us here 💚

**Comment by felixgabler** [comment]
@thorwebdev no worries, thanks for taking a look now! I have resolved the comments and it should be ready to merge now.

I hope it is okay if I use this opportunity to mention another issue that might have slipped through the cracks: https://github.com/supabase/auth-js/issues/912. This is blocking the Nuxt supabase integration from upgrading to `@supabase/ssr` through [this PR](https://github.com/nuxt-modules/supabase/pull/357). Maybe you could nudge someone for us? Thanks!

**Pull request merged**
