### PR TITLE
Text center-aligned instead of left-aligned in dropdown menu #16243 |…

### PR DESCRIPTION
**Pull request by hellofaizan**
… Fixed

## What kind of change does this PR introduce?
Fixed minor UI big #166243

### CODE REVIEW

**Comment by hieuwu** [comment]
It would be nice if you provide some screenshots of the change for easy comparison, maybe in different screen sizes to make sure they are responsive

**Comment by hellofaizan** [comment]
I am not able to run it locally on my machine. It's just I know Tailwind and also inspected the code base so I made the changes

**Review by ivasilov — APPROVED** [review]

**Comment by ivasilov** [comment]
Thank you for your contribution @hellofaizan.

**Comment by hellofaizan** [comment]
Pleasure

**Pull request merged**
