### PR TITLE
fix: close mobile menu on click

### PR DESCRIPTION
**Pull request by nick-krantz**
## What kind of change does this PR introduce?

Bug Fix.

## What is the current behavior?

Bug fix for #14533. The mobile menu does not close when selecting a navigation item in the client reference documentation. 

## What is the new behavior?

An `onClick` listener is attached to the reference navigation items that will close the mobile menu when clicked. This event will fire on desktop as well but does not have an effect because the navigation is always in view.

## Additional context

There is an horizontal overflow that causes some odd behavior when expanding an accordion within the navigation menu. That seems to be caused by `<code>` elements. I did not fix that here to keep the scope of the PR smaller but I can if it would be beneficial.
Ex: 
1. Open JavaScript reference doc site on mobile device
2. "Install via CDN" code block causes horizontal scroll (amongst others)

### CODE REVIEW

**Comment by gregnr** [comment]
Thanks @nick-krantz! Testing this out on mobile:
https://docs-git-fork-nick-krantz-14533-mobile-menu-fix-supabase.vercel.app/docs/reference/javascript/installing

The menu closing works great, but it seems that sometimes the links don't always go to the right sections anymore. Are you able to reproduce this?

**Comment by nick-krantz** [comment]
@gregnr I believe I found the root cause. When the mobile menu is open the `Container` component gets assigned a `width: auto !important` style. The change from `width: 100%` causes a shift vertically as all elements on the page have more or less horizontal space to be in.

I believe this shift is the cause of the sections not being scrolled into view properly and removing this style fixes the issue in my testing. Commit [7f801c3](https://github.com/supabase/supabase/pull/15588/commits/7f801c375b31aeb74e3a38fac07323198898bf21)

I don't see any negative side effects to this change but being a made from a Layout component it does impact all doc pages. There is some horizontal overflow on the mobile site but that seems to be preexisting.

Let me know what you think!

**Comment by charislam** [comment]
Hi @nick-krantz! Thanks so much for submitting this fix, and apologies for the delay in getting back to you! This PR seems to have slipped through the cracks.

I'm happy to merge this, do you mind just resolving the conflicts that have popped up in the meantime? Many thanks!

**Comment by nick-krantz** [comment]
> Hi @nick-krantz! Thanks so much for submitting this fix, and apologies for the delay in getting back to you! This PR seems to have slipped through the cracks.
> 
> I'm happy to merge this, do you mind just resolving the conflicts that have popped up in the meantime? Many thanks!

I should be able to get those fixed tonight, thanks @charislam!

**Comment by nick-krantz** [comment]
@charislam I apologize for the delay, conflicts fixed!

**Review by charislam — APPROVED** [review]

**Pull request merged**
