### PR TITLE
docs(snippets): add bash example for third party Oauth

### LINKED ISSUE #22275: No bash example in the documentation for Third-party login
# Improve documentation

## Link 

https://supabase.com/dashboard/project/<PROJECT_ID>/api?page=users

## Describe the problem

The javascript snippet is present but there is nothing for bash:
image

## Describe the improvement

Adding a short example would be helpful for people who don't want to go through the JS client.

### PR DESCRIPTION
**Pull request by frgfm**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

doc update by adding a bash snippet

## What is the current behavior?

There is a javascript snippet but no bash one.

## What is the new behavior?

Bash snippet added

## Additional context

Closes #22275

### CODE REVIEW

**Review by encima — APPROVED** [review]

**Comment by frgfm** [comment]
Oops, I just fixed prettier formatting @encima

**Comment by frgfm** [comment]
quick ping @encima, do we need another approval for merge? Or is there anything I should modify in the PR?

**Comment by encima** [comment]
@frgfm yes, we need approval from the frontend team. No need to do anything on your side, all good!

**Comment by frgfm** [comment]
Any update? Perhaps @charislam? :pray:

**Review by charislam — APPROVED** [review]
Thanks @frgfm and sorry for the delay! Looks great.

**Pull request merged**
