### PR TITLE
Docs: Update SvelteKit SSR example to match the SvelteKit v2 cookies API

### PR DESCRIPTION
**Pull request by Hugos68**
## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

Type error when using the current SSR SvelteKit example.
See: https://github.com/supabase/auth-helpers/issues/706#issuecomment-1895488327

## What is the new behavior?

A `path` variable is added by default besides the provided `options` to ensure the path is always set,
See: https://kit.svelte.dev/docs/types#public-types-cookies
image

## Additional context

-

### CODE REVIEW

**Comment by probablykasper** [comment]
Where did you see that the `path` should be `''`?

**Review by charislam — APPROVED** [review]

**Comment by charislam** [comment]
Awesome, thanks for this! Can you run a quick `npm run format` so it will pass our CI checks?

**Comment by Hugos68** [comment]
Sure! I couldn't find a CONTRIBUTING.md so I wasn't sure how to pass CI

**Comment by Hugos68** [comment]
It should pass CI now, I ran ``pnpm format`` in the root

**Comment by probablykasper** [comment]
This will likely mislead people to get unexpected errors

The [SvelteKit v2 migration guide](https://kit.svelte.dev/docs/migrating-to-sveltekit-2) explains:
> Most of the time, you probably want to use `path: '/'`, but you can set it to whatever you like, including relative paths — `''` means 'the current path', `'.'` means 'the current directory'.

**Pull request merged**
