### PR TITLE
Chore/allow selection of all rows in table editor

### PR DESCRIPTION
**Pull request by joshenlim**
- Allow selection of _all_ rows within the table editor (including those not visible within the current page)
- This selection is also scoped to within the current active filters and sorts
- Extended exporting to CSV and deletion of rows based on this ^
image

### CODE REVIEW

**Review by alaister — CHANGES_REQUESTED** [review]
Handy feature!

Works well aside from when trying to delete all my rows - getting:
`"no filters for this delete query"`
Is this due to some delete without a condition protection?

I also tried the export to CSV with a table containing 1,000,000 rows, and when I got bored of waiting for it to finish, I clicked the X to close the selection, but it looks like all the network requests continue in the background. I don't think this is a huge deal as it's kind of a niche use case.

**Comment by joshenlim** [comment]
ahh there was a safe guard against running a delete without filters haha - looking into that

> exporting 1,000,000 rows
yeah i was thinking about handling large tables too - it wouldn't be possible (atm) to try to do something such a heavy operation in the browser, until i can think of a better way to handle it perhaps for now i'll just reject exporting to CSV for any table above 500,000 rows

**Comment by joshenlim** [comment]
@alaister okay, added a truncate method for deletion of all rows on table with no active filters
also added a guard for CSV export on max no of rows

**Review by alaister — APPROVED** [review]
Nice!

**Pull request merged**
