### PR TITLE
Update kotlin docs to reflect new version

### PR DESCRIPTION
**Pull request by jan-tennert**
## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

Outdated documentation

## What is the new behavior?

New documentation with a new guide explaining how to set up deeplinking and custom serialization.

## Additional context

For some reason, the table showing the platform targets doesn't render properly. It does on `docs/guides/ai/managing-indexes` (I tested it there because there was another table).

~Also, I wouldn't merge this before the actual version comes out. I'm waiting on a dependency to update, but the rest is done.~

### CODE REVIEW

**Comment by gregnr** [comment]
Thanks @jan-tennert! Converting this to a draft until we're ready to merge, just so that it doesn't accidentally go in early.

**Comment by jan-tennert** [comment]
Just released the version, the docs should also be ready. There is still the problem with the table not getting rendered properly.

**Review by gregnr — APPROVED** [review]
@jan-tennert LGTM, nice one 👍 

I fixed the markdown table issue:
https://docs-git-fork-jan-tennert-master-supabase.vercel.app/docs/reference/kotlin/introduction

Should be good to merge - FYI we're dealing with some pipeline issues right now which is blocking this from merging. I'll keep you posted.

**Comment by gregnr** [comment]
Pipelines fixed! Thanks @jan-tennert 🙌

**Pull request merged**
