### PR TITLE
Chore/legal pages

### PR DESCRIPTION
**Pull request by joshenlim**
DPA

image

SOC2

image

### CODE REVIEW

**Comment by MildTomato** [comment]
@joshenlim ok to change the default country to united states ?

**Comment by joshenlim** [comment]
> @joshenlim ok to change the default country to united states ?

Oh yup! the default is US, was testing the phone placeholder stuff so clicked on US virgin islands

**Review by MildTomato — APPROVED** [review]

**Review by MildTomato — COMMENTED** [review]
maybe rename the DPA file to have a datestamp in the filename ? @joshenlim

**Comment by joshenlim** [comment]
> maybe rename the DPA file to have a datestamp in the filename ? @joshenlim

sure thing - we put it as today's date?

**Pull request merged**
