### PR TITLE
refactor: Vue and Nuxt 3 docs code snippets formatting

### LINKED ISSUE #11929: Proper format Vue and Nuxt code snippets on Quickstart docs
# Improve documentation

## Links

[Vue 3 Supabase Quickstart docs](https://supabase.com/docs/guides/getting-started/tutorials/with-vue-3)
[Nuxt 3 Supabase Quickstart docs](https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3)

## Describe the problem

I've noticed an inconsistency in the documentation regarding the formatting and styling of code snippets between the Vue and Nuxt sections. The current format of these code snippets does not align well with [Vue's](https://vuejs.org/guide/scaling-up/sfc.html) official documentation style.

## Describe the improvement

To improve the readability and usability of the documentation, I've made an effort to ensure that the Nuxt and Vue code snippets match Vue's official documentation styling and formatting by editing the files included in the PR. This will make it easier for developers to understand the Nuxt code snippets and how they relate to the Vue code snippets. I also changed the markdown code block language from html to vue for better code syntax formatting.

I have submitted a pull request with the changes I've made for review and would greatly appreciate it if someone could take a look and merge the changes.

Thank you for your time and consideration. Let me know if you have any questions or concerns.

Pull request: #11928

### PR DESCRIPTION
**Pull request by icarusgk**
## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

[Vue 3 Supabase Quickstart docs](https://supabase.com/docs/guides/getting-started/tutorials/with-vue-3)

Code snippets formatted with 2 spaces of indentation:

Screenshot_20230125_170855

[Nuxt 3 Supabase Quickstart docs](https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3)

Code snippets with `<script setup>` block after the `<template>` block

Screenshot_20230125_171049

## What is the new behavior?

The `<script setup>` doesn't have indentation and comes before the `<template> block to align better with [Vue's official docs](https://vuejs.org/guide/scaling-up/sfc.html) and with a [code snippet on Supabase](https://supabase.com/docs/guides/getting-started/quickstarts/vue)

Frame 1

## Additional context

Link to issue: #11929

Vue's official docs:

Screenshot_20230125_171801

### CODE REVIEW

**Comment by dannykng** [comment]
@silentworks mind taking a look at this? 🙏🏼

**Review by silentworks — APPROVED** [review]

**Comment by silentworks** [comment]
This isn't passing the  code check with Prettier due to the formatting, you might need to add some `prettier-ignore` inline comments in the code for this to work.

**Comment by icarusgk** [comment]
> This isn't passing the code check with Prettier due to the formatting, you might need to add some `prettier-ignore` inline comments in the code for this to work.

Working on it right away 🖖🏼

**Comment by icarusgk** [comment]
With the fixes, it seems to no longer throw errors:

image

**Review by silentworks — APPROVED** [review]

**Pull request merged**
