### PR TITLE
fix: changed nextjs-icon.svg file

### LINKED ISSUE #5931: Nextjs icon not visable in light mode
# Bug report

## Describe the bug

The Nextjs icon in the studio is not visible in light mode.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [app.supabase.io/project/ref](https://app.supabase.io/project/ref)
2. Click on theme toggle
3. Scroll down to Example projects

## Expected behavior

The nextjs icon is visible.

## Screenshots

Screen Shot 2022-03-14 at 8 41 09 PM
Screen Shot 2022-03-14 at 8 41 22 PM

## System information

- OS: Any
- Browser: Any
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

The same could be said for the expo icon.

### PR DESCRIPTION
**Pull request by devnamrits**
## What kind of change does this PR introduce?

Bug fix #5931 

## What is the current behavior?

The current svg icon for nextjs-icon is light-themed due to which it fades away in light theme and is prominently visible only in dark theme.

## What is the new behavior?

Due to this change, the icon is clearly visible in both light and dark themes.

## Additional context

Screenshot 2022-03-18 at 12 54 54 AM

### CODE REVIEW

**Comment by Isaiah-Hamilton** [comment]
@devnamrits these changes only seem to work in light mode now, which defeats the purpose of the issue. We want to want to change the icon based on the theme provider. for example:

```js
theme == 'dark' ? '/img/nextjs-icon-dark.svg' : '/img/nextjs-icon-light.svg'
```

**Comment by devnamrits** [comment]
Hi @Isaiah-Hamilton I initially did something like this only:
`theme == 'dark' ? '/img/nextjs-icon-dark.svg' : '/img/nextjs-icon-light.svg'`
But since the content more specifically images is not being updated when there is a change in theme. I assume this is because there are not being stored in the `UIstore` or any other kind of store.
The above thing works only when we refresh the page each time after theme switching else images don't replace. This was the issue that I stated in point two of my initial comment. Please help.

**Comment by devnamrits** [comment]
Hi @Isaiah-Hamilton , Any suggestions?

**Comment by Isaiah-Hamilton** [comment]
Hey @devnamrits - Sorry for the late response. What you could try is maybe turning all the icons into a react component. For Example, like this [github.com/HarryET/custodi/blob/main/components/LoginIcons.tsx](https://github.com/HarryET/custodi/blob/main/components/LoginIcons.tsx).

**Comment by Isaiah-Hamilton** [comment]
Closing because of inactivity and this has already been fixed https://github.com/supabase/supabase/pull/6733

**Pull request closed without merging**
