### PR TITLE
feat: transfer project to another org

### PR DESCRIPTION
**Pull request by kevcodez**
Feature is only available for us internally for now, until we've done further testing and docs

Screenshot 2023-06-28 at 17 00 48

Screenshot 2023-06-28 at 16 58 16

Screenshot 2023-06-28 at 16 58 10

### CODE REVIEW

**Comment by saltcod** [comment]
(changed the wording here a touch) but 2 things:

1. the first link is to a Notion page 
2. I don't see where on the org page in the second link (http://localhost:8082/org/_/general) to change to org-level billing. Is that the right?
 
CleanShot 2023-06-28 at 15 30 10@2x

**Comment by saltcod** [comment]
I'm not seeing a project dropdown b/c: 

this returns `[]` 

CleanShot 2023-06-28 at 15 32 18@2x


then this fails: 

CleanShot 2023-06-28 at 15 33 06@2x

**Comment by kevcodez** [comment]
> (changed the wording here a touch) but 2 things:
> 
> 1. the first link is to a Notion page 
> 2. I don't see where on the org page in the second link (http://localhost:8082/org/_/general) to change to org-level billing. Is that the right?
>  
> CleanShot 2023-06-28 at 15 30 10@2x
> 

Check first paragraph on notion page. It's just for us and WIP, will eventually link to our docs.

Check the other PR for the self serve migration

**Comment by kevcodez** [comment]
> I'm not seeing a project dropdown b/c: 
> 
> this returns `[]` 
> 
> CleanShot 2023-06-28 at 15 32 18@2x
> 
> 
> then this fails: 
> 
> CleanShot 2023-06-28 at 15 33 06@2x
> 

I see, we can always render it

**Review by saltcod — APPROVED** [review]

**Pull request merged**
