### PR TITLE
feat: Add new RLS Policy template for insert

### LINKED ISSUE #15416: Add new RLS Policy template for insert
Create a new RLS policy template for insert based on user_id. 
We currently have one for delete but not for insert, which is also extremely common:

CleanShot 2023-06-28 at 11 45 40@2x

### PR DESCRIPTION
**Pull request by a0m0rajab**
## What kind of change does this PR introduce?

This adds an extra template for insert policy based on the `Add new RLS Policy template for insert ` issue

fixes #15416

### CODE REVIEW

**Review by ivasilov — APPROVED** [review]

**Review by ivasilov — DISMISSED** [review]
The `WITH CHECK expression` field is empty when trying to use the new policy template. Can you take another look?

**Comment by a0m0rajab** [comment]
@ivasilov thank you for that, just added checks, if there is anything to fix could you mention that? 
thanks!

**Comment by a0m0rajab** [comment]
Is there anything I need to do for this PR @ivasilov

**Review by saltcod — APPROVED** [review]

**Comment by a0m0rajab** [comment]
@saltcod Thank you!

**Pull request merged**
