### PR TITLE
Added Descope as a Provider

### PR DESCRIPTION
**Pull request by gaokevin1**
## What kind of change does this PR introduce?

Added Descope as a Provider

## What is the current behavior?

Currently many of our customers are forced to use custom SAML applications with Supabase, but we want to provide them the option to use their custom OIDC applications and have a more "native" experience with integrating Descope as an OAuth provider, through their use of the Supabase SDK.

## What is the new behavior?

Descope, as an authentication provider, has been added a standard Auth Provider, using the OAuth 2.0 standard.

### CODE REVIEW

**Comment by hf** [comment]
Hi @gaokevin1, thank you for the contribution. At this time we've got a moratorium on new social providers. It's very hard for the Auth team to maintain many of them (it's a small team) -- and especially the small ones like Descope.

We plan to have custom OAuth and OIDC provider support as early as possible in 2024, and at that point your integration guide can be based on the new primitives.

I'd appreciate it if you could wait a little for this.

**Comment by gaokevin1** [comment]
Hi @hf,

I appreciate you taking the time to look over my PR. I also can totally understand where you're coming from, with it being hard to manage all of the auth providers being a small team is all.

However, I could kindly ask that you reconsider adding Descope as an Auth Provider, as a one-time exception to your policy. Since we've launched our NextJS SDK, we've seen a huge spike in Supabase customers using Descope for their authentication. Descope has 10k+ developers and many more users that are using our platform as a CIAM workflow solution for their authentication.

Currently all of our Descope + Supabase customers are either using Descope as a SAML provider (if they are enterprise-tier customers) or using generic `SupabaseAuth` and RLS policies like in our sample app [here](https://github.com/descope-sample-apps/supabase-descope-todo-list). We're also in the process of working on a blog that will help promote using Descope with Supabase, based on the two solutions outlined above.

Having Descope as a native provider would make it very easy for customers of yours as well as ours to set-up Supabase with Descope in their application. The purpose of this is really to improve the efficiency and lack of complexity in integration between our two platforms.

Thank you for your consideration, and I look forward to hearing back from you.

**Comment by gaokevin1** [comment]
Hi @hf ,

Any updates on this? Would it be possible to make an exception for this particular provider?

Thanks!

**Comment by saltcod** [comment]
Hi all — checked with the auth team again re: this one and the decision remains the same given the realities of maintenance with a small team. I'm going to mark this one as closed, but appreciate the effort.

**Pull request closed without merging**
