### PR TITLE
Example: Todo app using Vue + TS

### PR DESCRIPTION
**Pull request by chiubaca**
## What kind of change does this PR introduce?
Example todo app based on the [Next.js example](https://github.com/supabase/supabase/tree/master/examples/todo-nextjs), but built with Vue.js Composition API and TypeScript instead.

## Additional context
Related to #213

### CODE REVIEW

**Comment by chiubaca** [comment]
All features have been faithfully rewritten in Vue +TS. Just doing some final tweaks and code tidyup.

**Comment by kiwicopple** [comment]
wow, this is impressive @chiubaca . Nice work

**Comment by chiubaca** [comment]
cheers @kiwicopple! I was able to reuse all the tailwind styling and repurpose most of the react hooks so was not a biggie. Was fun to build. Loving the platform so far, looking forward to experimenting some more.

I think this is ready now for review now. 

I did notice that my [implementation of signing in with a magic link](https://github.com/chiubaca/supabase/blob/vue3-ts-example/examples/todo-vue3-ts/src/vuetils/useAuth.ts#L11) is returning a Syntax Error in the response object. I beleive it's happening in the [Next implementation too](https://github.com/supabase/supabase/blob/3d2c8c7ee93e36017a82a85208771880ac9aeb63/examples/todo-nextjs/components/Auth.js#L8). Not sure if its a bug with the sdk or an implementation issue? Happy to raise an issue.

**Comment by kiwicopple** [comment]
> I did notice that my implementation of signing in with a magic link is returning a Syntax Error in the response object. 

I think this might be the middleware which needs upgrading. We are doing that today. Let me merge this, and if it's not resolved in a couple of days then we can start a new issue. 

This is a great contribution @chiubaca. Welcome to the community ⚡

**Pull request merged**
