### PR TITLE
Twitter logo may be need to update as new 'X' logo

### PR DESCRIPTION
**Pull request by po1so9**
## What kind of change does this PR introduce?

Bug fix, fixed the twitter logo (X) at the homepage

## What is the current behavior?
https://github.com/supabase/supabase/issues/16671

## What is the new behavior?
Showing new Twitter logo( X ) at the home page.
Supabase _ The Open Source Firebase Alternative - Brave 22-08-2023 18_22_24

### CODE REVIEW

**Review by hieuwu — COMMENTED** [review]
It would be nice if you find other places that are using the old Twitter icon and replace them as well. Also double check for light theme

**Comment by po1so9** [comment]
> It would be nice if you find other places that are using the old Twitter icon and replace them as well. Also double check for light theme

Sure, I'll replace it if I see one also it is working as intended with the light theme as well.

**Comment by saltcod** [comment]
Hey there — thanks for this!

Looks like there's this one as well, if you could please have a look!

CleanShot 2023-08-22 at 12 01 49@2x

**Comment by EngHasanSabbir** [comment]
In dark mode, I think this logo is looking more gorgeous

image

**Comment by po1so9** [comment]
> In dark mode, I think this logo is looking more gorgeous
> 
> image

yeah, I also noticed that but the logo is very small and the X lines are very thin which makes it hard to see also you can see that the screenshot you added has a black background which makes it easier to add the logo and there are not a lot of X logos out there may be in future if I find a better one I'll update it. I'm still going through the whole file structure to understand the project better.

**Pull request closed without merging**
