### PR TITLE
Feat: CRUD custom reports

### PR DESCRIPTION
**Pull request by jordienr**
## What kind of change does this PR introduce?

- Allows users to create, delete, update and read many custom reports

## What is the current behavior?

You can only create one custom report

## What is the new behavior?

Users can now create more than one custom.

## Additional context

CleanShot 2024-02-08 at 15 41 52@2x
CleanShot 2024-02-08 at 15 42 03@2x

### CODE REVIEW

**Review by kiwicopple — APPROVED** [review]
lfg 🔥

**Comment by saltcod** [comment]
Awesome @jordienr !

Couple of small things:

When the first report is created, the query isn't getting revalidated here I think? 
screenshot-2024-02-08-at-12 11 40

This takes a second —a <loading> spinner would be good there onSubmit
screenshot-2024-02-08-at-12 12 56

**Comment by joshenlim** [comment]
Could we update the "Create report" CTA when we land on the reports page and there's no custom reports to open the modal that "Create new custom report" in the side menu does? so that the behaviour is consistent

**Comment by joshenlim** [comment]
Also some QOL improvements at the top of my mind

given that we support descriptions in the reports, lets add it below the title too
image

and also add an edit button beside the title, on hover of the title, to edit the title/description (by opening the edit report modal)

**Comment by joshenlim** [comment]
there seems to be some lag when going between custom reports - are the contents not cached in react query?

**Review by saltcod — APPROVED** [review]

**Pull request merged**
