### PR TITLE
feature/example todo sveltejs

### LINKED ISSUE #215: Example: Todo App using Svelte
# Feature request

## Is your feature request related to a problem? Please describe.

New example use case

## Describe the solution you'd like

- Create a initial React app in `examples/todos-svelte` using Svelte.js
- Build a todo list app, using Supabase as the backend. Use the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example.
- Should include logins + policies
- Add a one-click deploy using Vercel deploy button

## Additional context

- Ant has done an example [here](https://github.com/supabase/supabase/tree/master/examples/todo), which is a good baseline
- Keep it as simple as possible - for styling we can use Tailwind

### PR DESCRIPTION
**Pull request by duncanhealy**
- csa - sveltejs template with tailwind via csa #215
- todo template step 1 #215
- use https://github.com/sveltejs/svelte-todomvc/ #215
- change styles to tailwind #215
- move items to todos import #215
- add supabase dep #215
- env example #215
- doc: installation steps #215
- change to use SNOWPACK env variables #215
- add env plugin to snowpack #215
- wip: add item query to svelte todo example
- wip: add crud to task list svelte todo
- feat: add env to snowpack plugins #215
- make sparse-checkout command for example repo #215
- add to License #215
- wip: pre split into components todo svelte #215
- wip: split to components todo svelte #215
- wip: cleanup names #215

### CODE REVIEW

**Comment by duncanhealy** [comment]
deletes still do not work - they go to REST endpoint but return with no error waiting on #245

**Comment by kiwicopple** [comment]
Hey @duncanhealy is that the final thing you're waiting on? If that's the case I'm happy to merge this in 👍

**Comment by duncanhealy** [comment]
yea should be good to go once we can debug/fix the deletes

**Comment by kiwicopple** [comment]
Legend, thanks @duncanhealy - amazing work on this one.

**Pull request merged**
