### PR TITLE
fix: Buttons wrapped in Links should just be styled anchor tags

### PR DESCRIPTION
**Pull request by brandongregoryscott**
## What kind of change does this PR introduce?

Bug fix/accessibility improvement

## What is the current behavior?

I noticed when tabbing through the .com site that certain elements would actually require two tabs to get to the next element. This is due to the `<a>` tag that is being rendered around the `<Button>` component, since both are tabbable.

Before change - Button-styled anchors require 2 tabs

## What is the new behavior?

For accessibility purposes, all of these should be represented as links since they take you to another page, so I've removed the wrapping `a` or `Link` components.
 
The `Button` component already has an `as` prop to allow it to be rendered as any basic HTML element, but it didn't have the typing to support props that `a` elements have, which lead to people using `ts-ignore` comments. Based on some types in `ui-box` and @MildTomato's suggestion, I added a more advanced type that better supports polymorphism using the `as` prop.

After change - elements only require 1 tab

## Additional context

The original issue with using `Button`s that were links throwing errors in the studio (https://github.com/supabase/supabase/pull/13540#issuecomment-1505152745) should be fixed now with the ref changes in https://github.com/supabase/supabase/pull/13580 - the `SignInLayout` in the studio package is no longer throwing a runtime error, so this should be safe to move forward with 🎉

### CODE REVIEW

**Comment by MildTomato** [comment]
@brandongregoryscott this might break tests in /studio.
worth checking that first

**Comment by brandongregoryscott** [comment]
@MildTomato Studio tests are passing, should they be? 😛 The button implementation didn't change, just the types. I can add some tests to these two changed components, though!

```
studio:test: Test Suites: 19 passed, 19 total
studio:test: Tests:       8 skipped, 4 todo, 276 passed, 288 total
studio:test: Snapshots:   0 total
studio:test: Time:        145.869 s
studio:test: Ran all test suites.

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2m29.231s 
```

**Comment by MildTomato** [comment]
@brandongregoryscott you might be interested in this.
PR from a long time ago adding in types for `as` prop

**Comment by MildTomato** [comment]
> Also, I went back and noticed there were a lot more of these anchor-wrapped-buttons on the homepage.

Yea we have them everywhere. We used to use `<Button as="a">` everywhere but it started breaking our tests in /studio so I just changed them all as a temporary fix. 

Your right though, it needs fixing and all the sites can be updated to have `<Button as="a">` again 🚀

> I can make some > follow-up PRs to tackle these if we're happy with the current implementation.

That would be great!

**Comment by brandongregoryscott** [comment]
I think this should do it! We have a similar type in `ui-box` that pulls the basic HTML attributes that I used for reference: https://github.com/segmentio/ui-box/blob/master/src/types/box-types.ts#L13

image
image

On another note...
I didn't end up messing with the `ref` type, which is currently `any`. I think we can remove the imperative handle and `RefHandle` type in favor of just using the forwarded ref, but it'd be nice to have a test for it. I see there's some tests in https://github.com/supabase/supabase/blob/master/packages/ui/src/components/Button/Button.test.js, but I'm not seeing any `test` script in the packages/ui folder, and the `test` script in the root directory seems to fail. 

Do these tests not run currently? Can also open up another issue/PR to iron these out!

```sh
> supabase@0.0.0 test
> jest

● Validation Error:

  Module <rootDir>/tests/jest-env in the setupFiles option was not found.
         <rootDir> is: /Users/Brandon/oss/fork/supabase

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

**Comment by MildTomato** [comment]
> Do these tests not run currently? Can also open up another issue/PR to iron these out!

that would be awesome

**Comment by MildTomato** [comment]
This looks great @brandongregoryscott - i'll have a proper look soon, but I think we can get this in

**Comment by MildTomato** [comment]
@brandongregoryscott i changed 1 button in studio just to double check this works.
will need to make sure studio tests pass and also just make sure the there's no client errors when viewing the page.

**Comment by brandongregoryscott** [comment]
>Added into the 'sign in' layout.

Hmm, I am seeing a React error on the deployed Studio preview:

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I'm seeing this locally as well, and I think it is due to the next `Link` component that is wrapping it. This seems to work:

```diff
-<Link href="https://supabase.com/docs" passHref>
-  <Button type="default" icon={<IconFileText />} as="a" target="_blank">
+  <Button type="default" icon={<IconFileText />} as="a" target="_blank" href="https://supabase.com/docs">
    Documentation
  </Button>
-</Link>
```

I'll dig into this more later - not entirely sure why wrapping it would cause an infinite loop.

**Comment by MildTomato** [comment]
@brandongregoryscott you found our original issue.

This is why we ended up taking out all the `as="a"` temporarily.

**Comment by brandongregoryscott** [comment]
I think it should probably safe to use assuming it isn’t being wrapped by the next `Link` (what would the `as=“a”` be for then anyway?) but it is worth looking into as to why it blows up :sweat_smile: 

Maybe we hold off on this PR until the tests are up & running and we can test for this.

Based on https://github.com/vercel/next.js/issues/42902, we might need to memoize the `CustomButton` that is declared in-line so it isn't creating a new reference on every render.

**Comment by brandongregoryscott** [comment]
@MildTomato seems like the way the ref was setup in the Button was the culprit - I've removed the imperative handle and added some tests to cover it on this other branch: [`55f9a89` (#13580)](https://github.com/supabase/supabase/pull/13580/commits/55f9a89294e3a1a3cc8447bf0afedaec7da99e65). Tested it out on the sign-in page and it no longer crashes 🎉

**Comment by MildTomato** [comment]
@brandongregoryscott nice - lets get this in and keep going 🚀

**Comment by brandongregoryscott** [comment]
@MildTomato should I merge in my other branch here so the ref changes can be tested alongside the changes here to unwrap the extra `a` tags? or would we prefer to get #13580 in first?

**Comment by brandongregoryscott** [comment]
@MildTomato Anything I can do to help get this over the line? 🙏

**Comment by MildTomato** [comment]
hey, sorry @brandongregoryscott - this got forgotten about. looking into this now.

**Comment by MildTomato** [comment]
I'm thinking maybe we do it like [this](https://github.com/supabase/supabase/pull/14999)

And we use `asChild` prop, which seems to have become a bit of a standard now.

then you'll have 

```js
<Button asChild><Link href="/foo">Hello World</Link></Button>
```

**Comment by brandongregoryscott** [comment]
Ah, interesting! It seems like that PR might make this one obsolete, so feel free to close it out.

**Comment by oarsheo** [comment]
[Code Review AI](https://github.com/marketplace/code-review-ai): `apps/www/components/Hero/Hero.tsx`

The code seems to be well-written and follows good practices. However, there is a small suggestion for improvement:

1. The `onClick` event handlers are directly using anonymous functions. This can lead to unnecessary re-renders in React as a new function is created on each render. It would be better to define these functions outside of the JSX and reference them in the `onClick` handlers. 

Here is an example of how you could do this:

```jsx
const handleStartProjectClick = () => sendTelemetryEvent(gaEvents['www_hp_hero_startProject']);
const handleDocumentationClick = () => sendTelemetryEvent(gaEvents['www_hp_hero_documentation']);

// ...

<Button
  as="a"
  href="https://app.supabase.com"
  size="medium"
  className="text-white"
  onClick={handleStartProjectClick}
>
  Start your project
</Button>
<Button
  as="a"
  href="/docs"
  size="medium"
  type="default"
  icon={<IconBookOpen />}
  onClick={handleDocumentationClick}
>
  Documentation
</Button>
```

This way, the same function reference is used across renders, which can help to avoid unnecessary re-renders.

----

[Code Review AI](https://github.com/marketplace/code-review-ai): `apps/www/components/Nav/index.tsx`

1. Code Duplication: The same URL "https://supabase.com/dashboard" is used twice. It's better to store it in a variable and use the variable instead. This will make the code easier to maintain.

```jsx
const dashboardUrl = "https://supabase.com/dashboard";

<Button
  as="a"
  href={dashboardUrl}
  type="default"
  className="hidden lg:block"
>
  Sign in
</Button>
<Button
  as="a"
  href={dashboardUrl}
  className="hidden text-white lg:block"
>
  Start your project
</Button>
```

2. Use of `target="_blank"`: When using `target="_blank"`, it's recommended to also include `rel="noopener noreferrer"` to prevent potential security issues.

```jsx
<Button
  as="a"
  href="https://github.com/supabase/supabase"
  target="_blank"
  rel="noopener noreferrer"
  className="hidden group lg:flex"
  type="text"
>
  Star us on GitHub
</Button>
```

**Pull request closed without merging**
