### PR TITLE
chore/logs: LogsPreviewer query building logic refactor

### PR DESCRIPTION
**Pull request by Ziinc**
Refactor of logs query building logic of filters for better code quality & clarity.

This PR will also reduce number of requests made, speeding up refresh times as well as reducing redundant server calls.

- [x] manually test functions previewer
- [x] manually test api previewer
- [x] manually test db previewer

### CODE REVIEW

**Comment by MildTomato** [comment]
Looks like an issue with one of the SQL_FILTER_TEMPLATES templates.
search_query seems to return the whole JS function into SQL when 'exploring via query' (ie, logs explorer)

Screenshot 2022-04-06 at 2 43 41 PM
.

**Comment by Ziinc** [comment]
image
fixed the sql generation, also added some unit tests for the generator function.

**Comment by MildTomato** [comment]
manually tested function logs. looks good.

**Review by MildTomato — APPROVED** [review]
⚡️ awesome!

**Pull request merged**
