### PR TITLE
fix SQL typo in query-optimization.mdx

### PR DESCRIPTION
**Pull request by heloineto**
## I have read the [CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md) file.

YES

## What kind of change does this PR introduce?

Fix typo in SQL

### CODE REVIEW

**Review by Hallidayo — APPROVED** [review]
Good spot @heloineto! thank you 👍

**Comment by charislam** [comment]
Thanks @heloineto! For some reason Prettier has an issue with this, do you mind running a quick `npm run format` so this will pass our merge checks?

**Comment by heloineto** [comment]
> Thanks @heloineto! For some reason Prettier has an issue with this, do you mind running a quick `npm run format` so this will pass our merge checks?

I'm getting many different errors while running `npm install` and I do not have the time to debug them. I really don't see why this check would fail for the change made, and I believe this problem existed before this PR.

Feel free to close this PR and let someone who already has this project setup on their machine fix it.

**Comment by charislam** [comment]
Ahh, didn't realize you didn't already have the repo set up on your machine, or I wouldn't have asked. No problem, pushed the formatting change!

**Comment by heloineto** [comment]
> Ahh, didn't realize you didn't already have the repo set up on your machine, or I wouldn't have asked. No problem, pushed the formatting change!

Thank you a lot!

**Pull request merged**
