### PR TITLE
Fix database replications page tables not toggling realtime properly

### PR DESCRIPTION
**Pull request by joshenlim**
Issue was because we were passing `selectedPublication` via react state, when we should be using the meta store to retrieve the selected publication - because of this, the client state for tables that were toggled for realtime was always stale

### CODE REVIEW

**Review by alaister — APPROVED** [review]
Nice one! Works well for me 👍🏻

Small side note maybe for a separate PR: it'd be cool to have some text to say "no publications found" when filtering if no results are returned. wdyt?

**Comment by joshenlim** [comment]
> it'd be cool to have some text to say "no publications found" when filtering if no results are returned. wdyt?

I can get this one within this PR - it was probably something that was overlooked when we first built this page

**Comment by joshenlim** [comment]
just fyi i'm going with a very simple, existing no search results ui component
definitely can be improved but one for next time
image

**Comment by alaister** [comment]
Looks great!

**Comment by joshenlim** [comment]
did the same thing for database/tables and database/extensions for consistency

**Pull request merged**
