### PR TITLE
Fix/studio file upload validation

### LINKED ISSUE #6012: Unable to upload CSV from a Windows OS
# Bug report
Error when uploading a CSV file to Supabase dashboard.

## Describe the bug
Tried it on a Windows OS, on 3 different browsers (Chrome, Edge, Firefox) got the same error.
It might be something related to the OS since its working on MAC.

## To Reproduce
1. Go to 'Database'
2. Click on 'New'
3. Click on 'Import data via spreadsheet'
4. Import the CSV file 
5. See error

## Expected behavior
To be able to upload a CSV file without errors.

## Screenshots
image

## System information
- OS: [Windows]
- Browser [Chrome, Firefox, Edge]

Linked ticket : https://support.supabase.org/a/tickets/5456

### PR DESCRIPTION
**Pull request by bVNyDUKE**
## What kind of change does this PR introduce?

Bug fix https://github.com/supabase/supabase/issues/6012

## What is the current behavior?

Currently, CSV files cannot be uploaded from Windows without a user end registry hack to chang the MIME type mapping.
Issue [here](https://github.com/supabase/supabase/issues/6012#issue-1177335263)

Additionally, users are able to attempt uploading xlsx files which can cause errors

## What is the new behavior?

CSV is now able to be uploaded from Windows and XLSX is properly rejected automatically.

## Additional context

Additional discussion [here](https://github.com/supabase/supabase/discussions/5953)

With this change users are still able to manually change xlsx file extensions to either csv or tsv and attempt an upload.
This causes errors like previously, but at least now it requires the user to do something intentionally wrong for the error to occur.

### CODE REVIEW

**Comment by pucho** [comment]
@bVNyDUKE Could you please merge master, it looks good to me but I haven't been able to reproduce on my windows box. I'll review again after the merge. Thanks!

**Comment by bVNyDUKE** [comment]
@pucho  Thanks for reviving this. Master merged.

**Comment by pucho** [comment]
@bVNyDUKE I'll take a look as soon as I get back to my windows box over the weekend. Thanks for the update!

**Review by pucho — APPROVED** [review]
LGTM

**Pull request merged**
