### PR TITLE
Chore: update new docs ui

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

Update new docs to match current docs.

## What is the current behavior?

https://user-images.githubusercontent.com/70828596/171325727-f950c76e-3ea1-4ed5-aa0c-663495db06a6.mp4

https://user-images.githubusercontent.com/70828596/171325770-1e9e266e-dcaa-4214-a0c5-ce33716f5184.mp4

## What is the new behavior?

https://user-images.githubusercontent.com/70828596/171555764-1ba8a8d8-042f-4346-9941-9a6ea9078641.mp4

https://user-images.githubusercontent.com/70828596/171555792-2f724bca-e274-4963-886e-5ebbfd760414.mp4

### CODE REVIEW

**Comment by MildTomato** [comment]
🔥 🔥

**Review by kiwicopple — APPROVED** [review]

**Comment by kiwicopple** [comment]
Epic @Isaiah-Hamilton. Should we merge this and get it deployed on vercel?

@MildTomato - would you mind helping with the vercel deployment?

**Comment by Isaiah-Hamilton** [comment]
@kiwicopple I Think we should hold off for little while before deploying to vercel. The site still feels a little sluggish and still needs some improvements.

**Comment by kiwicopple** [comment]
Yeah I think we just need a Preview environment to check out and compare. Whenever you're ready @Isaiah-Hamilton 👍

**Pull request merged**
