### PR TITLE
feat: add alert for restart of projects scheduled for migration, showing planned maintenance window

### PR DESCRIPTION
**Pull request by thebengeu**
Collapsible collapsed:
Screenshot 2024-03-05 at 12 59 29

Collapsible expanded:
Screenshot 2024-03-05 at 12 59 38

### CODE REVIEW

**Comment by MildTomato** [comment]
@thebengeu is there a blog post / docs / changelog we can link to explaining more about this?

**Comment by MildTomato** [comment]
Feedback: I think we should front load the important information and lead with the important fact, that there is upcoming downtime.

```markdown
** Upcoming downtime scheduled **

This project will automatically restart on 4th April between 20:00 and 20:30
> Why this time? (collapse component)

You can manually restart this project anytime before then at a time that is convenient for you.

_Find out more about our v2 infrastructure migration_
```

**Comment by thebengeu** [comment]
@MildTomato Will make the updates you suggested.

> @thebengeu is there a blog post / docs / changelog we can link to explaining more about this?

There will be a GitHub discussion, which we'll link to by updating the `v2AnnouncementUrl` flag.

**Comment by thebengeu** [comment]
@MildTomato made the changes you suggested, PTAL.

**Review by MildTomato — APPROVED** [review]
lgtm. another review from FE would be good

**Review by joshenlim — APPROVED** [review]

**Review by alaister — APPROVED** [review]

**Pull request merged**
