### PR TITLE
Update testing.mdx fixing incorrect command 

### PR DESCRIPTION
**Pull request by kav**
the db test command is `supabase db test` not `supabase test db` also the path appears to be incorrect (doesn't find the test there). Debugging that now.

### CODE REVIEW

**Comment by sweatybridge** [comment]
Hi @kav, I've added clarification to the docs that the min supported cli version is v1.11.4 (released ytd). Please upgrade and have another try. `test db` should be working as documented.

If you encounter any problems, feel free to file an issue at https://github.com/supabase/cli.

**Comment by kav** [comment]
That fixed finding tests but the PR here is still valid in correcting the incorrect parameter order

**Comment by sweatybridge** [comment]
In the latest CLI, `supabase db test` and `supabase test db` are simply aliases. Reason for this change is that we are planning to expand the scope of testing to include other platform features, like functions, storage, etc. For example, you will be able to call `supabase test function` in the future run function tests.

Atm, you can continue using `db test` but that won't be appearing in our docs anymore since it's a just an alias to the top level command.

**Comment by kav** [comment]
Ah perfect, sorry for the noise

**Pull request closed without merging**
