### PR TITLE
Make oss repos dynamic

### PR DESCRIPTION
**Pull request by Isaiah-Hamilton**
## What kind of change does this PR introduce?

An updated version of the original pull request https://github.com/supabase/supabase/pull/4591 by @HarryET, To make the OSS page repos dynamic.

### CODE REVIEW

**Comment by HarryET** [comment]
Would it have made sense to continue this in the original PR? I have allow edits by maintainers on ...

**Comment by kiwicopple** [comment]
looks pretty good @Isaiah-Hamilton 👍 / happy to approve and merge whenever you want to move out of Draft

**Comment by MildTomato** [comment]
Anyone need help with this? Looks like this PR is stuck

**Comment by Isaiah-Hamilton** [comment]
> Anyone need help with this? Looks like this PR is stuck

This pull request just needs to be reviewed and merged.

**Review by kiwicopple — APPROVED** [review]

**Pull request merged**
