### PR TITLE
feat: s3 + clickhouse wrapper ui

### PR DESCRIPTION
**Pull request by alaister**

### CODE REVIEW

**Comment by joshenlim** [comment]
minor - might need some client side validation for the column names when creating an s3 wrapper to ensure that length > 0

**Comment by joshenlim** [comment]
minor - add some padding at the bottom of the s3 wrapper form
image

**Comment by joshenlim** [comment]
perhaps we can be more explicit in the description here: "Map to a file in S3 (CSV or JSON only)"
image

**Comment by joshenlim** [comment]
In S3 wrapper (not sure if common component), maybe just true or false as options here? or is `---` an actual possible value
image

**Review by kiwicopple — APPROVED** [review]

**Pull request merged**
