### PR TITLE
teste for format for action

### PR DESCRIPTION
**Pull request by carlosstenzel**
Test format
https://github.com/supabase/supabase/pull/1659

### CODE REVIEW

**Comment by inian** [comment]
Hi @carlosstenzel, can you ignore the generated files in the prettier format? This leads to a messy commit history because everytime a user [re-generates the docs](https://github.com/supabase/supabase/blob/master/web/README.md), they get un-prettified and GH action prettifies it again. 

We can either 
- ignore generated files for prettier action
- or add the prettier to generated commands like `npm run gen:supabase`

**Comment by carlosstenzel** [comment]
we can skip some folders or use it only for some folders

**Comment by carlosstenzel** [comment]
ex:

npx prettier --write './www/*'  
npx prettier --write './web/*' 
..

**Comment by carlosstenzel** [comment]
Or ignoring
https://prettier.io/docs/en/ignore.html

**Pull request closed without merging**
